In [1]:
import pandas as pd

# Replace 'file_path.xlsx' with the path to your Excel file
file_path = r"C:\Research-Paper\PAPER-WORK-2024\Outputs\Spider-Data-7.xlsx"

# Read the Excel file into a DataFrame
df = pd.read_excel(file_path)

# Display the first few rows of the DataFrame
df.head()

,db_id,spider_query,question,text2sql_query
0,farm,SELECT count(*) FROM farm,How many farms are there?,"SELECT COUNT(DISTINCT f.Farm_ID) FROM ""farm"" f;"
1,farm,SELECT count(*) FROM farm,Count the number of farms.,"SELECT COUNT(DISTINCT f.""Farm_ID"") FROM ""farm"" f;"
2,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,List the total number of horses on farms in as...,"SELECT f.""Farm_ID"", f.""Year"", f.""Total_Horses""..."
3,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,"What is the total horses record for each farm,...","SELECT f.Farm_ID, f.Total_Horses FROM farm f O..."
4,farm,SELECT Hosts FROM farm_competition WHERE Theme...,What are the hosts of competitions whose theme...,SELECT DISTINCT fc.Hosts FROM farm_competition...

In [2]:
df.shape

(719, 4)

In [3]:
def calculate_accuracy(results):
    return (results.count(True) / len(results))*100

## Approach 1:Edit Distance

In [3]:
#!pip install Levenshtein

In [4]:
import Levenshtein

def normalized_edit_distance(str1, str2):
    """
    Calculate the normalized edit distance between two strings.
    
    Args:
        str1 (str): The first string.
        str2 (str): The second string.

    Returns:
        float: The normalized edit distance considering string lengths.
    """
    # Calculate raw edit distance using Levenshtein
    edit_distance = Levenshtein.distance(str1, str2)
    
    # Normalize by average string length
    avg_length = (len(str1) + len(str2)) / 2
    normalized_distance = edit_distance / avg_length if avg_length > 0 else 0
    
    return normalized_distance

In [5]:
def edit_dist_match(query1,query2):
    query1 = query1.lower()
    query2 = query2.lower()
    ed = normalized_edit_distance(query1, query2)
    print(f"Normalized Edit Distance Similarity: {ed}")
    return ed

In [6]:
query1 = "SELECT COUNT(*) FROM farm;"
query2 = """SELECT f."Farm_ID", f."Total_Horses" FROM "farm" f ORDER BY f."Total_Horses" ASC;"""
edit_dist_match(query1,query2)

Normalized Edit Distance Similarity: 1.158878504672897

1.158878504672897

In [86]:
query1 = "SELECT COUNT(*) FROM farm;"
query2 = "SELECT count(*) FROM farm f;"
edit_dist_match(query1,query2)

Normalized Edit Distance Similarity: 0.07407407407407407

0.07407407407407407

In [87]:
query1 = """SELECT lname ,  sex FROM Student WHERE StuID IN (SELECT T1.StuID FROM Plays_games AS T1 JOIN Video_games AS T2 ON T1.GameID  =  T2.GameID WHERE T2.Gname  =  "Call of Destiny" INTERSECT SELECT T1.StuID FROM Plays_games AS T1 JOIN Video_games AS T2 ON T1.GameID  =  T2.GameID WHERE T2.Gname  =  "Works of Widenius")"""
query2 = """SELECT s.LastName, s.Gender FROM Student s JOIN Plays_Games pg ON s.StuID = pg.StuID JOIN Video_Games vg ON pg.GameID = vg.GameID WHERE vg.GName = 'Call of Destiny' AND vg.GName = 'Works of Widenius' GROUP BY s.LastName, s.Gender HAVING COUNT(DISTINCT vg.GName) = 2;"""
edit_dist_match(query1,query2)

Normalized Edit Distance Similarity: 0.6252158894645942

0.6252158894645942

In [7]:
edit_dist_result = []
for index, row in df.iterrows():
    spider_query = row['spider_query']
    text2sql_query = row['text2sql_query']
    res = edit_dist_match(spider_query,text2sql_query)
    edit_dist_result.append(res)

Normalized Edit Distance Similarity: 0.6388888888888888
Normalized Edit Distance Similarity: 0.6756756756756757
Normalized Edit Distance Similarity: 0.4931506849315068
Normalized Edit Distance Similarity: 0.28125
Normalized Edit Distance Similarity: 0.3111111111111111
Normalized Edit Distance Similarity: 0.19047619047619047
Normalized Edit Distance Similarity: 0.3089430894308943
Normalized Edit Distance Similarity: 0.4122137404580153
Normalized Edit Distance Similarity: 0.44025157232704404
Normalized Edit Distance Similarity: 0.44025157232704404
Normalized Edit Distance Similarity: 0.5607476635514018
Normalized Edit Distance Similarity: 0.5607476635514018
Normalized Edit Distance Similarity: 0.16470588235294117
Normalized Edit Distance Similarity: 0.3516483516483517
Normalized Edit Distance Similarity: 0.32061068702290074
Normalized Edit Distance Similarity: 0.32061068702290074
Normalized Edit Distance Similarity: 0.13071895424836602
Normalized Edit Distance Similarity: 0.13071895424836602
Normalized Edit Distance Similarity: 0.7224334600760456
Normalized Edit Distance Similarity: 0.6639344262295082
Normalized Edit Distance Similarity: 0.7064935064935065
Normalized Edit Distance Similarity: 0.7277486910994765
Normalized Edit Distance Similarity: 0.7444168734491315
Normalized Edit Distance Similarity: 0.9544554455445544
Normalized Edit Distance Similarity: 0.6130268199233716
Normalized Edit Distance Similarity: 0.6222222222222222
Normalized Edit Distance Similarity: 0.7272727272727273
Normalized Edit Distance Similarity: 0.7272727272727273
Normalized Edit Distance Similarity: 0.5161290322580645
Normalized Edit Distance Similarity: 0.6190476190476191
Normalized Edit Distance Similarity: 0.4418604651162791
Normalized Edit Distance Similarity: 0.4418604651162791
Normalized Edit Distance Similarity: 0.576
Normalized Edit Distance Similarity: 0.10945273631840796
Normalized Edit Distance Similarity: 0.5555555555555556
Normalized Edit Distance Similarity: 0.5387755102040817
Normalized Edit Distance Similarity: 0.49746192893401014
Normalized Edit Distance Similarity: 0.49746192893401014
Normalized Edit Distance Similarity: 0.625
Normalized Edit Distance Similarity: 0.6075949367088608
Normalized Edit Distance Similarity: 0.7354838709677419
Normalized Edit Distance Similarity: 0.7354838709677419
Normalized Edit Distance Similarity: 0.6816720257234726
Normalized Edit Distance Similarity: 0.7025316455696202
Normalized Edit Distance Similarity: 0.15555555555555556
Normalized Edit Distance Similarity: 0.15555555555555556
Normalized Edit Distance Similarity: 0.40418118466898956
Normalized Edit Distance Similarity: 0.40418118466898956
Normalized Edit Distance Similarity: 0.21468926553672316
Normalized Edit Distance Similarity: 0.16129032258064516
Normalized Edit Distance Similarity: 0.8623853211009175
Normalized Edit Distance Similarity: 0.8623853211009175
Normalized Edit Distance Similarity: 0.38461538461538464
Normalized Edit Distance Similarity: 0.38461538461538464
Normalized Edit Distance Similarity: 0.6130952380952381
Normalized Edit Distance Similarity: 0.5759162303664922
Normalized Edit Distance Similarity: 0.7529411764705882
Normalized Edit Distance Similarity: 0.21761658031088082
Normalized Edit Distance Similarity: 0.36553524804177545
Normalized Edit Distance Similarity: 0.27071823204419887
Normalized Edit Distance Similarity: 0.4419889502762431
Normalized Edit Distance Similarity: 0.632258064516129
Normalized Edit Distance Similarity: 0.34782608695652173
Normalized Edit Distance Similarity: 0.24277456647398843
Normalized Edit Distance Similarity: 0.5986394557823129
Normalized Edit Distance Similarity: 0.2598870056497175
Normalized Edit Distance Similarity: 0.5769230769230769
Normalized Edit Distance Similarity: 0.1348314606741573
Normalized Edit Distance Similarity: 0.7686832740213523
Normalized Edit Distance Similarity: 0.7686832740213523
Normalized Edit Distance Similarity: 0.422680412371134
Normalized Edit Distance Similarity: 0.3
Normalized Edit Distance Similarity: 0.14507772020725387
Normalized Edit Distance Similarity: 0.14507772020725387
Normalized Edit Distance Similarity: 0.5021645021645021
Normalized Edit Distance Similarity: 0.1693121693121693
Normalized Edit Distance Similarity: 0.782608695652174
Normalized Edit Distance Similarity: 0.6412213740458015
Normalized Edit Distance Similarity: 0.39436619718309857
Normalized Edit Distance Similarity: 0.15
Normalized Edit Distance Similarity: 0.49214659685863876
Normalized Edit Distance Similarity: 0.5306122448979592
Normalized Edit Distance Similarity: 0.096
Normalized Edit Distance Similarity: 0.8983957219251337
Normalized Edit Distance Similarity: 0.7549019607843137
Normalized Edit Distance Similarity: 0.5951219512195122
Normalized Edit Distance Similarity: 0.15757575757575756
Normalized Edit Distance Similarity: 0.7330677290836654
Normalized Edit Distance Similarity: 0.526829268292683
Normalized Edit Distance Similarity: 0.5432098765432098
Normalized Edit Distance Similarity: 0.5303030303030303
Normalized Edit Distance Similarity: 0.6349206349206349
Normalized Edit Distance Similarity: 0.5299145299145299
Normalized Edit Distance Similarity: 0.8552631578947368
Normalized Edit Distance Similarity: 0.49760765550239233
Normalized Edit Distance Similarity: 0.23696682464454977
Normalized Edit Distance Similarity: 0.4100418410041841
Normalized Edit Distance Similarity: 0.5198237885462555
Normalized Edit Distance Similarity: 0.5235602094240838
Normalized Edit Distance Similarity: 0.4970414201183432
Normalized Edit Distance Similarity: 0.03508771929824561
Normalized Edit Distance Similarity: 0.03508771929824561
Normalized Edit Distance Similarity: 0.3177570093457944
Normalized Edit Distance Similarity: 0.3177570093457944
Normalized Edit Distance Similarity: 0.5174825174825175
Normalized Edit Distance Similarity: 0.5174825174825175
Normalized Edit Distance Similarity: 0.32
Normalized Edit Distance Similarity: 0.34210526315789475
Normalized Edit Distance Similarity: 0.10989010989010989
Normalized Edit Distance Similarity: 0.10989010989010989
Normalized Edit Distance Similarity: 0.15053763440860216
Normalized Edit Distance Similarity: 0.3
Normalized Edit Distance Similarity: 0.5985401459854015
Normalized Edit Distance Similarity: 0.5985401459854015
Normalized Edit Distance Similarity: 0.15384615384615385
Normalized Edit Distance Similarity: 0.2992125984251969
Normalized Edit Distance Similarity: 0.2972972972972973
Normalized Edit Distance Similarity: 0.12413793103448276
Normalized Edit Distance Similarity: 0.3448275862068966
Normalized Edit Distance Similarity: 0.35294117647058826
Normalized Edit Distance Similarity: 0.45871559633027525
Normalized Edit Distance Similarity: 0.24083769633507854
Normalized Edit Distance Similarity: 0.4444444444444444
Normalized Edit Distance Similarity: 0.17872340425531916
Normalized Edit Distance Similarity: 0.2084942084942085
Normalized Edit Distance Similarity: 0.3776223776223776
Normalized Edit Distance Similarity: 0.8068181818181818
Normalized Edit Distance Similarity: 0.2222222222222222
Normalized Edit Distance Similarity: 0.8969072164948454
Normalized Edit Distance Similarity: 0.8969072164948454
Normalized Edit Distance Similarity: 0.5683060109289617
Normalized Edit Distance Similarity: 0.8251121076233184
Normalized Edit Distance Similarity: 0.2909090909090909
Normalized Edit Distance Similarity: 0.44221105527638194
Normalized Edit Distance Similarity: 0.5232067510548524
Normalized Edit Distance Similarity: 0.5814977973568282
Normalized Edit Distance Similarity: 0.4228571428571429
Normalized Edit Distance Similarity: 0.592964824120603
Normalized Edit Distance Similarity: 0.46511627906976744
Normalized Edit Distance Similarity: 0.4827586206896552
Normalized Edit Distance Similarity: 0.11214953271028037
Normalized Edit Distance Similarity: 0.5588235294117647
Normalized Edit Distance Similarity: 0.3508771929824561
Normalized Edit Distance Similarity: 0.5454545454545454
Normalized Edit Distance Similarity: 0.43523316062176165
Normalized Edit Distance Similarity: 0.8042328042328042
Normalized Edit Distance Similarity: 0.13986013986013987
Normalized Edit Distance Similarity: 0.21897810218978103
Normalized Edit Distance Similarity: 0.7160493827160493
Normalized Edit Distance Similarity: 0.7581699346405228
Normalized Edit Distance Similarity: 0.494949494949495
Normalized Edit Distance Similarity: 0.423728813559322
Normalized Edit Distance Similarity: 0.16589861751152074
Normalized Edit Distance Similarity: 0.6274509803921569
Normalized Edit Distance Similarity: 0.5263157894736842
Normalized Edit Distance Similarity: 0.5836065573770491
Normalized Edit Distance Similarity: 0.4628099173553719
Normalized Edit Distance Similarity: 0.585480093676815
Normalized Edit Distance Similarity: 0.8770053475935828
Normalized Edit Distance Similarity: 0.14705882352941177
Normalized Edit Distance Similarity: 0.09836065573770492
Normalized Edit Distance Similarity: 0.03389830508474576
Normalized Edit Distance Similarity: 0.7272727272727273
Normalized Edit Distance Similarity: 0.6575342465753424
Normalized Edit Distance Similarity: 0.30303030303030304
Normalized Edit Distance Similarity: 0.11764705882352941
Normalized Edit Distance Similarity: 0.15384615384615385
Normalized Edit Distance Similarity: 0.27450980392156865
Normalized Edit Distance Similarity: 0.660377358490566
Normalized Edit Distance Similarity: 0.660377358490566
Normalized Edit Distance Similarity: 0.18181818181818182
Normalized Edit Distance Similarity: 0.5555555555555556
Normalized Edit Distance Similarity: 0.5511811023622047
Normalized Edit Distance Similarity: 0.5511811023622047
Normalized Edit Distance Similarity: 0.43018867924528303
Normalized Edit Distance Similarity: 0.43018867924528303
Normalized Edit Distance Similarity: 0.4620938628158845
Normalized Edit Distance Similarity: 1.0097560975609756
Normalized Edit Distance Similarity: 0.46886446886446886
Normalized Edit Distance Similarity: 0.6007326007326007
Normalized Edit Distance Similarity: 0.9381443298969072
Normalized Edit Distance Similarity: 0.9052631578947369
Normalized Edit Distance Similarity: 0.6486486486486487
Normalized Edit Distance Similarity: 0.9626556016597511
Normalized Edit Distance Similarity: 0.6486486486486487
Normalized Edit Distance Similarity: 0.6486486486486487
Normalized Edit Distance Similarity: 0.3898305084745763
Normalized Edit Distance Similarity: 0.38333333333333336
Normalized Edit Distance Similarity: 0.3473053892215569
Normalized Edit Distance Similarity: 0.3473053892215569
Normalized Edit Distance Similarity: 0.7692307692307693
Normalized Edit Distance Similarity: 0.5906735751295337
Normalized Edit Distance Similarity: 0.11764705882352941
Normalized Edit Distance Similarity: 0.11764705882352941
Normalized Edit Distance Similarity: 0.6666666666666666
Normalized Edit Distance Similarity: 0.6666666666666666
Normalized Edit Distance Similarity: 0.20408163265306123
Normalized Edit Distance Similarity: 0.20408163265306123
Normalized Edit Distance Similarity: 0.4578313253012048
Normalized Edit Distance Similarity: 0.4909090909090909
Normalized Edit Distance Similarity: 0.1774193548387097
Normalized Edit Distance Similarity: 0.112
Normalized Edit Distance Similarity: 0.5419354838709678
Normalized Edit Distance Similarity: 0.04081632653061224
Normalized Edit Distance Similarity: 0.06593406593406594
Normalized Edit Distance Similarity: 0.06593406593406594
Normalized Edit Distance Similarity: 0.1509433962264151
Normalized Edit Distance Similarity: 0.1509433962264151
Normalized Edit Distance Similarity: 0.5555555555555556
Normalized Edit Distance Similarity: 0.4594594594594595
Normalized Edit Distance Similarity: 0.18867924528301888
Normalized Edit Distance Similarity: 0.18867924528301888
Normalized Edit Distance Similarity: 0.22608695652173913
Normalized Edit Distance Similarity: 0.22608695652173913
Normalized Edit Distance Similarity: 0.4642857142857143
Normalized Edit Distance Similarity: 0.18947368421052632
Normalized Edit Distance Similarity: 0.7142857142857143
Normalized Edit Distance Similarity: 0.6218487394957983
Normalized Edit Distance Similarity: 0.33962264150943394
Normalized Edit Distance Similarity: 0.5645933014354066
Normalized Edit Distance Similarity: 0.7068273092369478
Normalized Edit Distance Similarity: 0.5106382978723404
Normalized Edit Distance Similarity: 0.6540284360189573
Normalized Edit Distance Similarity: 0.6442307692307693
Normalized Edit Distance Similarity: 0.46153846153846156
Normalized Edit Distance Similarity: 0.46153846153846156
Normalized Edit Distance Similarity: 0.44221105527638194
Normalized Edit Distance Similarity: 0.6060606060606061
Normalized Edit Distance Similarity: 0.6617100371747212
Normalized Edit Distance Similarity: 0.5
Normalized Edit Distance Similarity: 0.5735294117647058
Normalized Edit Distance Similarity: 0.5735294117647058
Normalized Edit Distance Similarity: 0.8730964467005076
Normalized Edit Distance Similarity: 0.6263345195729537
Normalized Edit Distance Similarity: 0.19642857142857142
Normalized Edit Distance Similarity: 0.9793510324483776
Normalized Edit Distance Similarity: 0.634020618556701
Normalized Edit Distance Similarity: 0.6237816764132553
Normalized Edit Distance Similarity: 0.5038167938931297
Normalized Edit Distance Similarity: 0.5943396226415094
Normalized Edit Distance Similarity: 0.46963562753036436
Normalized Edit Distance Similarity: 0.3119266055045872
Normalized Edit Distance Similarity: 0.4067796610169492
Normalized Edit Distance Similarity: 0.3333333333333333
Normalized Edit Distance Similarity: 0.32894736842105265
Normalized Edit Distance Similarity: 0.5634674922600619
Normalized Edit Distance Similarity: 0.6214689265536724
Normalized Edit Distance Similarity: 0.7174447174447175
Normalized Edit Distance Similarity: 0.7848101265822784
Normalized Edit Distance Similarity: 1.0510204081632653
Normalized Edit Distance Similarity: 0.5167173252279635
Normalized Edit Distance Similarity: 0.6306306306306306
Normalized Edit Distance Similarity: 0.6099290780141844
Normalized Edit Distance Similarity: 0.5633802816901409
Normalized Edit Distance Similarity: 0.7475409836065574
Normalized Edit Distance Similarity: 0.7272727272727273
Normalized Edit Distance Similarity: 0.30666666666666664
Normalized Edit Distance Similarity: 0.30666666666666664
Normalized Edit Distance Similarity: 0.5555555555555556
Normalized Edit Distance Similarity: 0.7068273092369478
Normalized Edit Distance Similarity: 0.7191011235955056
Normalized Edit Distance Similarity: 0.7664233576642335
Normalized Edit Distance Similarity: 0.45454545454545453
Normalized Edit Distance Similarity: 0.4850498338870432
Normalized Edit Distance Similarity: 0.8791773778920309
Normalized Edit Distance Similarity: 0.7988980716253443
Normalized Edit Distance Similarity: 0.8831168831168831
Normalized Edit Distance Similarity: 0.9197530864197531
Normalized Edit Distance Similarity: 0.664756446991404
Normalized Edit Distance Similarity: 0.6182965299684543
Normalized Edit Distance Similarity: 0.7973421926910299
Normalized Edit Distance Similarity: 0.8300653594771242
Normalized Edit Distance Similarity: 0.7878787878787878
Normalized Edit Distance Similarity: 0.7719298245614035
Normalized Edit Distance Similarity: 0.5071428571428571
Normalized Edit Distance Similarity: 0.5035460992907801
Normalized Edit Distance Similarity: 0.6507936507936508
Normalized Edit Distance Similarity: 0.5296803652968036
Normalized Edit Distance Similarity: 0.2569832402234637
Normalized Edit Distance Similarity: 0.2658959537572254
Normalized Edit Distance Similarity: 0.6253369272237197
Normalized Edit Distance Similarity: 0.8038740920096852
Normalized Edit Distance Similarity: 0.5663082437275986
Normalized Edit Distance Similarity: 0.37722419928825623
Normalized Edit Distance Similarity: 0.64
Normalized Edit Distance Similarity: 0.6331658291457286
Normalized Edit Distance Similarity: 0.5815602836879432
Normalized Edit Distance Similarity: 0.5815602836879432
Normalized Edit Distance Similarity: 0.7931034482758621
Normalized Edit Distance Similarity: 1.0666666666666667
Normalized Edit Distance Similarity: 0.8044280442804428
Normalized Edit Distance Similarity: 0.8044280442804428
Normalized Edit Distance Similarity: 0.5
Normalized Edit Distance Similarity: 0.5
Normalized Edit Distance Similarity: 0.7748344370860927
Normalized Edit Distance Similarity: 0.7238095238095238
Normalized Edit Distance Similarity: 0.8063492063492064
Normalized Edit Distance Similarity: 0.7174603174603175
Normalized Edit Distance Similarity: 0.1694915254237288
Normalized Edit Distance Similarity: 0.1694915254237288
Normalized Edit Distance Similarity: 0.6821705426356589
Normalized Edit Distance Similarity: 0.6821705426356589
Normalized Edit Distance Similarity: 0.5979381443298969
Normalized Edit Distance Similarity: 0.5979381443298969
Normalized Edit Distance Similarity: 0.5906040268456376
Normalized Edit Distance Similarity: 0.5906040268456376
Normalized Edit Distance Similarity: 0.6666666666666666
Normalized Edit Distance Similarity: 0.6666666666666666
Normalized Edit Distance Similarity: 0.21138211382113822
Normalized Edit Distance Similarity: 0.21138211382113822
Normalized Edit Distance Similarity: 0.205607476635514
Normalized Edit Distance Similarity: 0.25225225225225223
Normalized Edit Distance Similarity: 0.6721311475409836
Normalized Edit Distance Similarity: 0.6721311475409836
Normalized Edit Distance Similarity: 0.1935483870967742
Normalized Edit Distance Similarity: 0.15384615384615385
Normalized Edit Distance Similarity: 0.36363636363636365
Normalized Edit Distance Similarity: 0.36363636363636365
Normalized Edit Distance Similarity: 0.4819277108433735
Normalized Edit Distance Similarity: 0.4819277108433735
Normalized Edit Distance Similarity: 1.5274725274725274
Normalized Edit Distance Similarity: 0.9135802469135802
Normalized Edit Distance Similarity: 0.5603448275862069
Normalized Edit Distance Similarity: 0.5787234042553191
Normalized Edit Distance Similarity: 0.6715328467153284
Normalized Edit Distance Similarity: 0.6259541984732825
Normalized Edit Distance Similarity: 0.39080459770114945
Normalized Edit Distance Similarity: 0.39080459770114945
Normalized Edit Distance Similarity: 0.6981132075471698
Normalized Edit Distance Similarity: 0.6035087719298246
Normalized Edit Distance Similarity: 0.26285714285714284
Normalized Edit Distance Similarity: 0.26285714285714284
Normalized Edit Distance Similarity: 0.24630541871921183
Normalized Edit Distance Similarity: 0.36036036036036034
Normalized Edit Distance Similarity: 0.3557312252964427
Normalized Edit Distance Similarity: 0.5
Normalized Edit Distance Similarity: 0.5038167938931297
Normalized Edit Distance Similarity: 0.5038167938931297
Normalized Edit Distance Similarity: 0.7151515151515152
Normalized Edit Distance Similarity: 0.7151515151515152
Normalized Edit Distance Similarity: 0.8108108108108109
Normalized Edit Distance Similarity: 0.8108108108108109
Normalized Edit Distance Similarity: 0.3511450381679389
Normalized Edit Distance Similarity: 0.3511450381679389
Normalized Edit Distance Similarity: 0.1487603305785124
Normalized Edit Distance Similarity: 0.1487603305785124
Normalized Edit Distance Similarity: 0.3087248322147651
Normalized Edit Distance Similarity: 0.13333333333333333
Normalized Edit Distance Similarity: 0.3129251700680272
Normalized Edit Distance Similarity: 0.13533834586466165
Normalized Edit Distance Similarity: 0.7193460490463215
Normalized Edit Distance Similarity: 0.47058823529411764
Normalized Edit Distance Similarity: 0.6436781609195402
Normalized Edit Distance Similarity: 0.6436781609195402
Normalized Edit Distance Similarity: 0.43283582089552236
Normalized Edit Distance Similarity: 0.610062893081761
Normalized Edit Distance Similarity: 0.8837209302325582
Normalized Edit Distance Similarity: 0.9823321554770318
Normalized Edit Distance Similarity: 0.8518518518518519

In [8]:
len(edit_dist_result)

719

In [9]:
df['edit_distance'] = edit_dist_result

## Approach 2 : Embedding Matching

In [10]:
from sentence_transformers import SentenceTransformer, util
# Load a pre-trained model
model = SentenceTransformer('sentence-transformers/all-MiniLM-L12-v2')

C:\Users\GuPr564\AppData\Local\anaconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\GuPr564\AppData\Local\anaconda3\Lib\site-packages\torchvision\datapoints\__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
C:\Users\GuPr564\AppData\Local\anaconda3\Lib\site-packages\torchvision\transforms\v2\__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)

In [11]:
def embedding_match(query1,query2):
    query1 = query1.lower()
    query2 = query2.lower()
    # Compute embeddings
    embedding1 = model.encode(query1)
    embedding2 = model.encode(query2)
    # Compute cosine similarity
    similarity = util.cos_sim(embedding1, embedding2)
    print(f"Semantic Similarity: {similarity.item()}")
    return similarity.item()

In [94]:
query1 = "SELECT COUNT(*) FROM farm;"
query2 = """SELECT f."Farm_ID", f."Total_Horses" FROM "farm" f ORDER BY f."Total_Horses" ASC;"""
embedding_match(query1,query2)

Semantic Similarity: 0.5847867131233215

0.5847867131233215

In [95]:
# Example queries
query1 = "SELECT COUNT(*) FROM farm;"
query2 = "SELECT count(*) FROM farm f;"
embedding_match(query1,query2)

Semantic Similarity: 0.9586180448532104

0.9586180448532104

In [96]:
query1 = """SELECT lname ,  sex FROM Student WHERE StuID IN (SELECT T1.StuID FROM Plays_games AS T1 JOIN Video_games AS T2 ON T1.GameID  =  T2.GameID WHERE T2.Gname  =  "Call of Destiny" INTERSECT SELECT T1.StuID FROM Plays_games AS T1 JOIN Video_games AS T2 ON T1.GameID  =  T2.GameID WHERE T2.Gname  =  "Works of Widenius")"""
query2 = """SELECT s.LastName, s.Gender FROM Student s JOIN Plays_Games pg ON s.StuID = pg.StuID JOIN Video_Games vg ON pg.GameID = vg.GameID WHERE vg.GName = 'Call of Destiny' AND vg.GName = 'Works of Widenius' GROUP BY s.LastName, s.Gender HAVING COUNT(DISTINCT vg.GName) = 2;"""
embedding_match(query1,query2)

Semantic Similarity: 0.8142150640487671

0.8142150640487671

In [12]:
embed_result = []
i = 0
for index, row in df.iterrows():
    i = i+1
    print(i)
    spider_query = row['spider_query']
    text2sql_query = row['text2sql_query']
    res = embedding_match(spider_query,text2sql_query)
    embed_result.append(res)

1
Semantic Similarity: 0.7701829671859741
2
Semantic Similarity: 0.7547934651374817
3
Semantic Similarity: 0.8307386636734009
4
Semantic Similarity: 0.8872911930084229
5
Semantic Similarity: 0.8674377202987671
6
Semantic Similarity: 0.9067676067352295
7
Semantic Similarity: 0.8506258726119995
8
Semantic Similarity: 0.8344841003417969
9
Semantic Similarity: 0.94203782081604
10
Semantic Similarity: 0.94203782081604
11
Semantic Similarity: 0.9385462999343872
12
Semantic Similarity: 0.9385462999343872
13
Semantic Similarity: 0.9642791748046875
14
Semantic Similarity: 0.6855964660644531
15
Semantic Similarity: 0.8984886407852173
16
Semantic Similarity: 0.8984886407852173
17
Semantic Similarity: 0.9404617547988892
18
Semantic Similarity: 0.9404617547988892
19
Semantic Similarity: 0.772111713886261
20
Semantic Similarity: 0.7605451345443726
21
Semantic Similarity: 0.8252102136611938
22
Semantic Similarity: 0.8974716663360596
23
Semantic Similarity: 0.9170470237731934
24
Semantic Similarity: 0.86497962474823
25
Semantic Similarity: 0.8446882963180542
26
Semantic Similarity: 0.8417328000068665
27
Semantic Similarity: 0.8545815944671631
28
Semantic Similarity: 0.8545815944671631
29
Semantic Similarity: 0.8957412242889404
30
Semantic Similarity: 0.9158285856246948
31
Semantic Similarity: 0.9246422052383423
32
Semantic Similarity: 0.9246422052383423
33
Semantic Similarity: 0.9218884706497192
34
Semantic Similarity: 0.945542573928833
35
Semantic Similarity: 0.7542712688446045
36
Semantic Similarity: 0.8124550580978394
37
Semantic Similarity: 0.7660709619522095
38
Semantic Similarity: 0.7660709619522095
39
Semantic Similarity: 0.8183789849281311
40
Semantic Similarity: 0.8179894685745239
41
Semantic Similarity: 0.5712134838104248
42
Semantic Similarity: 0.5712134838104248
43
Semantic Similarity: 0.8030521273612976
44
Semantic Similarity: 0.7922406792640686
45
Semantic Similarity: 0.8873621225357056
46
Semantic Similarity: 0.8873621225357056
47
Semantic Similarity: 0.8681443929672241
48
Semantic Similarity: 0.8681443929672241
49
Semantic Similarity: 0.8083279728889465
50
Semantic Similarity: 0.8968223333358765
51
Semantic Similarity: 0.8621904253959656
52
Semantic Similarity: 0.8621904253959656
53
Semantic Similarity: 0.8993066549301147
54
Semantic Similarity: 0.8993066549301147
55
Semantic Similarity: 0.8853713870048523
56
Semantic Similarity: 0.9076480865478516
57
Semantic Similarity: 0.7763321995735168
58
Semantic Similarity: 0.8627986311912537
59
Semantic Similarity: 0.9101446866989136
60
Semantic Similarity: 0.9158848524093628
61
Semantic Similarity: 0.9447124600410461
62
Semantic Similarity: 0.791633129119873
63
Semantic Similarity: 0.8772873282432556
64
Semantic Similarity: 0.8959410190582275
65
Semantic Similarity: 0.518039345741272
66
Semantic Similarity: 0.8603967428207397
67
Semantic Similarity: 0.8624958992004395
68
Semantic Similarity: 0.9196767807006836
69
Semantic Similarity: 0.8327474594116211
70
Semantic Similarity: 0.8327474594116211
71
Semantic Similarity: 0.8476851582527161
72
Semantic Similarity: 0.8558342456817627
73
Semantic Similarity: 0.8972437381744385
74
Semantic Similarity: 0.8972437381744385
75
Semantic Similarity: 0.8329357504844666
76
Semantic Similarity: 0.9394265413284302
77
Semantic Similarity: 0.5101848840713501
78
Semantic Similarity: 0.8141865730285645
79
Semantic Similarity: 0.6926337480545044
80
Semantic Similarity: 0.9324177503585815
81
Semantic Similarity: 0.8162461519241333
82
Semantic Similarity: 0.802333652973175
83
Semantic Similarity: 0.9729403257369995
84
Semantic Similarity: 0.808526873588562
85
Semantic Similarity: 0.5874239802360535
86
Semantic Similarity: 0.8306021094322205
87
Semantic Similarity: 0.9327592253684998
88
Semantic Similarity: 0.8691695332527161
89
Semantic Similarity: 0.8281847834587097
90
Semantic Similarity: 0.7679585218429565
91
Semantic Similarity: 0.7277050018310547
92
Semantic Similarity: 0.8039441108703613
93
Semantic Similarity: 0.7795712351799011
94
Semantic Similarity: 0.9277873039245605
95
Semantic Similarity: 0.878645658493042
96
Semantic Similarity: 0.940847635269165
97
Semantic Similarity: 0.9699466228485107
98
Semantic Similarity: 0.9452686309814453
99
Semantic Similarity: 0.8581185340881348
100
Semantic Similarity: 0.8150111436843872
101
Semantic Similarity: 0.9862444400787354
102
Semantic Similarity: 0.9862444400787354
103
Semantic Similarity: 0.9134611487388611
104
Semantic Similarity: 0.9134611487388611
105
Semantic Similarity: 0.7954053282737732
106
Semantic Similarity: 0.7954053282737732
107
Semantic Similarity: 0.9622578024864197
108
Semantic Similarity: 0.9544300436973572
109
Semantic Similarity: 0.9552308320999146
110
Semantic Similarity: 0.9552308320999146
111
Semantic Similarity: 0.9335192441940308
112
Semantic Similarity: 0.7944154143333435
113
Semantic Similarity: 0.7646350264549255
114
Semantic Similarity: 0.7646350264549255
115
Semantic Similarity: 0.9495418071746826
116
Semantic Similarity: 0.9313329458236694
117
Semantic Similarity: 0.927330732345581
118
Semantic Similarity: 0.9551827907562256
119
Semantic Similarity: 0.9425504803657532
120
Semantic Similarity: 0.939329981803894
121
Semantic Similarity: 0.8310731649398804
122
Semantic Similarity: 0.9497982859611511
123
Semantic Similarity: 0.8470686078071594
124
Semantic Similarity: 0.958215594291687
125
Semantic Similarity: 0.9545596241950989
126
Semantic Similarity: 0.8827675580978394
127
Semantic Similarity: 0.8482087850570679
128
Semantic Similarity: 0.9521889090538025
129
Semantic Similarity: 0.8264265060424805
130
Semantic Similarity: 0.8264265060424805
131
Semantic Similarity: 0.8303112387657166
132
Semantic Similarity: 0.8347498774528503
133
Semantic Similarity: 0.9134899377822876
134
Semantic Similarity: 0.8563382625579834
135
Semantic Similarity: 0.7488322257995605
136
Semantic Similarity: 0.7647779583930969
137
Semantic Similarity: 0.9143691062927246
138
Semantic Similarity: 0.8795551061630249
139
Semantic Similarity: 0.816336989402771
140
Semantic Similarity: 0.8199553489685059
141
Semantic Similarity: 0.9738982915878296
142
Semantic Similarity: 0.7663288116455078
143
Semantic Similarity: 0.9066423773765564
144
Semantic Similarity: 0.8454219102859497
145
Semantic Similarity: 0.8012648820877075
146
Semantic Similarity: 0.841744065284729
147
Semantic Similarity: 0.9499792456626892
148
Semantic Similarity: 0.9415684938430786
149
Semantic Similarity: 0.8063924908638
150
Semantic Similarity: 0.8082427382469177
151
Semantic Similarity: 0.8433957099914551
152
Semantic Similarity: 0.9440828561782837
153
Semantic Similarity: 0.9420874118804932
154
Semantic Similarity: 0.8220029473304749
155
Semantic Similarity: 0.9253863096237183
156
Semantic Similarity: 0.9326635599136353
157
Semantic Similarity: 0.932914137840271
158
Semantic Similarity: 0.8464480638504028
159
Semantic Similarity: 0.7871333360671997
160
Semantic Similarity: 0.9741106033325195
161
Semantic Similarity: 0.9670709371566772
162
Semantic Similarity: 0.9857528209686279
163
Semantic Similarity: 0.7746408581733704
164
Semantic Similarity: 0.8087490797042847
165
Semantic Similarity: 0.9132254123687744
166
Semantic Similarity: 0.9435251951217651
167
Semantic Similarity: 0.9446736574172974
168
Semantic Similarity: 0.8904135227203369
169
Semantic Similarity: 0.7097916603088379
170
Semantic Similarity: 0.7097916603088379
171
Semantic Similarity: 0.9615762233734131
172
Semantic Similarity: 0.825715184211731
173
Semantic Similarity: 0.8298465609550476
174
Semantic Similarity: 0.8298465609550476
175
Semantic Similarity: 0.9506435990333557
176
Semantic Similarity: 0.9506435990333557
177
Semantic Similarity: 0.9240071773529053
178
Semantic Similarity: 0.8868445754051208
179
Semantic Similarity: 0.8663413524627686
180
Semantic Similarity: 0.8575847744941711
181
Semantic Similarity: 0.8170628547668457
182
Semantic Similarity: 0.8115586042404175
183
Semantic Similarity: 0.8044012784957886
184
Semantic Similarity: 0.8337709903717041
185
Semantic Similarity: 0.7812552452087402
186
Semantic Similarity: 0.7812552452087402
187
Semantic Similarity: 0.8928378820419312
188
Semantic Similarity: 0.8538659811019897
189
Semantic Similarity: 0.913860559463501
190
Semantic Similarity: 0.913860559463501
191

Semantic Similarity: 0.8422232866287231
192
Semantic Similarity: 0.8679594993591309
193
Semantic Similarity: 0.961883544921875
194
Semantic Similarity: 0.961883544921875
195
Semantic Similarity: 0.7434301376342773
196
Semantic Similarity: 0.7434301376342773
197
Semantic Similarity: 0.9531548619270325
198
Semantic Similarity: 0.9531548619270325
199
Semantic Similarity: 0.9100795984268188
200
Semantic Similarity: 0.8427411317825317
201
Semantic Similarity: 0.9221060276031494
202
Semantic Similarity: 0.9060105085372925
203
Semantic Similarity: 0.9238733053207397
204
Semantic Similarity: 0.9857629537582397
205
Semantic Similarity: 0.9923897981643677
206
Semantic Similarity: 0.9923897981643677
207
Semantic Similarity: 0.911920428276062
208
Semantic Similarity: 0.911920428276062
209
Semantic Similarity: 0.6312083005905151
210
Semantic Similarity: 0.7959184646606445
211
Semantic Similarity: 0.9056371450424194
212
Semantic Similarity: 0.9056371450424194
213
Semantic Similarity: 0.939344048500061
214
Semantic Similarity: 0.939344048500061
215
Semantic Similarity: 0.9314935207366943
216
Semantic Similarity: 0.9581800699234009
217
Semantic Similarity: 0.9322136640548706
218
Semantic Similarity: 0.9314451217651367
219
Semantic Similarity: 0.9534175992012024
220
Semantic Similarity: 0.8569716215133667
221
Semantic Similarity: 0.8892630338668823
222
Semantic Similarity: 0.9575213193893433
223
Semantic Similarity: 0.8074208498001099
224
Semantic Similarity: 0.846550464630127
225
Semantic Similarity: 0.8779212236404419
226
Semantic Similarity: 0.8779212236404419
227
Semantic Similarity: 0.9292000532150269
228
Semantic Similarity: 0.8239411115646362
229
Semantic Similarity: 0.8961681723594666
230
Semantic Similarity: 0.9479113817214966
231
Semantic Similarity: 0.7610169649124146
232
Semantic Similarity: 0.7610169649124146
233
Semantic Similarity: 0.7884403467178345
234
Semantic Similarity: 0.9048065543174744
235
Semantic Similarity: 0.9565609097480774
236
Semantic Similarity: 0.861926794052124
237
Semantic Similarity: 0.818185567855835
238
Semantic Similarity: 0.8338834643363953
239
Semantic Similarity: 0.9484085440635681
240
Semantic Similarity: 0.9496010541915894
241
Semantic Similarity: 0.9332311749458313
242
Semantic Similarity: 0.9539586305618286
243
Semantic Similarity: 0.9025722742080688
244
Semantic Similarity: 0.9302417039871216
245
Semantic Similarity: 0.9210952520370483
246
Semantic Similarity: 0.915820837020874
247
Semantic Similarity: 0.8992018699645996
248
Semantic Similarity: 0.8773114681243896
249
Semantic Similarity: 0.721066951751709
250
Semantic Similarity: 0.7007116079330444
251
Semantic Similarity: 0.9117013216018677
252
Semantic Similarity: 0.8460625410079956
253
Semantic Similarity: 0.8364241123199463
254
Semantic Similarity: 0.8286780118942261
255
Semantic Similarity: 0.7713799476623535
256
Semantic Similarity: 0.7672542333602905
257
Semantic Similarity: 0.8858397006988525
258
Semantic Similarity: 0.8858397006988525
259
Semantic Similarity: 0.9192332625389099
260
Semantic Similarity: 0.8922325372695923
261
Semantic Similarity: 0.9100677967071533
262
Semantic Similarity: 0.8729643821716309
263
Semantic Similarity: 0.9221875667572021
264
Semantic Similarity: 0.9347881078720093
265
Semantic Similarity: 0.9042898416519165
266
Semantic Similarity: 0.927177369594574
267
Semantic Similarity: 0.8848017454147339
268
Semantic Similarity: 0.882844090461731
269
Semantic Similarity: 0.9254522323608398
270
Semantic Similarity: 0.8936170339584351
271
Semantic Similarity: 0.8825673460960388
272
Semantic Similarity: 0.8608858585357666
273
Semantic Similarity: 0.6908844113349915
274
Semantic Similarity: 0.6819469332695007
275
Semantic Similarity: 0.9360864162445068
276
Semantic Similarity: 0.9075014591217041
277
Semantic Similarity: 0.8934552669525146
278
Semantic Similarity: 0.9084556102752686
279
Semantic Similarity: 0.9670175313949585
280
Semantic Similarity: 0.9650484323501587
281
Semantic Similarity: 0.9061134457588196
282
Semantic Similarity: 0.8423901796340942
283
Semantic Similarity: 0.8617908954620361
284
Semantic Similarity: 0.8818656206130981
285
Semantic Similarity: 0.9146355986595154
286
Semantic Similarity: 0.8733332753181458
287
Semantic Similarity: 0.8901484608650208
288
Semantic Similarity: 0.8901484608650208
289
Semantic Similarity: 0.8190436363220215
290
Semantic Similarity: 0.8560888767242432
291
Semantic Similarity: 0.8319046497344971
292
Semantic Similarity: 0.8319046497344971
293
Semantic Similarity: 0.974134087562561
294
Semantic Similarity: 0.974134087562561
295
Semantic Similarity: 0.8783096075057983
296
Semantic Similarity: 0.8405345678329468
297
Semantic Similarity: 0.8271991014480591
298
Semantic Similarity: 0.8370844125747681
299
Semantic Similarity: 0.9559776186943054
300
Semantic Similarity: 0.9559776186943054
301
Semantic Similarity: 0.6568371057510376
302
Semantic Similarity: 0.6568371057510376
303
Semantic Similarity: 0.8790541887283325
304
Semantic Similarity: 0.8790541887283325
305
Semantic Similarity: 0.9132344722747803
306
Semantic Similarity: 0.9132344722747803
307
Semantic Similarity: 0.788861870765686
308
Semantic Similarity: 0.788861870765686
309
Semantic Similarity: 0.9158831238746643
310
Semantic Similarity: 0.9158831238746643
311
Semantic Similarity: 0.9374408721923828
312
Semantic Similarity: 0.9198939800262451
313
Semantic Similarity: 0.7611479759216309
314
Semantic Similarity: 0.7611479759216309
315
Semantic Similarity: 0.9536362886428833
316
Semantic Similarity: 0.9640073776245117
317
Semantic Similarity: 0.8330812454223633
318
Semantic Similarity: 0.8330812454223633
319
Semantic Similarity: 0.8171764016151428
320
Semantic Similarity: 0.8171764016151428
321
Semantic Similarity: 0.63869309425354
322
Semantic Similarity: 0.7105400562286377
323
Semantic Similarity: 0.8299000263214111
324
Semantic Similarity: 0.8313103318214417
325
Semantic Similarity: 0.8545674681663513
326
Semantic Similarity: 0.8273632526397705
327
Semantic Similarity: 0.966131865978241
328
Semantic Similarity: 0.966131865978241
329
Semantic Similarity: 0.8481334447860718
330
Semantic Similarity: 0.8363714218139648
331
Semantic Similarity: 0.9509141445159912
332
Semantic Similarity: 0.9509141445159912
333
Semantic Similarity: 0.9523187279701233
334
Semantic Similarity: 0.944794774055481
335
Semantic Similarity: 0.882764458656311
336
Semantic Similarity: 0.744893491268158
337
Semantic Similarity: 0.8287346363067627
338
Semantic Similarity: 0.8287346363067627
339
Semantic Similarity: 0.8485246896743774
340
Semantic Similarity: 0.8485246896743774
341
Semantic Similarity: 0.8016704320907593
342
Semantic Similarity: 0.8016704320907593
343
Semantic Similarity: 0.8724578619003296
344
Semantic Similarity: 0.8724578619003296
345
Semantic Similarity: 0.8910355567932129
346
Semantic Similarity: 0.8910355567932129
347
Semantic Similarity: 0.9109313488006592
348
Semantic Similarity: 0.9283413887023926
349
Semantic Similarity: 0.9189011454582214
350
Semantic Similarity: 0.9306697249412537
351
Semantic Similarity: 0.8528606295585632
352
Semantic Similarity: 0.8570340871810913
353
Semantic Similarity: 0.8075224161148071
354
Semantic Similarity: 0.8075224161148071
355
Semantic Similarity: 0.8758035898208618
356
Semantic Similarity: 0.8478535413742065
357
Semantic Similarity: 0.8839330673217773
358
Semantic Similarity: 0.8404545783996582
359
Semantic Similarity: 0.7012161612510681
360
Semantic Similarity: 0.4826242923736572
361
Semantic Similarity: 0.8493399620056152
362
Semantic Similarity: 0.8493399620056152
363
Semantic Similarity: 0.7394534349441528
364
Semantic Similarity: 0.7741079330444336
365
Semantic Similarity: 0.7389501333236694
366
Semantic Similarity: 0.7623804807662964
367
Semantic Similarity: 0.9708836078643799
368
Semantic Similarity: 0.9290131330490112
369
Semantic Similarity: 0.6965697407722473
370
Semantic Similarity: 0.9236756563186646
371
Semantic Similarity: 0.9404560327529907
372
Semantic Similarity: 0.6998437643051147
373
Semantic Similarity: 0.93320631980896
374
Semantic Similarity: 0.93320631980896
375
Semantic Similarity: 0.9311350584030151
376
Semantic Similarity: 0.9311350584030151
377
Semantic Similarity: 0.9228297472000122
378

Semantic Similarity: 0.9228297472000122
379
Semantic Similarity: 0.9349486827850342
380
Semantic Similarity: 0.8809223771095276
381
Semantic Similarity: 0.9051936268806458
382
Semantic Similarity: 0.8266217708587646
383
Semantic Similarity: 0.9146302938461304
384
Semantic Similarity: 0.9212348461151123
385
Semantic Similarity: 0.932000994682312
386
Semantic Similarity: 0.932000994682312
387
Semantic Similarity: 0.9578737020492554
388
Semantic Similarity: 0.9578737020492554
389
Semantic Similarity: 0.9901930093765259
390
Semantic Similarity: 0.9901930093765259
391
Semantic Similarity: 0.9550637006759644
392
Semantic Similarity: 0.9550637006759644
393
Semantic Similarity: 0.8801776766777039
394
Semantic Similarity: 0.8801776766777039
395
Semantic Similarity: 0.7110204696655273
396
Semantic Similarity: 0.7110204696655273
397
Semantic Similarity: 0.6115026473999023
398
Semantic Similarity: 0.5975775122642517
399
Semantic Similarity: 0.7678027749061584
400
Semantic Similarity: 0.7678027749061584
401
Semantic Similarity: 0.8523507118225098
402
Semantic Similarity: 0.8523507118225098
403
Semantic Similarity: 0.8830775022506714
404
Semantic Similarity: 0.8871842622756958
405
Semantic Similarity: 0.9677022099494934
406
Semantic Similarity: 0.8927066326141357
407
Semantic Similarity: 0.8905806541442871
408
Semantic Similarity: 0.8905806541442871
409
Semantic Similarity: 0.8672971725463867
410
Semantic Similarity: 0.8564159870147705
411
Semantic Similarity: 0.9072792530059814
412
Semantic Similarity: 0.9072792530059814
413
Semantic Similarity: 0.747573971748352
414
Semantic Similarity: 0.9214159846305847
415
Semantic Similarity: 0.9044835567474365
416
Semantic Similarity: 0.9155977964401245
417
Semantic Similarity: 0.8566895723342896
418
Semantic Similarity: 0.8566895723342896
419
Semantic Similarity: 0.844409167766571
420
Semantic Similarity: 0.8460562229156494
421
Semantic Similarity: 0.8112155795097351
422
Semantic Similarity: 0.9088701605796814
423
Semantic Similarity: 0.7506471872329712
424
Semantic Similarity: 0.8357888460159302
425
Semantic Similarity: 0.8844261765480042
426
Semantic Similarity: 0.8844261765480042
427
Semantic Similarity: 0.9576276540756226
428
Semantic Similarity: 0.9460469484329224
429
Semantic Similarity: 0.9477447271347046
430
Semantic Similarity: 0.9477447271347046
431
Semantic Similarity: 0.826911985874176
432
Semantic Similarity: 0.8812717795372009
433
Semantic Similarity: 0.7967367768287659
434
Semantic Similarity: 0.8041192293167114
435
Semantic Similarity: 0.9356486797332764
436
Semantic Similarity: 0.9300578236579895
437
Semantic Similarity: 0.9691110849380493
438
Semantic Similarity: 0.9702589511871338
439
Semantic Similarity: 0.8567626476287842
440
Semantic Similarity: 0.8567626476287842
441
Semantic Similarity: 0.9578315019607544
442
Semantic Similarity: 0.9556341171264648
443
Semantic Similarity: 0.8978331089019775
444
Semantic Similarity: 0.9065873622894287
445
Semantic Similarity: 0.8547719120979309
446
Semantic Similarity: 0.8547719120979309
447
Semantic Similarity: 0.8825968503952026
448
Semantic Similarity: 0.856304407119751
449
Semantic Similarity: 0.912527322769165
450
Semantic Similarity: 0.9065735340118408
451
Semantic Similarity: 0.9590964317321777
452
Semantic Similarity: 0.9590964317321777
453
Semantic Similarity: 0.8667445182800293
454
Semantic Similarity: 0.8667445182800293
455
Semantic Similarity: 0.876255989074707
456
Semantic Similarity: 0.876255989074707
457
Semantic Similarity: 0.9522696137428284
458
Semantic Similarity: 0.9565197229385376
459
Semantic Similarity: 0.9425995349884033
460
Semantic Similarity: 0.9196747541427612
461
Semantic Similarity: 0.8166639804840088
462
Semantic Similarity: 0.8166639804840088
463
Semantic Similarity: 0.8957587480545044
464
Semantic Similarity: 0.9248205423355103
465
Semantic Similarity: 0.8988770246505737
466
Semantic Similarity: 0.8484706878662109
467
Semantic Similarity: 0.7240678071975708
468
Semantic Similarity: 0.7072082757949829
469
Semantic Similarity: 0.9065663814544678
470
Semantic Similarity: 0.9065663814544678
471
Semantic Similarity: 0.8805273771286011
472
Semantic Similarity: 0.8788081407546997
473
Semantic Similarity: 0.8118324279785156
474
Semantic Similarity: 0.792328417301178
475
Semantic Similarity: 0.9374387264251709
476
Semantic Similarity: 0.9513295888900757
477
Semantic Similarity: 0.9324506521224976
478
Semantic Similarity: 0.9324446320533752
479
Semantic Similarity: 0.9228793978691101
480
Semantic Similarity: 0.9228793978691101
481
Semantic Similarity: 0.7535969018936157
482
Semantic Similarity: 0.7535969018936157
483
Semantic Similarity: 0.8628000020980835
484
Semantic Similarity: 0.8628000020980835
485
Semantic Similarity: 0.6351799964904785
486
Semantic Similarity: 0.8797214031219482
487
Semantic Similarity: 0.9624916315078735
488
Semantic Similarity: 0.9624916315078735
489
Semantic Similarity: 0.8100547790527344
490
Semantic Similarity: 0.8100547790527344
491
Semantic Similarity: 0.8712931871414185
492
Semantic Similarity: 0.9113131761550903
493
Semantic Similarity: 0.9146553874015808
494
Semantic Similarity: 0.8606011867523193
495
Semantic Similarity: 0.9874556064605713
496
Semantic Similarity: 0.9874556064605713
497
Semantic Similarity: 0.7700521945953369
498
Semantic Similarity: 0.7700521945953369
499
Semantic Similarity: 0.9210419654846191
500
Semantic Similarity: 0.8890920281410217
501
Semantic Similarity: 0.734175980091095
502
Semantic Similarity: 0.7015901207923889
503
Semantic Similarity: 0.807318925857544
504
Semantic Similarity: 0.807318925857544
505
Semantic Similarity: 0.9457257986068726
506
Semantic Similarity: 0.9467635154724121
507
Semantic Similarity: 0.9728845953941345
508
Semantic Similarity: 0.9728845953941345
509
Semantic Similarity: 0.9256014823913574
510
Semantic Similarity: 0.6985770463943481
511
Semantic Similarity: 0.8993398547172546
512
Semantic Similarity: 0.8993398547172546
513
Semantic Similarity: 0.8329646587371826
514
Semantic Similarity: 0.9539119601249695
515
Semantic Similarity: 0.9654202461242676
516
Semantic Similarity: 0.9115828275680542
517
Semantic Similarity: 0.9701083898544312
518
Semantic Similarity: 0.9701083898544312
519
Semantic Similarity: 0.9306027889251709
520
Semantic Similarity: 0.8347334861755371
521
Semantic Similarity: 0.9032853841781616
522
Semantic Similarity: 0.9032853841781616
523
Semantic Similarity: 0.847781777381897
524
Semantic Similarity: 0.8249841928482056
525
Semantic Similarity: 0.8528057336807251
526
Semantic Similarity: 0.8773901462554932
527
Semantic Similarity: 0.8646718859672546
528
Semantic Similarity: 0.8739711046218872
529
Semantic Similarity: 0.9489310383796692
530
Semantic Similarity: 0.9489310383796692
531
Semantic Similarity: 0.8588849306106567
532
Semantic Similarity: 0.7287565469741821
533
Semantic Similarity: 0.9094406962394714
534
Semantic Similarity: 0.9094406962394714
535
Semantic Similarity: 0.7940329313278198
536
Semantic Similarity: 0.7823749780654907
537
Semantic Similarity: 0.8695891499519348
538
Semantic Similarity: 0.8695891499519348
539
Semantic Similarity: 0.8824988603591919
540
Semantic Similarity: 0.9146809577941895
541
Semantic Similarity: 0.7382082343101501
542
Semantic Similarity: 0.9023101329803467
543
Semantic Similarity: 0.9424052834510803
544
Semantic Similarity: 0.9424052834510803
545
Semantic Similarity: 0.9035810232162476
546
Semantic Similarity: 0.6941063404083252
547
Semantic Similarity: 0.8203862905502319
548
Semantic Similarity: 0.8119221925735474
549
Semantic Similarity: 0.9141254425048828
550
Semantic Similarity: 0.9141254425048828
551
Semantic Similarity: 0.9111456871032715
552
Semantic Similarity: 0.9111456871032715
553
Semantic Similarity: 0.9451030492782593
554
Semantic Similarity: 0.9451030492782593
555
Semantic Similarity: 0.9582890868186951
556
Semantic Similarity: 0.9582890868186951
557
Semantic Similarity: 0.9555630683898926
558
Semantic Similarity: 0.9555630683898926
559
Semantic Similarity: 0.9317692518234253
560
Semantic Similarity: 0.9501245617866516
561
Semantic Similarity: 0.9252221584320068
562
Semantic Similarity: 0.9252221584320068
563
Semantic Similarity: 0.8706910014152527
564
Semantic Similarity: 0.8677187561988831
565

Semantic Similarity: 0.8516708612442017
566
Semantic Similarity: 0.8516708612442017
567
Semantic Similarity: 0.9003729224205017
568
Semantic Similarity: 0.8166956901550293
569
Semantic Similarity: 0.8526628017425537
570
Semantic Similarity: 0.8640333414077759
571
Semantic Similarity: 0.8786101937294006
572
Semantic Similarity: 0.817780613899231
573
Semantic Similarity: 0.9214351177215576
574
Semantic Similarity: 0.9214351177215576
575
Semantic Similarity: 0.7787696123123169
576
Semantic Similarity: 0.8480383157730103
577
Semantic Similarity: 0.7917274236679077
578
Semantic Similarity: 0.765002965927124
579
Semantic Similarity: 0.9164180755615234
580
Semantic Similarity: 0.9707498550415039
581
Semantic Similarity: 0.8716698884963989
582
Semantic Similarity: 0.8807005882263184
583
Semantic Similarity: 0.982806921005249
584
Semantic Similarity: 0.8263787031173706
585
Semantic Similarity: 0.9484239220619202
586
Semantic Similarity: 0.9737815260887146
587
Semantic Similarity: 0.8705424666404724
588
Semantic Similarity: 0.8588013648986816
589
Semantic Similarity: 0.8815664052963257
590
Semantic Similarity: 0.8626518249511719
591
Semantic Similarity: 0.8731759786605835
592
Semantic Similarity: 0.8536287546157837
593
Semantic Similarity: 0.8091899156570435
594
Semantic Similarity: 0.7290489673614502
595
Semantic Similarity: 0.9615431427955627
596
Semantic Similarity: 0.9240826368331909
597
Semantic Similarity: 0.9791632890701294
598
Semantic Similarity: 0.8963786363601685
599
Semantic Similarity: 0.9493335485458374
600
Semantic Similarity: 0.9575424790382385
601
Semantic Similarity: 0.9700027704238892
602
Semantic Similarity: 0.9536997079849243
603
Semantic Similarity: 0.957277774810791
604
Semantic Similarity: 0.9611936807632446
605
Semantic Similarity: 0.9152005910873413
606
Semantic Similarity: 0.9407341480255127
607
Semantic Similarity: 0.8659567832946777
608
Semantic Similarity: 0.852637767791748
609
Semantic Similarity: 0.8897915482521057
610
Semantic Similarity: 0.9266387224197388
611
Semantic Similarity: 0.6237461566925049
612
Semantic Similarity: 0.93170166015625
613
Semantic Similarity: 0.7754712104797363
614
Semantic Similarity: 0.9036962389945984
615
Semantic Similarity: 0.790032684803009
616
Semantic Similarity: 0.9521179795265198
617
Semantic Similarity: 0.8750962615013123
618
Semantic Similarity: 0.8819248080253601
619
Semantic Similarity: 0.7567204236984253
620
Semantic Similarity: 0.821503221988678
621
Semantic Similarity: 0.9411648511886597
622
Semantic Similarity: 0.8323568105697632
623
Semantic Similarity: 0.9121690988540649
624
Semantic Similarity: 0.952418863773346
625
Semantic Similarity: 0.8129000663757324
626
Semantic Similarity: 0.9110291004180908
627
Semantic Similarity: 0.8530428409576416
628
Semantic Similarity: 0.8271872997283936
629
Semantic Similarity: 0.9601783752441406
630
Semantic Similarity: 0.8332914710044861
631
Semantic Similarity: 0.764100193977356
632
Semantic Similarity: 0.8902423977851868
633
Semantic Similarity: 0.7911008596420288
634
Semantic Similarity: 0.9608557224273682
635
Semantic Similarity: 0.9608557224273682
636
Semantic Similarity: 0.9852492809295654
637
Semantic Similarity: 0.9419410228729248
638
Semantic Similarity: 0.8073872327804565
639
Semantic Similarity: 0.8244156837463379
640
Semantic Similarity: 0.8852865695953369
641
Semantic Similarity: 0.8852865695953369
642
Semantic Similarity: 0.926360547542572
643
Semantic Similarity: 0.932500422000885
644
Semantic Similarity: 0.9334712028503418
645
Semantic Similarity: 0.9334712028503418
646
Semantic Similarity: 0.9652723073959351
647
Semantic Similarity: 0.9652723073959351
648
Semantic Similarity: 0.8413304090499878
649
Semantic Similarity: 0.863721489906311
650
Semantic Similarity: 0.9146060943603516
651
Semantic Similarity: 0.9146060943603516
652
Semantic Similarity: 0.8821761608123779
653
Semantic Similarity: 0.8017466068267822
654
Semantic Similarity: 0.945823073387146
655
Semantic Similarity: 0.945823073387146
656
Semantic Similarity: 0.7704668045043945
657
Semantic Similarity: 0.7704668045043945
658
Semantic Similarity: 0.9471494555473328
659
Semantic Similarity: 0.9471494555473328
660
Semantic Similarity: 0.899495005607605
661
Semantic Similarity: 0.9034390449523926
662
Semantic Similarity: 0.8493925333023071
663
Semantic Similarity: 0.31212398409843445
664
Semantic Similarity: 0.9636966586112976
665
Semantic Similarity: 0.9636966586112976
666
Semantic Similarity: 0.9502086639404297
667
Semantic Similarity: 0.9522743225097656
668
Semantic Similarity: 0.720348060131073
669
Semantic Similarity: 0.7572410106658936
670
Semantic Similarity: 0.8133326768875122
671
Semantic Similarity: 0.8133326768875122
672
Semantic Similarity: 0.8462092876434326
673
Semantic Similarity: 0.7106536626815796
674
Semantic Similarity: 0.943458080291748
675
Semantic Similarity: 0.943458080291748
676
Semantic Similarity: 0.7854578495025635
677
Semantic Similarity: 0.7752273082733154
678
Semantic Similarity: 0.8420149683952332
679
Semantic Similarity: 0.7320444583892822
680
Semantic Similarity: 0.8839882612228394
681
Semantic Similarity: 0.8471064567565918
682
Semantic Similarity: 0.9326353073120117
683
Semantic Similarity: 0.9130697250366211
684
Semantic Similarity: 0.901038646697998
685
Semantic Similarity: 0.9115329384803772
686
Semantic Similarity: 0.8431569933891296
687
Semantic Similarity: 0.8431569933891296
688
Semantic Similarity: 0.7851060628890991
689
Semantic Similarity: 0.7851060628890991
690
Semantic Similarity: 0.7542849779129028
691
Semantic Similarity: 0.7542849779129028
692
Semantic Similarity: 0.7651041746139526
693
Semantic Similarity: 0.7342091202735901
694
Semantic Similarity: 0.7404664754867554
695
Semantic Similarity: 0.843963623046875
696
Semantic Similarity: 0.7829132080078125
697
Semantic Similarity: 0.9530971050262451
698
Semantic Similarity: 0.9610595107078552
699
Semantic Similarity: 0.9394354224205017
700
Semantic Similarity: 0.8517488837242126
701
Semantic Similarity: 0.7765103578567505
702
Semantic Similarity: 0.8124455213546753
703
Semantic Similarity: 0.8124455213546753
704
Semantic Similarity: 0.833017885684967
705
Semantic Similarity: 0.8349787592887878
706
Semantic Similarity: 0.8376328349113464
707
Semantic Similarity: 0.6991065144538879
708
Semantic Similarity: 0.9631140232086182
709
Semantic Similarity: 0.9603126049041748
710
Semantic Similarity: 0.8022910356521606
711
Semantic Similarity: 0.9052194356918335
712
Semantic Similarity: 0.9003764390945435
713
Semantic Similarity: 0.9194165468215942
714
Semantic Similarity: 0.8397420048713684
715
Semantic Similarity: 0.8804835081100464
716
Semantic Similarity: 0.7923176288604736
717
Semantic Similarity: 0.7923176288604736
718
Semantic Similarity: 0.7989025115966797
719
Semantic Similarity: 0.7507411241531372

In [13]:
len(embed_result)

719

In [14]:
df['embedding_match'] = embed_result

## Approach 3 : Fuzzy Matching

In [30]:
#!pip install rapidfuzz

In [15]:
from rapidfuzz import fuzz, process

def fuzzy_match(query1,query2):
    query1 = query1.lower()
    query2 = query2.lower()
    # Compute fuzzy match score
    similarity_score = fuzz.ratio(query1, query2)
    print(f"Fuzzy Similarity Score: {similarity_score}%")
    return similarity_score

In [15]:
# Example queries
query1 = "SELECT COUNT(*) FROM farm WHERE Total_Horses > 10;"
query2 = "SELECT count(*) FROM farm WHERE Total_Horses > 10;"
fuzzy_match(query1,query2)

Fuzzy Similarity Score: 100.0%

100.0

In [102]:
query1 = "SELECT Total_Horses FROM farm ORDER BY Total_Horses ASC"
query2 = """SELECT f."Farm_ID", f."Total_Horses" FROM "farm" f ORDER BY f."Total_Horses" ASC;"""
fuzzy_match(query1,query2)

Fuzzy Similarity Score: 80.88235294117648%

80.88235294117648

In [16]:
fuzzy_result = []
i = 0
for index, row in df.iterrows():
    i = i+1
    spider_query = row['spider_query']
    text2sql_query = row['text2sql_query']
    print(i)
    res = fuzzy_match(spider_query,text2sql_query)
    fuzzy_result.append(res)

1
Fuzzy Similarity Score: 66.66666666666667%
2
Fuzzy Similarity Score: 64.86486486486487%
3
Fuzzy Similarity Score: 75.34246575342466%
4
Fuzzy Similarity Score: 85.9375%
5
Fuzzy Similarity Score: 84.44444444444444%
6
Fuzzy Similarity Score: 90.47619047619048%
7
Fuzzy Similarity Score: 84.55284552845528%
8
Fuzzy Similarity Score: 79.38931297709924%
9
Fuzzy Similarity Score: 77.9874213836478%
10
Fuzzy Similarity Score: 77.9874213836478%
11
Fuzzy Similarity Score: 71.02803738317758%
12
Fuzzy Similarity Score: 71.02803738317758%
13
Fuzzy Similarity Score: 91.76470588235294%
14
Fuzzy Similarity Score: 79.12087912087912%
15
Fuzzy Similarity Score: 83.96946564885496%
16
Fuzzy Similarity Score: 83.96946564885496%
17
Fuzzy Similarity Score: 92.81045751633987%
18
Fuzzy Similarity Score: 92.81045751633987%
19
Fuzzy Similarity Score: 53.99239543726235%
20
Fuzzy Similarity Score: 58.19672131147541%
21
Fuzzy Similarity Score: 58.18181818181818%
22
Fuzzy Similarity Score: 56.544502617801044%
23
Fuzzy Similarity Score: 53.59801488833747%
24
Fuzzy Similarity Score: 45.94059405940594%
25
Fuzzy Similarity Score: 65.90038314176245%
26
Fuzzy Similarity Score: 64.44444444444444%
27
Fuzzy Similarity Score: 63.63636363636363%
28
Fuzzy Similarity Score: 63.63636363636363%
29
Fuzzy Similarity Score: 73.54838709677419%
30
Fuzzy Similarity Score: 69.04761904761905%
31
Fuzzy Similarity Score: 77.90697674418605%
32
Fuzzy Similarity Score: 77.90697674418605%
33
Fuzzy Similarity Score: 66.39999999999999%
34
Fuzzy Similarity Score: 94.5273631840796%
35
Fuzzy Similarity Score: 62.03703703703704%
36
Fuzzy Similarity Score: 62.857142857142854%
37
Fuzzy Similarity Score: 75.1269035532995%
38
Fuzzy Similarity Score: 75.1269035532995%
39
Fuzzy Similarity Score: 67.5%
40
Fuzzy Similarity Score: 68.35443037974683%
41
Fuzzy Similarity Score: 61.935483870967744%
42
Fuzzy Similarity Score: 61.935483870967744%
43
Fuzzy Similarity Score: 64.95176848874597%
44
Fuzzy Similarity Score: 63.9240506329114%
45
Fuzzy Similarity Score: 91.11111111111111%
46
Fuzzy Similarity Score: 91.11111111111111%
47
Fuzzy Similarity Score: 79.44250871080139%
48
Fuzzy Similarity Score: 79.44250871080139%
49
Fuzzy Similarity Score: 87.00564971751412%
50
Fuzzy Similarity Score: 90.32258064516128%
51
Fuzzy Similarity Score: 55.04587155963303%
52
Fuzzy Similarity Score: 55.04587155963303%
53
Fuzzy Similarity Score: 78.02197802197803%
54
Fuzzy Similarity Score: 78.02197802197803%
55
Fuzzy Similarity Score: 59.226190476190474%
56
Fuzzy Similarity Score: 66.66666666666667%
57
Fuzzy Similarity Score: 59.6078431372549%
58
Fuzzy Similarity Score: 89.11917098445596%
59
Fuzzy Similarity Score: 77.28459530026109%
60
Fuzzy Similarity Score: 81.76795580110497%
61
Fuzzy Similarity Score: 77.34806629834254%
62
Fuzzy Similarity Score: 56.774193548387096%
63
Fuzzy Similarity Score: 82.6086956521739%
64
Fuzzy Similarity Score: 87.86127167630057%
65
Fuzzy Similarity Score: 61.224489795918366%
66
Fuzzy Similarity Score: 87.00564971751412%
67
Fuzzy Similarity Score: 65.38461538461539%
68
Fuzzy Similarity Score: 92.13483146067416%
69
Fuzzy Similarity Score: 59.07473309608541%
70
Fuzzy Similarity Score: 59.07473309608541%
71
Fuzzy Similarity Score: 76.28865979381443%
72
Fuzzy Similarity Score: 82.22222222222221%
73
Fuzzy Similarity Score: 89.11917098445596%
74
Fuzzy Similarity Score: 89.11917098445596%
75
Fuzzy Similarity Score: 74.45887445887446%
76
Fuzzy Similarity Score: 91.005291005291%
77
Fuzzy Similarity Score: 48.69565217391304%
78
Fuzzy Similarity Score: 65.64885496183206%
79
Fuzzy Similarity Score: 70.4225352112676%
80
Fuzzy Similarity Score: 92.5%
81
Fuzzy Similarity Score: 74.3455497382199%
82
Fuzzy Similarity Score: 72.44897959183673%
83
Fuzzy Similarity Score: 94.39999999999999%
84
Fuzzy Similarity Score: 52.406417112299465%
85
Fuzzy Similarity Score: 55.88235294117647%
86
Fuzzy Similarity Score: 67.3170731707317%
87
Fuzzy Similarity Score: 90.9090909090909%
88
Fuzzy Similarity Score: 62.15139442231076%
89
Fuzzy Similarity Score: 61.46341463414634%
90
Fuzzy Similarity Score: 61.728395061728406%
91
Fuzzy Similarity Score: 63.63636363636363%
92
Fuzzy Similarity Score: 62.433862433862444%
93
Fuzzy Similarity Score: 73.50427350427351%
94
Fuzzy Similarity Score: 52.63157894736843%
95
Fuzzy Similarity Score: 73.6842105263158%
96
Fuzzy Similarity Score: 87.20379146919431%
97
Fuzzy Similarity Score: 73.64016736401673%
98
Fuzzy Similarity Score: 71.36563876651982%
99
Fuzzy Similarity Score: 72.25130890052355%
100
Fuzzy Similarity Score: 73.37278106508876%
101
Fuzzy Similarity Score: 98.24561403508771%
102
Fuzzy Similarity Score: 98.24561403508771%
103
Fuzzy Similarity Score: 84.11214953271028%
104
Fuzzy Similarity Score: 84.11214953271028%
105
Fuzzy Similarity Score: 72.72727272727273%
106
Fuzzy Similarity Score: 72.72727272727273%
107
Fuzzy Similarity Score: 82.66666666666667%
108
Fuzzy Similarity Score: 81.57894736842105%
109
Fuzzy Similarity Score: 94.5054945054945%
110
Fuzzy Similarity Score: 94.5054945054945%
111
Fuzzy Similarity Score: 92.47311827956989%
112
Fuzzy Similarity Score: 84.0%
113
Fuzzy Similarity Score: 70.07299270072993%
114
Fuzzy Similarity Score: 70.07299270072993%
115
Fuzzy Similarity Score: 92.3076923076923%
116
Fuzzy Similarity Score: 85.03937007874016%
117
Fuzzy Similarity Score: 79.72972972972973%
118
Fuzzy Similarity Score: 93.79310344827586%
119
Fuzzy Similarity Score: 78.81773399014779%
120
Fuzzy Similarity Score: 78.43137254901961%
121
Fuzzy Similarity Score: 74.31192660550458%
122
Fuzzy Similarity Score: 84.81675392670157%
123
Fuzzy Similarity Score: 71.26436781609196%
124
Fuzzy Similarity Score: 88.51063829787233%
125
Fuzzy Similarity Score: 85.71428571428572%
126
Fuzzy Similarity Score: 77.62237762237763%
127
Fuzzy Similarity Score: 56.81818181818181%
128
Fuzzy Similarity Score: 85.33333333333333%
129
Fuzzy Similarity Score: 54.639175257731964%
130
Fuzzy Similarity Score: 54.639175257731964%
131
Fuzzy Similarity Score: 69.94535519125684%
132
Fuzzy Similarity Score: 57.399103139013455%
133
Fuzzy Similarity Score: 81.21212121212122%
134
Fuzzy Similarity Score: 76.38190954773869%
135
Fuzzy Similarity Score: 60.75949367088608%
136
Fuzzy Similarity Score: 58.14977973568283%
137
Fuzzy Similarity Score: 78.85714285714286%
138
Fuzzy Similarity Score: 69.34673366834171%
139
Fuzzy Similarity Score: 76.74418604651163%
140
Fuzzy Similarity Score: 75.86206896551724%
141
Fuzzy Similarity Score: 93.45794392523365%
142
Fuzzy Similarity Score: 70.58823529411764%
143
Fuzzy Similarity Score: 82.45614035087719%
144
Fuzzy Similarity Score: 71.65775401069519%
145
Fuzzy Similarity Score: 77.720207253886%
146
Fuzzy Similarity Score: 59.25925925925925%
147
Fuzzy Similarity Score: 92.3076923076923%
148
Fuzzy Similarity Score: 87.59124087591242%
149
Fuzzy Similarity Score: 58.0246913580247%
150
Fuzzy Similarity Score: 57.51633986928104%
151
Fuzzy Similarity Score: 74.74747474747474%
152
Fuzzy Similarity Score: 74.01129943502825%
153
Fuzzy Similarity Score: 91.24423963133641%
154
Fuzzy Similarity Score: 59.6078431372549%
155
Fuzzy Similarity Score: 68.0701754385965%
156
Fuzzy Similarity Score: 61.63934426229508%
157
Fuzzy Similarity Score: 76.03305785123968%
158
Fuzzy Similarity Score: 56.20608899297424%
159
Fuzzy Similarity Score: 55.61497326203209%
160
Fuzzy Similarity Score: 92.64705882352942%
161
Fuzzy Similarity Score: 95.08196721311475%
162
Fuzzy Similarity Score: 98.30508474576271%
163
Fuzzy Similarity Score: 63.63636363636363%
164
Fuzzy Similarity Score: 67.12328767123287%
165
Fuzzy Similarity Score: 84.84848484848484%
166
Fuzzy Similarity Score: 94.11764705882352%
167
Fuzzy Similarity Score: 90.9090909090909%
168
Fuzzy Similarity Score: 83.66013071895425%
169
Fuzzy Similarity Score: 66.03773584905662%
170
Fuzzy Similarity Score: 66.03773584905662%
171
Fuzzy Similarity Score: 89.5104895104895%
172
Fuzzy Similarity Score: 71.11111111111111%
173
Fuzzy Similarity Score: 64.56692913385827%
174
Fuzzy Similarity Score: 64.56692913385827%
175
Fuzzy Similarity Score: 70.9433962264151%
176
Fuzzy Similarity Score: 70.9433962264151%
177
Fuzzy Similarity Score: 69.31407942238268%
178
Fuzzy Similarity Score: 42.926829268292686%
179
Fuzzy Similarity Score: 73.26007326007327%
180
Fuzzy Similarity Score: 63.003663003663%
181
Fuzzy Similarity Score: 52.57731958762887%
182
Fuzzy Similarity Score: 53.68421052631579%
183
Fuzzy Similarity Score: 65.94594594594594%
184
Fuzzy Similarity Score: 50.62240663900415%
185
Fuzzy Similarity Score: 66.66666666666667%
186
Fuzzy Similarity Score: 66.66666666666667%
187
Fuzzy Similarity Score: 79.66101694915254%
188
Fuzzy Similarity Score: 80.0%
189
Fuzzy Similarity Score: 82.63473053892216%
190
Fuzzy Similarity Score: 82.63473053892216%
191
Fuzzy Similarity Score: 60.63348416289593%
192
Fuzzy Similarity Score: 69.43005181347151%
193
Fuzzy Similarity Score: 94.11764705882352%
194
Fuzzy Similarity Score: 94.11764705882352%
195
Fuzzy Similarity Score: 56.58914728682171%
196
Fuzzy Similarity Score: 56.58914728682171%
197
Fuzzy Similarity Score: 89.79591836734694%
198
Fuzzy Similarity Score: 89.79591836734694%
199
Fuzzy Similarity Score: 72.28915662650603%
200
Fuzzy Similarity Score: 70.9090909090909%
201
Fuzzy Similarity Score: 88.70967741935483%
202
Fuzzy Similarity Score: 94.39999999999999%
203
Fuzzy Similarity Score: 72.25806451612904%
204
Fuzzy Similarity Score: 97.95918367346938%
205
Fuzzy Similarity Score: 96.7032967032967%
206
Fuzzy Similarity Score: 96.7032967032967%
207
Fuzzy Similarity Score: 92.45283018867924%
208
Fuzzy Similarity Score: 92.45283018867924%
209
Fuzzy Similarity Score: 63.888888888888886%
210
Fuzzy Similarity Score: 75.67567567567568%
211
Fuzzy Similarity Score: 88.67924528301887%
212
Fuzzy Similarity Score: 88.67924528301887%
213
Fuzzy Similarity Score: 86.95652173913044%
214
Fuzzy Similarity Score: 86.95652173913044%
215
Fuzzy Similarity Score: 76.78571428571428%
216
Fuzzy Similarity Score: 90.52631578947368%
217
Fuzzy Similarity Score: 60.31746031746032%
218
Fuzzy Similarity Score: 65.54621848739495%
219
Fuzzy Similarity Score: 79.24528301886792%
220
Fuzzy Similarity Score: 63.1578947368421%
221
Fuzzy Similarity Score: 54.61847389558233%
222
Fuzzy Similarity Score: 70.63829787234043%
223
Fuzzy Similarity Score: 54.02843601895735%
224
Fuzzy Similarity Score: 50.96153846153846%
225
Fuzzy Similarity Score: 76.92307692307692%
226
Fuzzy Similarity Score: 76.92307692307692%
227
Fuzzy Similarity Score: 67.33668341708542%
228
Fuzzy Similarity Score: 59.5959595959596%
229
Fuzzy Similarity Score: 55.01858736059479%
230
Fuzzy Similarity Score: 66.66666666666667%
231
Fuzzy Similarity Score: 57.35294117647059%
232
Fuzzy Similarity Score: 57.35294117647059%
233
Fuzzy Similarity Score: 50.76142131979695%
234
Fuzzy Similarity Score: 59.07473309608541%
235
Fuzzy Similarity Score: 89.28571428571429%
236
Fuzzy Similarity Score: 44.83775811209439%
237
Fuzzy Similarity Score: 58.24742268041236%
238
Fuzzy Similarity Score: 60.81871345029239%
239
Fuzzy Similarity Score: 67.68447837150127%
240
Fuzzy Similarity Score: 63.20754716981132%
241
Fuzzy Similarity Score: 71.25506072874495%
242
Fuzzy Similarity Score: 78.89908256880733%
243
Fuzzy Similarity Score: 71.1864406779661%
244
Fuzzy Similarity Score: 76.0%
245
Fuzzy Similarity Score: 76.31578947368422%
246
Fuzzy Similarity Score: 64.39628482972137%
247
Fuzzy Similarity Score: 58.192090395480236%
248
Fuzzy Similarity Score: 54.054054054054056%
249
Fuzzy Similarity Score: 53.16455696202531%
250
Fuzzy Similarity Score: 41.83673469387755%
251
Fuzzy Similarity Score: 66.8693009118541%
252
Fuzzy Similarity Score: 60.66066066066066%
253
Fuzzy Similarity Score: 59.57446808510638%
254
Fuzzy Similarity Score: 61.26760563380282%
255
Fuzzy Similarity Score: 51.80327868852459%
256
Fuzzy Similarity Score: 52.52525252525253%
257
Fuzzy Similarity Score: 84.0%
258
Fuzzy Similarity Score: 84.0%
259
Fuzzy Similarity Score: 64.64646464646464%
260
Fuzzy Similarity Score: 60.24096385542168%
261
Fuzzy Similarity Score: 58.42696629213483%
262
Fuzzy Similarity Score: 54.74452554744526%
263
Fuzzy Similarity Score: 67.83216783216784%
264
Fuzzy Similarity Score: 69.10299003322258%
265
Fuzzy Similarity Score: 49.3573264781491%
266
Fuzzy Similarity Score: 53.443526170798904%
267
Fuzzy Similarity Score: 45.45454545454546%
268
Fuzzy Similarity Score: 43.82716049382716%
269
Fuzzy Similarity Score: 58.45272206303724%
270
Fuzzy Similarity Score: 54.25867507886435%
271
Fuzzy Similarity Score: 49.83388704318937%
272
Fuzzy Similarity Score: 49.01960784313726%
273
Fuzzy Similarity Score: 48.484848484848484%
274
Fuzzy Similarity Score: 51.2280701754386%
275
Fuzzy Similarity Score: 67.85714285714286%
276
Fuzzy Similarity Score: 70.92198581560284%
277
Fuzzy Similarity Score: 62.698412698412696%
278
Fuzzy Similarity Score: 66.66666666666667%
279
Fuzzy Similarity Score: 82.68156424581005%
280
Fuzzy Similarity Score: 83.23699421965318%
281
Fuzzy Similarity Score: 62.53369272237197%
282
Fuzzy Similarity Score: 48.42615012106537%
283
Fuzzy Similarity Score: 67.38351254480285%
284
Fuzzy Similarity Score: 74.73309608540926%
285
Fuzzy Similarity Score: 67.0%
286
Fuzzy Similarity Score: 66.33165829145729%
287
Fuzzy Similarity Score: 56.73758865248226%
288
Fuzzy Similarity Score: 56.73758865248226%
289
Fuzzy Similarity Score: 55.172413793103445%
290
Fuzzy Similarity Score: 46.060606060606055%
291
Fuzzy Similarity Score: 50.92250922509225%
292
Fuzzy Similarity Score: 50.92250922509225%
293
Fuzzy Similarity Score: 72.97297297297297%
294
Fuzzy Similarity Score: 72.97297297297297%
295
Fuzzy Similarity Score: 54.3046357615894%
296
Fuzzy Similarity Score: 55.87301587301587%
297
Fuzzy Similarity Score: 49.523809523809526%
298
Fuzzy Similarity Score: 52.6984126984127%
299
Fuzzy Similarity Score: 91.52542372881356%
300
Fuzzy Similarity Score: 91.52542372881356%
301
Fuzzy Similarity Score: 65.11627906976744%
302
Fuzzy Similarity Score: 65.11627906976744%
303
Fuzzy Similarity Score: 70.10309278350515%
304
Fuzzy Similarity Score: 70.10309278350515%
305
Fuzzy Similarity Score: 69.79865771812081%
306
Fuzzy Similarity Score: 69.79865771812081%
307
Fuzzy Similarity Score: 66.66666666666667%
308
Fuzzy Similarity Score: 66.66666666666667%
309
Fuzzy Similarity Score: 87.8048780487805%
310
Fuzzy Similarity Score: 87.8048780487805%
311
Fuzzy Similarity Score: 89.7196261682243%
312
Fuzzy Similarity Score: 86.48648648648648%
313
Fuzzy Similarity Score: 65.57377049180329%
314
Fuzzy Similarity Score: 65.57377049180329%
315
Fuzzy Similarity Score: 90.32258064516128%
316
Fuzzy Similarity Score: 92.3076923076923%
317
Fuzzy Similarity Score: 80.21390374331551%
318
Fuzzy Similarity Score: 80.21390374331551%
319
Fuzzy Similarity Score: 74.69879518072288%
320
Fuzzy Similarity Score: 74.69879518072288%
321
Fuzzy Similarity Score: 23.076923076923073%
322
Fuzzy Similarity Score: 54.32098765432099%
323
Fuzzy Similarity Score: 62.06896551724138%
324
Fuzzy Similarity Score: 60.42553191489362%
325
Fuzzy Similarity Score: 60.58394160583942%
326
Fuzzy Similarity Score: 61.06870229007634%
327
Fuzzy Similarity Score: 72.79693486590037%
328
Fuzzy Similarity Score: 72.79693486590037%
329
Fuzzy Similarity Score: 57.861635220125784%
330
Fuzzy Similarity Score: 63.1578947368421%
331
Fuzzy Similarity Score: 83.42857142857143%
332
Fuzzy Similarity Score: 83.42857142857143%
333
Fuzzy Similarity Score: 83.74384236453201%
334
Fuzzy Similarity Score: 77.47747747747748%
335
Fuzzy Similarity Score: 74.30830039525691%
336
Fuzzy Similarity Score: 64.92537313432835%
337
Fuzzy Similarity Score: 70.99236641221374%
338
Fuzzy Similarity Score: 70.99236641221374%
339
Fuzzy Similarity Score: 61.212121212121204%
340
Fuzzy Similarity Score: 61.212121212121204%
341
Fuzzy Similarity Score: 51.35135135135135%
342
Fuzzy Similarity Score: 51.35135135135135%
343
Fuzzy Similarity Score: 82.44274809160305%
344
Fuzzy Similarity Score: 82.44274809160305%
345
Fuzzy Similarity Score: 92.56198347107438%
346
Fuzzy Similarity Score: 92.56198347107438%
347
Fuzzy Similarity Score: 84.56375838926175%
348
Fuzzy Similarity Score: 93.33333333333333%
349
Fuzzy Similarity Score: 84.35374149659864%
350
Fuzzy Similarity Score: 93.23308270676691%
351
Fuzzy Similarity Score: 60.49046321525886%
352
Fuzzy Similarity Score: 72.54901960784314%
353
Fuzzy Similarity Score: 66.66666666666667%
354
Fuzzy Similarity Score: 66.66666666666667%
355
Fuzzy Similarity Score: 70.1492537313433%
356
Fuzzy Similarity Score: 64.77987421383648%
357
Fuzzy Similarity Score: 55.81395348837209%
358
Fuzzy Similarity Score: 50.883392226148416%
359
Fuzzy Similarity Score: 50.370370370370374%
360
Fuzzy Similarity Score: 48.582995951417004%
361
Fuzzy Similarity Score: 74.37185929648241%
362
Fuzzy Similarity Score: 74.37185929648241%
363
Fuzzy Similarity Score: 56.723716381418086%
364
Fuzzy Similarity Score: 59.375%
365
Fuzzy Similarity Score: 56.05381165919283%
366
Fuzzy Similarity Score: 49.06666666666667%
367
Fuzzy Similarity Score: 94.33962264150944%
368
Fuzzy Similarity Score: 90.9090909090909%
369
Fuzzy Similarity Score: 55.88235294117647%
370
Fuzzy Similarity Score: 74.0%
371
Fuzzy Similarity Score: 81.4814814814815%
372
Fuzzy Similarity Score: 58.03108808290156%
373
Fuzzy Similarity Score: 78.37837837837837%
374
Fuzzy Similarity Score: 78.37837837837837%
375
Fuzzy Similarity Score: 72.54901960784314%
376
Fuzzy Similarity Score: 72.54901960784314%
377
Fuzzy Similarity Score: 87.3015873015873%
378
Fuzzy Similarity Score: 87.3015873015873%
379
Fuzzy Similarity Score: 89.52380952380953%
380
Fuzzy Similarity Score: 85.45454545454545%
381
Fuzzy Similarity Score: 81.03448275862068%
382
Fuzzy Similarity Score: 76.42276422764228%
383
Fuzzy Similarity Score: 62.745098039215684%
384
Fuzzy Similarity Score: 64.86486486486487%
385
Fuzzy Similarity Score: 89.44099378881988%
386
Fuzzy Similarity Score: 89.44099378881988%
387
Fuzzy Similarity Score: 91.35802469135803%
388
Fuzzy Similarity Score: 91.35802469135803%
389
Fuzzy Similarity Score: 98.7012987012987%
390
Fuzzy Similarity Score: 98.7012987012987%
391
Fuzzy Similarity Score: 94.73684210526316%
392
Fuzzy Similarity Score: 94.73684210526316%
393
Fuzzy Similarity Score: 91.66666666666666%
394
Fuzzy Similarity Score: 91.66666666666666%
395
Fuzzy Similarity Score: 69.8224852071006%
396
Fuzzy Similarity Score: 69.8224852071006%
397
Fuzzy Similarity Score: 63.670411985018724%
398
Fuzzy Similarity Score: 61.66666666666667%
399
Fuzzy Similarity Score: 67.53246753246754%
400
Fuzzy Similarity Score: 67.53246753246754%
401
Fuzzy Similarity Score: 67.62589928057554%
402
Fuzzy Similarity Score: 67.62589928057554%
403
Fuzzy Similarity Score: 70.92198581560284%
404
Fuzzy Similarity Score: 71.94244604316546%
405
Fuzzy Similarity Score: 95.33678756476685%
406
Fuzzy Similarity Score: 81.77777777777777%
407
Fuzzy Similarity Score: 85.71428571428572%
408
Fuzzy Similarity Score: 85.71428571428572%
409
Fuzzy Similarity Score: 84.50704225352112%
410
Fuzzy Similarity Score: 75.9493670886076%
411
Fuzzy Similarity Score: 86.5979381443299%
412
Fuzzy Similarity Score: 86.5979381443299%
413
Fuzzy Similarity Score: 51.66666666666666%
414
Fuzzy Similarity Score: 66.66666666666667%
415
Fuzzy Similarity Score: 69.26829268292683%
416
Fuzzy Similarity Score: 68.59903381642512%
417
Fuzzy Similarity Score: 68.08510638297872%
418
Fuzzy Similarity Score: 68.08510638297872%
419
Fuzzy Similarity Score: 70.9090909090909%
420
Fuzzy Similarity Score: 67.53246753246754%
421
Fuzzy Similarity Score: 55.793991416309005%
422
Fuzzy Similarity Score: 60.4982206405694%
423
Fuzzy Similarity Score: 58.44748858447488%
424
Fuzzy Similarity Score: 48.12834224598931%
425
Fuzzy Similarity Score: 70.81712062256808%
426
Fuzzy Similarity Score: 70.81712062256808%
427
Fuzzy Similarity Score: 72.0%
428
Fuzzy Similarity Score: 69.76744186046511%
429
Fuzzy Similarity Score: 65.03340757238307%
430
Fuzzy Similarity Score: 65.03340757238307%
431
Fuzzy Similarity Score: 52.991452991452995%
432

In [17]:
len(fuzzy_result)

719

In [18]:
df['fuzzy_match'] = fuzzy_result

In [19]:
df.head()

,db_id,spider_query,question,text2sql_query,edit_distance,embedding_match,fuzzy_match
0,farm,SELECT count(*) FROM farm,How many farms are there?,"SELECT COUNT(DISTINCT f.Farm_ID) FROM ""farm"" f;",0.638889,0.770183,66.666667
1,farm,SELECT count(*) FROM farm,Count the number of farms.,"SELECT COUNT(DISTINCT f.""Farm_ID"") FROM ""farm"" f;",0.675676,0.754793,64.864865
2,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,List the total number of horses on farms in as...,"SELECT f.""Farm_ID"", f.""Year"", f.""Total_Horses""...",0.493151,0.830739,75.342466
3,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,"What is the total horses record for each farm,...","SELECT f.Farm_ID, f.Total_Horses FROM farm f O...",0.281250,0.887291,85.937500
4,farm,SELECT Hosts FROM farm_competition WHERE Theme...,What are the hosts of competitions whose theme...,SELECT DISTINCT fc.Hosts FROM farm_competition...,0.311111,0.867438,84.444444

In [20]:
import pandas as pd

# Save the DataFrame to an Excel file
########################################################################
######### CHANGE OUTPUT FOLDER HERE ####################################
########################################################################
file_path = r"C:\Research-Paper\PAPER-WORK-2024\Outputs\Spider-Data-7-SQL-Similarity-Scores.xlsx"
df.to_excel(file_path, index=False)

print(f"DataFrame saved successfully to {file_path}")

DataFrame saved successfully to C:\Research-Paper\PAPER-WORK-2024\Outputs\Spider-Data-7-SQL-Similarity-Scores.xlsx

## Calculating Score Accuracy

In [46]:
#############################################################################
######### CHANGE OUTPUT FOLDER FILE HERE ####################################
#############################################################################
file_path = r"C:\Research-Paper\PAPER-WORK-2024\Outputs\Spider-Data-7-SQL-Similarity-Scores.xlsx"

# Read the Excel file into a DataFrame
score_df = pd.read_excel(file_path)

# Display the first few rows of the DataFrame
score_df.head()

,db_id,spider_query,question,text2sql_query,edit_distance,embedding_match,fuzzy_match
0,farm,SELECT count(*) FROM farm,How many farms are there?,"SELECT COUNT(DISTINCT f.Farm_ID) FROM ""farm"" f;",0.638889,0.770183,66.666667
1,farm,SELECT count(*) FROM farm,Count the number of farms.,"SELECT COUNT(DISTINCT f.""Farm_ID"") FROM ""farm"" f;",0.675676,0.754793,64.864865
2,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,List the total number of horses on farms in as...,"SELECT f.""Farm_ID"", f.""Year"", f.""Total_Horses""...",0.493151,0.830739,75.342466
3,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,"What is the total horses record for each farm,...","SELECT f.Farm_ID, f.Total_Horses FROM farm f O...",0.281250,0.887291,85.937500
4,farm,SELECT Hosts FROM farm_competition WHERE Theme...,What are the hosts of competitions whose theme...,SELECT DISTINCT fc.Hosts FROM farm_competition...,0.311111,0.867438,84.444444

In [47]:
edit_distance_threshold = 0.5 # if edit dist <= threshold its Match or true
embedding_match_threshold = 0.85 # if embed similairty >= thresh its a match
fuzzy_match_threshold = 75 # if fuzzy score >= thresh its a match

# Total number of elements in the column
total_elements = len(score_df['edit_distance'])

In [23]:
percentage_edit_distance = ((score_df['edit_distance'] <= edit_distance_threshold).sum() / total_elements) * 100
print(f"percentage_edit_distance: {percentage_edit_distance:.2f}%")

percentage_edit_distance: 47.29%

In [24]:
percentage_embedding_match = ((score_df['embedding_match'] >= embedding_match_threshold).sum() / total_elements) * 100
print(f"percentage_embedding_match: {percentage_embedding_match:.2f}%")

percentage_embedding_match: 64.12%

In [48]:
percentage_fuzzy_match = ((score_df['fuzzy_match'] >= fuzzy_match_threshold).sum() / total_elements) * 100
print(f"percentage_fuzzy_match: {percentage_fuzzy_match:.2f}%")

percentage_fuzzy_match: 39.08%

# ---------------------------Rough work-------------------------------
# ---------------------------Rough work-------------------------------
# ---------------------------Rough work-------------------------------
# ---------------------------Rough work-------------------------------
# ---------------------------Rough work-------------------------------

## Aproach 3 : SQL Execution

Use SQL execution to check if the two queries produce identical results on the same database.

Steps:
Execute both spider_query and text2sql_query on the target database.

Compare their outputs (e.g., row count, result set content).

This approach ensures logical correctness, but it requires a populated database.

In [50]:
"""
import sqlite3

# Example database setup
connection = sqlite3.connect(':memory:')  # In-memory database for testing
cursor = connection.cursor()
cursor.execute("CREATE TABLE farm (Total_Horses INTEGER);")
cursor.execute("INSERT INTO farm (Total_Horses) VALUES (5), (15), (20);")

# Queries
query1 = "SELECT COUNT(*) FROM farm WHERE Total_Horses > 10;"
query2 = "SELECT count(*) FROM farm WHERE Total_Horses > 10;"

def execute_query(query):
    cursor.execute(query)
    return cursor.fetchall()

# Execute and compare results
result1 = execute_query(query1)
result2 = execute_query(query2)

if result1 == result2:
    print("The queries are semantically equivalent.")
else:
    print("The queries produce different results.")
"""

'\nimport sqlite3\n\n# Example database setup\nconnection = sqlite3.connect(\':memory:\')  # In-memory database for testing\ncursor = connection.cursor()\ncursor.execute("CREATE TABLE farm (Total_Horses INTEGER);")\ncursor.execute("INSERT INTO farm (Total_Horses) VALUES (5), (15), (20);")\n\n# Queries\nquery1 = "SELECT COUNT(*) FROM farm WHERE Total_Horses > 10;"\nquery2 = "SELECT count(*) FROM farm WHERE Total_Horses > 10;"\n\ndef execute_query(query):\n    cursor.execute(query)\n    return cursor.fetchall()\n\n# Execute and compare results\nresult1 = execute_query(query1)\nresult2 = execute_query(query2)\n\nif result1 == result2:\n    print("The queries are semantically equivalent.")\nelse:\n    print("The queries produce different results.")\n'

In [ ]:
import sqlparse
import sqlite3
from typing import List

def normalize_query(query: str) -> str:
    """
    Normalize the SQL query by formatting it consistently to enable comparison.
    """
    parsed = sqlparse.format(query, keyword_case="upper", reindent=True, strip_comments=True)
    return parsed

def execute_query(query: str, db_connection: sqlite3.Connection) -> List[tuple]:
    """
    Execute the given SQL query on the database and fetch results.
    """
    cursor = db_connection.cursor()
    try:
        cursor.execute(query)
        return cursor.fetchall()
    except sqlite3.Error as e:
        print(f"Error executing query: {e}")
        return []

def are_queries_equivalent(query1: str, query2: str, db_connection: sqlite3.Connection) -> bool:
    """
    Check if two SQL queries produce the same results on the same database.
    """
    # Normalize the queries
    normalized_query1 = normalize_query(query1)
    normalized_query2 = normalize_query(query2)
    
    # Check if normalized queries are identical
    if normalized_query1 == normalized_query2:
        return True
    
    # Otherwise, compare their outputs
    result1 = execute_query(query1, db_connection)
    result2 = execute_query(query2, db_connection)
    
    return result1 == result2

    
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

In [21]:
import sqlparse
sqlparse.format("""select f."Farm_ID", f."Total_Horses" FROM "farm" where name='Prakhar' f Order BY f."Total_Horses" ASC;""", keyword_case="upper", reindent=True, strip_comments=True)

'SELECT f."Farm_ID",\n       f."Total_Horses"\nFROM "farm"\nWHERE name=\'Prakhar\' f\nORDER BY f."Total_Horses" ASC;'

In [ ]:
query1 = "SELECT Total_Horses FROM farm ORDER BY Total_Horses ASC"
query2 = """SELECT f."Farm_ID", f."Total_Horses" FROM "farm" f ORDER BY f."Total_Horses" ASC;"""
are_same = are_queries_equivalent(query1, query2, conn)

In [ ]:
conn.close()

### Approach 4: Exact Match

In [73]:
def exact_match(query1,query2):
    if query1.strip().lower() == query2.strip().lower():
        return True
    return False

In [41]:
# Example queries
query1 = "SELECT COUNT(*) FROM farm WHERE Total_Horses > 10;"
query2 = "SELECT count(*) FROM farm WHERE Total_Horses > 10;"
exact_match(query1,query2)

True

In [42]:
query1 = "SELECT Total_Horses FROM farm ORDER BY Total_Horses ASC"
query2 = """SELECT f."Farm_ID", f."Total_Horses" FROM "farm" f ORDER BY f."Total_Horses" ASC;"""
exact_match(query1,query2)

False

In [74]:
exact_result = []
i = 0
for index, row in df.iterrows():
    i = i+1
    spider_query = row['spider_query']
    text2sql_query = row['text2sql_query']
    print(i)
    res = exact_match(spider_query,text2sql_query)
    exact_result.append(res)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719

In [75]:
calculate_accuracy(exact_result)

0.0

### Approach 5: Normalized Match

NOT IMPLEMENTED

In [76]:
import re

def normalized_match(query1, query2):
    """
    Compare two SQL queries after normalizing them.
    
    Steps:
    1. Convert queries to lowercase.
    2. Remove semicolons (;), periods (.), and quotes (' or ").
    3. Compare the resulting strings.
    
    Args:
        query1 (str): The first SQL query.
        query2 (str): The second SQL query.
    
    Returns:
        bool: True if the normalized queries are equal, False otherwise.
    """
    def normalize(query):
        # Remove comments
        query = re.sub(r'(--.*?$)|(/\*.*?\*/)', '', query, flags=re.MULTILINE)
        # Convert to lowercase
        query = query.lower()
        # Remove semicolons, periods, and quotes
        query = re.sub(r"[;.'\"]", "", query)
        # Normalize whitespace
        query = re.sub(r'\s+', ' ', query).strip()
        return query
    
    normq1 = normalize(query1)
    normq2 = normalize(query2)
    print(normq1)
    print(normq2)
    return normq1 == normq2

# Example usage
query_a = "SELECT * FROM table_name WHERE column='value';"
query_b = "select * from table_name where column='value'"

# Example usage
query_a = "SELECT * FROM table_name WHERE column='value';"
query_b = "/*comment*/  select * FROM table_name where column='value'"
print(normalized_match(query_a, query_b))  # Output: True

select * from table_name where column=value
select * from table_name where column=value
True

In [77]:
normal_result = []
i = 0
for index, row in df.iterrows():
    i = i+1
    spider_query = row['spider_query']
    text2sql_query = row['text2sql_query']
    print(i)
    res = normalized_match(spider_query,text2sql_query)
    normal_result.append(res)

1
select count(*) from farm
select count(*) from farm f
2
select count(*) from farm
select count(*) from farm
3
select total_horses from farm order by total_horses asc
select ffarm_id, ftotal_horses from farm f order by ftotal_horses asc
4
select total_horses from farm order by total_horses asc
select ffarm_id, ftotal_horses from farm f order by ftotal_horses asc
5
select hosts from farm_competition where theme != aliens
select distinct fchosts from farm_competition fc where fctheme!= aliens
6
select hosts from farm_competition where theme != aliens
select fchosts from farm_competition fc where fctheme!= aliens
7
select theme from farm_competition order by year asc
select fcyear, fctheme from farm_competition fc order by fcyear asc
8
select theme from farm_competition order by year asc
select fcyear, fctheme from farm_competition fc order by fcyear asc
9
select avg(working_horses) from farm where total_horses > 5000
select avg(fworking_horses) as average_working_horses from farm f where ftotal_horses > 5000
10
select avg(working_horses) from farm where total_horses > 5000
select avg(fworking_horses) as average_working_horses from farm f where ftotal_horses > 5000
11
select max(cows) , min(cows) from farm
select max(fcows) as max_cows, min(fcows) as min_cows from farm f
12
select max(cows) , min(cows) from farm
select max(fcows) as max_cows, min(fcows) as min_cows from farm f
13
select count(distinct status) from city
select count(distinct cstatus) from city c
14
select count(distinct status) from city
select count(distinct status) from settlements
15
select official_name from city order by population desc
select cofficial_name, cpopulation from city c order by cpopulation desc
16
select official_name from city order by population desc
select cofficial_name, cpopulation from city c order by cpopulation desc
17
select official_name , status from city order by population desc limit 1
select cofficial_name, cstatus from city c order by cpopulation desc limit 1
18
select official_name , status from city order by population desc limit 1
select cofficial_name, cstatus from city c order by cpopulation desc limit 1
19
select t2year , t1official_name from city as t1 join farm_competition as t2 on t1city_id = t2host_city_id
select fcyear, scity as host_city from farm_competition fc join stadium s on fchost_city_id = sid order by fcyear nulls last
20
select t2year , t1official_name from city as t1 join farm_competition as t2 on t1city_id = t2host_city_id
select fcyear, ccity as official_city_name from farm_competition fc join city c on fchost_city_id = ccity_id order by fcyear nulls last
21
select t1official_name from city as t1 join farm_competition as t2 on t1city_id = t2host_city_id group by t2host_city_id having count(*) > 1
select cofficial_name from city c join farm_competition fc on ccity_id = fchost_city_id group by cofficial_name having count(fccompetition_id) > 1 order by cofficial_name nulls last
22
select t1official_name from city as t1 join farm_competition as t2 on t1city_id = t2host_city_id group by t2host_city_id having count(*) > 1
select cofficial_name from city c join farm_competition fc on ccity_id = fchost_city_id group by cofficial_name having count(fccompetition_id) > 1 order by cofficial_name nulls last
23
select t1status from city as t1 join farm_competition as t2 on t1city_id = t2host_city_id group by t2host_city_id order by count(*) desc limit 1
with hostedcompetitioncounts as (select ccity_id, count(fcompetition_id) as numcompetitions from city c join farm_competition f on ccity_id = fhost_city_id group by ccity_id) select cstatus from hostedcompetitioncounts h join city c on hcity_id = ccity_id order by hnumcompetitions desc limit 1
24
select t1status from city as t1 join farm_competition as t2 on t1city_id = t2host_city_id group by t2host_city_id order by count(*) desc limit 1
with city_competition_count as (select fchost_city_id, count(fccompetition_id) as num_competitions from farm_competition fc group by fchost_city_id) select scity, sstatus from city_competition_count ccc join stadium s on ccchost_city_id = sid order by cccnum_competitions desc nulls last limit 1
25
select t2theme from city as t1 join farm_competition as t2 on t1city_id = t2host_city_id where t1population > 1000
select fctheme from farm_competition fc join city c on fchost_city_id = ccity_id where cpopulation > 1000 order by fctheme nulls last
26
select t2theme from city as t1 join farm_competition as t2 on t1city_id = t2host_city_id where t1population > 1000
select fctheme from farm_competition fc join city c on fchost_city_id = ccity_id where cpopulation > 1000 order by fctheme nulls last
27
select status , avg(population) from city group by status
select cstatus, avg(cpopulation) as average_population from city c group by cstatus order by cstatus nulls last
28
select status , avg(population) from city group by status
select cstatus, avg(cpopulation) as average_population from city c group by cstatus order by cstatus nulls last
29
select status from city group by status order by count(*) asc
select cstatus, count(cstatus) as count from city c group by cstatus order by count desc
30
select status from city group by status order by count(*) asc
select cstatus, count(cstatus) as status_count from city c group by cstatus order by status_count asc
31
select status from city group by status order by count(*) desc limit 1
select cstatus as status, count(cstatus) as count from city c group by cstatus order by count desc nulls last limit 1
32
select status from city group by status order by count(*) desc limit 1
select cstatus, count(cstatus) as count from city c group by cstatus order by count desc limit 1
33
select official_name from city where city_id not in (select host_city_id from farm_competition)
select cofficial_name from city c where ccity_id not in (select fhost_city_id from farm_competition f)
34
select official_name from city where city_id not in (select host_city_id from farm_competition)
select ccity from city c where ccity not in (select fhosts from farm_competition f)
35
select status from city where population > 1500 intersect select status from city where population < 500
select cstatus from city c where cpopulation > 1500 and cpopulation < 500 order by cstatus nulls last
36
select status from city where population > 1500 intersect select status from city where population < 500
select cstatus from city c where cpopulation > 1500 and cpopulation < 500 group by cstatus having count(distinct cpopulation) = 2
37
select official_name from city where population > 1500 or population < 500
select cofficial_name from city c where cpopulation > 1500 or cpopulation < 500
38
select official_name from city where population > 1500 or population < 500
select cofficial_name from city c where cpopulation > 1500 or cpopulation < 500
39
select census_ranking from city where status != village
select ccensus_ranking from city c where cstatus!= village order by ccensus_ranking nulls last
40
select census_ranking from city where status != village
select ccensus_ranking from city c where cstatus not ilike %village%
41
select distinct(catalog_entry_name) from catalog_contents
select cccatalog_entry_name from catalog_contents cc
42
select distinct(catalog_entry_name) from catalog_contents
select cccatalog_entry_name from catalog_contents cc
43
select attribute_data_type from attribute_definitions group by attribute_data_type having count(*) > 3
select adattribute_data_type, count(adattribute_id) as count from attribute_definitions ad group by adattribute_data_type having count(adattribute_id) > 3 order by count(adattribute_id) desc nulls last
44
select attribute_data_type from attribute_definitions group by attribute_data_type having count(*) > 3
select adattribute_data_type, count(adattribute_id) as attribute_count from attribute_definitions ad group by adattribute_data_type having count(adattribute_id) > 3 order by adattribute_data_type nulls last
45
select attribute_data_type from attribute_definitions where attribute_name = green
select adattribute_data_type from attribute_definitions ad where adattribute_name = green
46
select attribute_data_type from attribute_definitions where attribute_name = green
select adattribute_data_type from attribute_definitions ad where adattribute_name = green
47
select catalog_level_name , catalog_level_number from catalog_structure where catalog_level_number between 5 and 10
select cscatalog_level_name, cscatalog_level_number from catalog_structure cs where cscatalog_level_number between 5 and 10 order by cscatalog_level_number nulls last
48
select catalog_level_name , catalog_level_number from catalog_structure where catalog_level_number between 5 and 10
select cscatalog_level_name, cscatalog_level_number from catalog_structure cs where cscatalog_level_number between 5 and 10 order by cscatalog_level_number nulls last
49
select distinct(catalog_publisher) from catalogs where catalog_publisher like %murray%
select ccatalog_publisher from catalogs c where ccatalog_publisher like %murray%
50
select distinct(catalog_publisher) from catalogs where catalog_publisher like %murray%
select ccatalog_publisher from catalogs c where ccatalog_publisher like %murray% order by ccatalog_publisher nulls last
51
select catalog_publisher from catalogs group by catalog_publisher order by count(*) desc limit 1
select ccatalog_publisher, count(ccatalog_id) as total_catalogs from catalogs c group by ccatalog_publisher order by total_catalogs desc nulls last limit 1
52
select catalog_publisher from catalogs group by catalog_publisher order by count(*) desc limit 1
select ccatalog_publisher, count(ccatalog_id) as catalog_count from catalogs c group by ccatalog_publisher order by catalog_count desc nulls last limit 1
53
select t1catalog_name , t1date_of_publication from catalogs as t1 join catalog_structure as t2 on t1catalog_id = t2catalog_id where catalog_level_number > 5
select ccatalog_name, cdate_of_publication from catalogs c join catalog_structure cs on ccatalog_id = cscatalog_id where cscatalog_level_number > 5
54
select t1catalog_name , t1date_of_publication from catalogs as t1 join catalog_structure as t2 on t1catalog_id = t2catalog_id where catalog_level_number > 5
select ccatalog_name, cdate_of_publication from catalogs c join catalog_structure cs on ccatalog_id = cscatalog_id where cscatalog_level_number > 5
55
select t1catalog_entry_name from catalog_contents as t1 join catalog_contents_additional_attributes as t2 on t1catalog_entry_id = t2catalog_entry_id where t2attribute_value = (select attribute_value from catalog_contents_additional_attributes group by attribute_value order by count(*) desc limit 1)
select cccatalog_entry_id, ccatalog_name, count(caacatalog_entry_id) as attribute_count from catalog_contents cc join catalogs c on cccatalog_id = ccatalog_id join catalog_contents_additional_attributes caa on cccatalog_entry_id = caacatalog_entry_id group by cccatalog_entry_id, ccatalog_name order by attribute_count desc nulls last limit 1
56
select t1catalog_entry_name from catalog_contents as t1 join catalog_contents_additional_attributes as t2 on t1catalog_entry_id = t2catalog_entry_id where t2attribute_value = (select attribute_value from catalog_contents_additional_attributes group by attribute_value order by count(*) desc limit 1)
select cccatalog_entry_name, count(caacatalog_entry_id) as attribute_count from catalog_contents cc join catalog_contents_additional_attributes caa on cccatalog_entry_id = caacatalog_entry_id group by cccatalog_entry_name order by attribute_count desc nulls last limit 1
57
select catalog_entry_name from catalog_contents order by price_in_dollars desc limit 1
select cccatalog_entry_name, max(ccprice_in_dollars) as max_price from catalog_contents cc group by cccatalog_entry_name order by max_price desc nulls last limit 1
58
select catalog_entry_name from catalog_contents order by price_in_dollars desc limit 1
select cccatalog_entry_name, ccprice_in_dollars from catalog_contents cc order by ccprice_in_dollars desc nulls last limit 1
59
select t2catalog_level_name from catalog_contents as t1 join catalog_structure as t2 on t1catalog_level_number = t2catalog_level_number order by t1price_in_dollars limit 1
select cscatalog_level_name, ccprice_in_dollars from catalog_contents cc join catalog_structure cs on cccatalog_level_number = cscatalog_level_number order by ccprice_in_dollars asc nulls last limit 1
60
select t2catalog_level_name from catalog_contents as t1 join catalog_structure as t2 on t1catalog_level_number = t2catalog_level_number order by t1price_in_dollars limit 1
select cscatalog_level_name, ccprice_in_dollars from catalog_contents cc join catalog_structure cs on cccatalog_level_number = cscatalog_level_number order by ccprice_in_dollars asc nulls last limit 1
61
select avg(price_in_euros) , min(price_in_euros) from catalog_contents
select avg(pprice) as average_price, min(pprice) as minimum_price from products p
62
select avg(price_in_euros) , min(price_in_euros) from catalog_contents
select avg(cprice_in_euros) as average_price_in_euros, min(cprice_in_euros) as minimum_price_in_euros from products p join catalog_contents c on pcode = cproduct_stock_number
63
select catalog_entry_name from catalog_contents order by height desc limit 1
select cccatalog_entry_name from catalog_contents cc order by ccheight desc nulls last limit 1
64
select catalog_entry_name from catalog_contents order by height desc limit 1
select cccatalog_entry_name from catalog_contents cc order by ccheight desc nulls last limit 1
65
select catalog_entry_name from catalog_contents order by capacity asc limit 1
select pname, ccapacity from products p join catalog_contents c on pcode = cproduct_stock_number order by ccapacity asc nulls last limit 1
66
select catalog_entry_name from catalog_contents order by capacity asc limit 1
select cccatalog_entry_name from catalog_contents cc where cccapacity = (select min(capacity) from catalog_contents)
67
select catalog_entry_name from catalog_contents where product_stock_number like 2%
select pname from products p join catalog_contents cc on pcode = cccatalog_entry_id where ccproduct_stock_number like 2%
68
select catalog_entry_name from catalog_contents where product_stock_number like 2%
select cccatalog_entry_name from catalog_contents cc where ccproduct_stock_number like 2%
69
select t1catalog_entry_name from catalog_contents as t1 join catalog_contents_additional_attributes as t2 on t1catalog_entry_id = t2catalog_entry_id where t2catalog_level_number = 8
select cccatalog_entry_name from catalog_contents cc where cccatalog_level_number = 8
70
select t1catalog_entry_name from catalog_contents as t1 join catalog_contents_additional_attributes as t2 on t1catalog_entry_id = t2catalog_entry_id where t2catalog_level_number = 8
select cccatalog_entry_name from catalog_contents cc where cccatalog_level_number = 8
71
select catalog_entry_name from catalog_contents where length < 3 or width > 5
select pname from products p join catalog_contents cc on pcode = ccproduct_stock_number where (length(cclength) < 3 or length(ccheight) > 5)
72
select catalog_entry_name from catalog_contents where length < 3 or width > 5
select cccatalog_entry_name from catalog_contents cc where (cclength < 3 or cclength > 5) order by cccatalog_entry_name nulls last
73
select t1attribute_name , t1attribute_id from attribute_definitions as t1 join catalog_contents_additional_attributes as t2 on t1attribute_id = t2attribute_id where t2attribute_value = 0
select adattribute_name, adattribute_id from attribute_definitions ad join catalog_contents_additional_attributes caa on adattribute_id = caaattribute_id where caaattribute_value = 0
74
select t1attribute_name , t1attribute_id from attribute_definitions as t1 join catalog_contents_additional_attributes as t2 on t1attribute_id = t2attribute_id where t2attribute_value = 0
select adattribute_name, adattribute_id from attribute_definitions ad join catalog_contents_additional_attributes caa on adattribute_id = caaattribute_id where caaattribute_value = 0
75
select catalog_entry_name , capacity from catalog_contents where price_in_dollars > 700
select pname, pprice, cccapacity from products p join catalog_contents cc on pcode = cccatalog_entry_id where pprice > 70000
76
select catalog_entry_name , capacity from catalog_contents where price_in_dollars > 700
select cccatalog_entry_name, cccapacity from catalog_contents cc where ccprice_in_dollars > 700
77
select date_of_latest_revision from catalogs group by date_of_latest_revision having count(*) > 1
select distinct cdate_of_latest_revision from catalogs c where cdate_of_latest_revision in (select date_of_latest_revision from catalogs group by date_of_latest_revision having count(date_of_latest_revision) > 1)
78
select date_of_latest_revision from catalogs group by date_of_latest_revision having count(*) > 1
select cdate_of_publication, count(cdate_of_latest_revision) as revisions_count from catalogs c group by cdate_of_publication having count(cdate_of_latest_revision) > 1 order by cdate_of_publication nulls last
79
select count(*) from catalog_contents
select count(distinct pcode) from products p
80
select count(*) from catalog_contents
select count(cccatalog_entry_id) as total_catalog_contents from catalog_contents cc
81
select catalog_entry_name from catalog_contents where next_entry_id > 8
select pname, pprice, pcode, pmanufacturer from products p where pcode in (select cccatalog_entry_id from catalog_contents cc where ccnext_entry_id > 8)
82
select catalog_entry_name from catalog_contents where next_entry_id > 8
select cccatalog_entry_name from catalog_contents cc where ccnext_entry_id > 8
83
select count(*) from member where membership_card = black
select count(*) from member m where mmembership_card = black
84
select count(*) , address from member group by address
select maddress, count(maddress) as number_of_members from member m group by maddress order by number_of_members desc nulls last
85
select name from member where address = harford or address = waterbury
select mname from member m where maddress ilike %harford% or maddress ilike %waterbury% order by mname nulls last
86
select name , member_id from member where membership_card = black or age < 30
select mmember_id, mname from member m where mage < 30 or mmembership_card = black
87
select time_of_purchase , age , address from member order by time_of_purchase
select mtime_of_purchase, mage, maddress from member m order by mtime_of_purchase nulls last
88
select membership_card from member group by membership_card having count(*) > 5
select mmembership_card, count(*) as member_count from member m group by mmembership_card having count(*) > 5 order by member_count desc nulls last
89
select address from member where age < 30 intersect select address from member where age > 40
select maddress from member m where mage < 30 and mage > 40 group by maddress having count(mage) > 1
90
select membership_card from member where address = hartford intersect select membership_card from member where address = waterbury
select mmembership_card from member m where maddress ilike %hartford% and maddress ilike %waterbury% group by mmembership_card having count(distinct maddress) = 2 order by mmembership_card nulls last
91
select count(*) from member where address != hartford
select count(*) from member m where maddress not ilike %hartford%
92
select address from member except select address from member where membership_card = black
select maddress from member m where mmembership_card not like %black% order by maddress nulls last
93
select address from shop order by open_year
select sopen_year, saddress from shop s order by sopen_year nulls last
94
select avg(num_of_staff) , avg(score) from shop
select avg(sscore) as average_score, avg(snum_of_staff) as average_staff from shop s
95
select shop_id , address from shop where score < (select avg(score) from shop)

calculate_accuracy(normal_result)

In [55]:
import sqlparse
from sqlparse.sql import IdentifierList, Identifier
from sqlparse.tokens import Keyword, DML

def extract_query_components(query: str) -> dict:
    """
    Parse and extract key components from the SQL query.
    """
    parsed = sqlparse.parse(query)[0]  # Parse the SQL query
    components = {"select": [], "from": [], "where": []}
    
    current_keyword = None

    for token in parsed.tokens:
        if token.is_whitespace or token.ttype == sqlparse.tokens.Punctuation:
            continue  # Skip whitespaces and punctuation

        if token.ttype in (Keyword, DML):
            current_keyword = token.value.upper()

        if current_keyword == "SELECT" and isinstance(token, (IdentifierList, Identifier)):
            components["select"].extend([str(item).strip() for item in token.get_identifiers()])
        elif current_keyword == "FROM" and isinstance(token, Identifier):
            components["from"].append(str(token).strip())
        elif current_keyword == "WHERE" and token.ttype is None:
            components["where"].append(str(token).strip())

    return components

def are_queries_equivalent(query1: str, query2: str) -> bool:
    """
    Compare two SQL queries to check if they are logically equivalent.
    """
    # Normalize queries
    query1 = sqlparse.format(query1, keyword_case="upper", strip_comments=True)
    query2 = sqlparse.format(query2, keyword_case="upper", strip_comments=True)

    print(query1)
    print(query2)
    # Extract components from both queries
    components1 = extract_query_components(query1)
    components2 = extract_query_components(query2)
    print(components1)
    print(components2)

    # Compare the components
    return components1 == components2

# Example usage
if __name__ == "__main__":
    query1 = "SELECT id, name FROM test WHERE id = 1"
    query2 = "select name, id from test t where id = 1"

    is_equivalent = are_queries_equivalent(query1, query2)
    print(f"Are the queries equivalent? {is_equivalent}")

SELECT id, name FROM test WHERE id = 1
SELECT name, id FROM test t WHERE id = 1
{'select': ['id', 'name'], 'from': ['test'], 'where': []}
{'select': ['name', 'id'], 'from': ['test t'], 'where': []}
Are the queries equivalent? False

In [49]:
import sqlparse

def normalize_query(query):
    # Format and normalize the query
    parsed = sqlparse.format(query, reindent=True, keyword_case='upper')
    # Remove unnecessary whitespace and line breaks
    return ''.join([token.value for token in sqlparse.parse(parsed)[0].tokens if not token.is_whitespace])

def are_queries_equal(query1, query2):
    normalized_query1 = normalize_query(query1)
    print(normalized_query1)
    normalized_query2 = normalize_query(query2)
    print(normalized_query2)
    return normalized_query1 == normalized_query2

# Example usage
query1 = "SELECT * FROM users WHERE id = 1;"
query2 = "select * FROM users WHERE id=1"

if are_queries_equal(query1, query2):
    print("The SQL queries are equivalent.")
else:
    print("The SQL queries are not equivalent.")

SELECT*FROMusersWHERE id = 1;
SELECT*FROMusersWHERE id=1
The SQL queries are not equivalent.

In [46]:
import sqlparse

# Example query
query = "SELECT COUNT(*) FROM farm WHERE Total_Horses > 10;"
query = """SELECT fc.Hosts FROM "farm_competition" fc WHERE fc.Theme!= 'Aliens';"""
query = """SELECT f."Farm_ID", f."Total_Horses" FROM "farm" f ORDER BY f."Total_Horses" ASC;"""

# Parse the query
parsed = sqlparse.parse(query)[0]

# Print the parsed query
print(parsed.tokens)

[<DML 'SELECT' at 0x1B5D61EDC00>, <Whitespace ' ' at 0x1B5E7E8BB80>, <IdentifierList 'f."Far...' at 0x1B5D96AFC50>, <Whitespace ' ' at 0x1B5E7E8BDC0>, <Keyword 'FROM' at 0x1B5E7E89540>, <Whitespace ' ' at 0x1B5E7E8BD60>, <Identifier '"farm"...' at 0x1B5D96AFE50>, <Whitespace ' ' at 0x1B5E7E8B1C0>, <Keyword 'ORDER ...' at 0x1B5E7E89420>, <Whitespace ' ' at 0x1B5E7E8B160>, <Identifier 'f."Tot...' at 0x1B5D96AFD50>, <Punctuation ';' at 0x1B5E7E892A0>]

In [47]:
for token in parsed.tokens:
    if not token.is_whitespace:
        print(f"Type: {token.ttype}, Value: {token.value}")

Type: Token.Keyword.DML, Value: SELECT
Type: None, Value: f."Farm_ID", f."Total_Horses"
Type: Token.Keyword, Value: FROM
Type: None, Value: "farm" f
Type: Token.Keyword, Value: ORDER BY
Type: None, Value: f."Total_Horses" ASC
Type: Token.Punctuation, Value: ;

### Normalized match

In [43]:
import re

def normalize_sql(query):
    # Convert to lowercase
    query = query.lower()
    
    # Remove extra whitespaces
    query = re.sub(r'\s+', ' ', query).strip()
    
    # Standardize table and column aliases
    query = re.sub(r'(\s)([a-zA-Z_]\w*)(\s)(?=\.)', r' \1', query)  # removes aliasing of table/column
    
    # Remove quotes around table/column names (for simplicity, this assumes no conflicting keywords)
    query = re.sub(r'\"([^\"]+)\"', r'\1', query)
    
    # Normalize ORDER BY and GROUP BY clauses to avoid position-based differences
    query = re.sub(r'\border\sby\b.*', 'order by', query)
    query = re.sub(r'\bgroup\sby\b.*', 'group by', query)
    
    # Normalize SELECT and other SQL keywords to lowercase
    query = re.sub(r'\b(select|from|where|group by|order by|count|distinct)\b', lambda match: match.group(0).lower(), query)
    
    return query

def compare_queries(query1, query2):
    # Normalize both queries
    norm1 = normalize_sql(query1)
    norm2 = normalize_sql(query2)
    print(norm1)
    print(norm2)
    
    # Return if the normalized queries are the same
    return norm1 == norm2

# Example usage
spider_query = 'SELECT count(*) FROM farm'
text2sql_query = 'SELECT COUNT(*) FROM "farm" f'
#text2sql_query = """SELECT fc.Hosts FROM "farm_competition" fc WHERE fc.Theme!= 'Aliens';"""

normalized_match = compare_queries(spider_query, text2sql_query)
print(f"Normalized Match: {normalized_match}")

select count(*) from farm
select count(*) from farm f
Normalized Match: False

In [51]:
import sqlparse
from sqlparse.sql import Identifier, IdentifierList
from sqlparse.tokens import Keyword, DML

def remove_aliases_from_sql(sql_query):
    """
    Removes alias names from a SQL query while retaining the query's structure.
    :param sql_query: The SQL query string.
    :return: SQL query string without aliases.
    """
    parsed = sqlparse.parse(sql_query)[0]
    modified_query = []
    
    def strip_alias(identifier):
        """Strips alias from an identifier."""
        if identifier.get_real_name() != identifier.get_name():
            return identifier.get_real_name()  # Remove alias
        return identifier.get_name()
    
    for token in parsed.tokens:
        if isinstance(token, IdentifierList):
            # Process each identifier in the list
            new_identifiers = []
            for identifier in token.get_identifiers():
                if isinstance(identifier, Identifier):
                    stripped = strip_alias(identifier)
                    new_identifiers.append(stripped)
                else:
                    new_identifiers.append(str(identifier))
            modified_query.append(", ".join(new_identifiers))
        elif isinstance(token, Identifier):
            # Process individual identifiers
            stripped = strip_alias(token)
            modified_query.append(stripped)
        else:
            # Add non-identifier tokens as-is
            modified_query.append(str(token))
    
    return " ".join(modified_query)

# Example usage
sql_query = """
SELECT a.id AS user_id, b.name AS user_name, c.age FROM users a
JOIN details b ON a.id = b.user_id
JOIN info c ON b.id = c.detail_id
WHERE a.status = 'active'
"""

clean_query = remove_aliases_from_sql(sql_query)
print("Original Query:\n", sql_query)
print("\nCleaned Query:\n", clean_query)

Original Query:

SELECT a.id AS user_id, b.name AS user_name, c.age FROM users a
JOIN details b ON a.id = b.user_id
JOIN info c ON b.id = c.detail_id
WHERE a.status = 'active'


Cleaned Query:

 SELECT   id, name, age   FROM   users
 JOIN   details   ON   a.id = b.user_id
 JOIN   info   ON   b.id = c.detail_id
 WHERE a.status = 'active'