## Spider Dataset

Link: https://yale-lily.github.io/spider

In [1]:
import json
import pandas as pd

# Path to the JSON file
file_path = r"C:\Research-Paper\spider_data\spider_data\train_spider.json"

# Read the JSON file
with open(file_path, 'r', encoding='utf-8') as file:
    data = json.load(file)

# Convert to a Pandas DataFrame
df = pd.json_normalize(data)

# Display the DataFrame
print(df.head())

                   db_id                                              query  \
0  department_management         SELECT count(*) FROM head WHERE age  >  56
1  department_management  SELECT name ,  born_state ,  age FROM head ORD...
2  department_management  SELECT creation ,  name ,  budget_in_billions ...
3  department_management  SELECT max(budget_in_billions) ,  min(budget_i...
4  department_management  SELECT avg(num_employees) FROM department WHER...

                                          query_toks  \
0  [SELECT, count, (, *, ), FROM, head, WHERE, ag...
1  [SELECT, name, ,, born_state, ,, age, FROM, he...
2  [SELECT, creation, ,, name, ,, budget_in_billi...
3  [SELECT, max, (, budget_in_billions, ), ,, min...
4  [SELECT, avg, (, num_employees, ), FROM, depar...

                                 query_toks_no_value  \
0  [select, count, (, *, ), from, head, where, ag...
1  [select, name, ,, born_state, ,, age, from, he...
2  [select, creation, ,, name, ,, budget_in_billi...
3  [select, max, (, budget_in_billions, ), ,, min...
4  [select, avg, (, num_employees, ), from, depar...

                                            question  \
0  How many heads of the departments are older th...
1  List the name, born state and age of the heads...
2  List the creation year, name and budget of eac...
3  What are the maximum and minimum budget of the...
4  What is the average number of employees of the...

                                       question_toks sql.from.table_units  \
0  [How, many, heads, of, the, departments, are, ...    [[table_unit, 1]]
1  [List, the, name, ,, born, state, and, age, of...    [[table_unit, 1]]
2  [List, the, creation, year, ,, name, and, budg...    [[table_unit, 0]]
3  [What, are, the, maximum, and, minimum, budget...    [[table_unit, 0]]
4  [What, is, the, average, number, of, employees...    [[table_unit, 0]]

  sql.from.conds                                         sql.select  \
0             []           [False, [[3, [0, [0, 0, False], None]]]]
1             []  [False, [[0, [0, [0, 8, False], None]], [0, [0...
2             []  [False, [[0, [0, [0, 3, False], None]], [0, [0...
3             []  [False, [[1, [0, [0, 5, False], None]], [2, [0...
4             []           [False, [[5, [0, [0, 6, False], None]]]]

                                           sql.where  ...  \
0  [[False, 3, [0, [0, 10, False], None], 56.0, N...  ...
1                                                 []  ...
2                                                 []  ...
3                                                 []  ...
4  [[False, 1, [0, [0, 4, False], None], 10.0, 15...  ...

  sql.except.from.conds sql.except.select sql.except.where  \
0                   NaN               NaN              NaN
1                   NaN               NaN              NaN
2                   NaN               NaN              NaN
3                   NaN               NaN              NaN
4                   NaN               NaN              NaN

   sql.except.groupBy  sql.except.having  sql.except.orderBy  \
0                 NaN                NaN                 NaN
1                 NaN                NaN                 NaN
2                 NaN                NaN                 NaN
3                 NaN                NaN                 NaN
4                 NaN                NaN                 NaN

   sql.except.limit sql.except.intersect sql.except.union sql.except.except
0               NaN                  NaN              NaN               NaN
1               NaN                  NaN              NaN               NaN
2               NaN                  NaN              NaN               NaN
3               NaN                  NaN              NaN               NaN
4               NaN                  NaN              NaN               NaN

[5 rows x 50 columns]

In [2]:
print(df.shape)

(7000, 50)

#### Getting number of unique db id's

In [3]:
df["db_id"].nunique()

140

In [4]:
df["db_id"].unique()

array(['department_management', 'farm', 'student_assessment', 'bike_1',
       'book_2', 'musical', 'twitter_1', 'product_catalog', 'flight_1',
       'allergy_1', 'store_1', 'journal_committee',
       'customers_card_transactions', 'race_track', 'coffee_shop',
       'chinook_1', 'insurance_fnol', 'medicine_enzyme_interaction',
       'university_basketball', 'phone_1', 'match_season', 'climbing',
       'body_builder', 'election_representative', 'apartment_rentals',
       'game_injury', 'soccer_1', 'performance_attendance', 'college_2',
       'debate', 'insurance_and_eClaims', 'customers_and_invoices',
       'wedding', 'theme_gallery', 'epinions_1', 'riding_club', 'gymnast',
       'small_bank_1', 'browser_web', 'wrestler', 'school_finance',
       'protein_institute', 'cinema', 'products_for_hire', 'phone_market',
       'gas_company', 'party_people', 'pilot_record',
       'cre_Doc_Control_Systems', 'company_1', 'local_govt_in_alabama',
       'formula_1', 'machine_repair', 'entrepreneur', 'perpetrator',
       'csu_1', 'candidate_poll', 'movie_1', 'county_public_safety',
       'inn_1', 'local_govt_mdm', 'party_host', 'storm_record',
       'election', 'news_report', 'restaurant_1', 'customer_deliveries',
       'icfp_1', 'sakila_1', 'loan_1', 'behavior_monitoring',
       'assets_maintenance', 'station_weather', 'college_1',
       'sports_competition', 'manufacturer', 'hr_1', 'music_1',
       'baseball_1', 'mountain_photos', 'program_share', 'e_learning',
       'insurance_policies', 'hospital_1', 'ship_mission', 'student_1',
       'company_employee', 'film_rank', 'cre_Doc_Tracking_DB', 'club_1',
       'tracking_grants_for_research', 'network_2',
       'decoration_competition', 'document_management', 'company_office',
       'solvency_ii', 'entertainment_awards',
       'customers_campaigns_ecommerce', 'college_3', 'department_store',
       'aircraft', 'local_govt_and_lot', 'school_player', 'store_product',
       'soccer_2', 'device', 'cre_Drama_Workshop_Groups', 'music_2',
       'manufactory_1', 'tracking_software_problems', 'shop_membership',
       'voter_2', 'products_gen_characteristics', 'swimming', 'railway',
       'customers_and_products_contacts', 'dorm_1', 'customer_complaints',
       'workshop_paper', 'tracking_share_transactions', 'cre_Theme_park',
       'game_1', 'customers_and_addresses', 'music_4', 'roller_coaster',
       'ship_1', 'city_record', 'e_government', 'school_bus',
       'flight_company', 'cre_Docs_and_Epenses', 'scientist_1', 'wine_1',
       'train_station', 'driving_school', 'activity_1', 'flight_4',
       'tracking_orders', 'architecture', 'culture_company'], dtype=object)

In [3]:
spider_df = df[["db_id","query","question"]]

In [6]:
spider_df.shape

(7000, 3)

In [7]:
spider_df.head(10)

,db_id,query,question
0,department_management,SELECT count(*) FROM head WHERE age > 56,How many heads of the departments are older th...
1,department_management,"SELECT name , born_state , age FROM head ORD...","List the name, born state and age of the heads..."
2,department_management,"SELECT creation , name , budget_in_billions ...","List the creation year, name and budget of eac..."
3,department_management,"SELECT max(budget_in_billions) , min(budget_i...",What are the maximum and minimum budget of the...
4,department_management,SELECT avg(num_employees) FROM department WHER...,What is the average number of employees of the...
5,department_management,SELECT name FROM head WHERE born_state != 'Cal...,What are the names of the heads who are born o...
6,department_management,SELECT DISTINCT T1.creation FROM department AS...,What are the distinct creation years of the de...
7,department_management,SELECT born_state FROM head GROUP BY born_stat...,What are the names of the states where at leas...
8,department_management,SELECT creation FROM department GROUP BY creat...,In which year were most departments established?
9,department_management,"SELECT T1.name , T1.num_employees FROM depart...",Show the name and number of employees for the ...

In [8]:
# Iterate through the first 10 rows of useful_df
for index, row in spider_df.head(20).iterrows():
    print(f"Row {index}:")
    print(row)
    print("-" * 80)  # Separator for readability

Row 0:
db_id                                   department_management
query              SELECT count(*) FROM head WHERE age  >  56
question    How many heads of the departments are older th...
Name: 0, dtype: object
--------------------------------------------------------------------------------
Row 1:
db_id                                   department_management
query       SELECT name ,  born_state ,  age FROM head ORD...
question    List the name, born state and age of the heads...
Name: 1, dtype: object
--------------------------------------------------------------------------------
Row 2:
db_id                                   department_management
query       SELECT creation ,  name ,  budget_in_billions ...
question    List the creation year, name and budget of eac...
Name: 2, dtype: object
--------------------------------------------------------------------------------
Row 3:
db_id                                   department_management
query       SELECT max(budget_in_billions) ,  min(budget_i...
question    What are the maximum and minimum budget of the...
Name: 3, dtype: object
--------------------------------------------------------------------------------
Row 4:
db_id                                   department_management
query       SELECT avg(num_employees) FROM department WHER...
question    What is the average number of employees of the...
Name: 4, dtype: object
--------------------------------------------------------------------------------
Row 5:
db_id                                   department_management
query       SELECT name FROM head WHERE born_state != 'Cal...
question    What are the names of the heads who are born o...
Name: 5, dtype: object
--------------------------------------------------------------------------------
Row 6:
db_id                                   department_management
query       SELECT DISTINCT T1.creation FROM department AS...
question    What are the distinct creation years of the de...
Name: 6, dtype: object
--------------------------------------------------------------------------------
Row 7:
db_id                                   department_management
query       SELECT born_state FROM head GROUP BY born_stat...
question    What are the names of the states where at leas...
Name: 7, dtype: object
--------------------------------------------------------------------------------
Row 8:
db_id                                   department_management
query       SELECT creation FROM department GROUP BY creat...
question     In which year were most departments established?
Name: 8, dtype: object
--------------------------------------------------------------------------------
Row 9:
db_id                                   department_management
query       SELECT T1.name ,  T1.num_employees FROM depart...
question    Show the name and number of employees for the ...
Name: 9, dtype: object
--------------------------------------------------------------------------------
Row 10:
db_id                                   department_management
query       SELECT count(DISTINCT temporary_acting) FROM m...
question                  How many acting statuses are there?
Name: 10, dtype: object
--------------------------------------------------------------------------------
Row 11:
db_id                                   department_management
query       SELECT count(*) FROM department WHERE departme...
question    How many departments are led by heads who are ...
Name: 11, dtype: object
--------------------------------------------------------------------------------
Row 12:
db_id                                   department_management
query       SELECT DISTINCT T1.age FROM management AS T2 J...
question    What are the distinct ages of the heads who ar...
Name: 12, dtype: object
--------------------------------------------------------------------------------
Row 13:
db_id                                   department_management
query       SELECT T3.born_state FROM department AS T1 JOI...
question    List the states where both the secretary of 'T...
Name: 13, dtype: object
--------------------------------------------------------------------------------
Row 14:
db_id                                   department_management
query       SELECT T1.department_id ,  T1.name ,  count(*)...
question    Which department has more than 1 head at a tim...
Name: 14, dtype: object
--------------------------------------------------------------------------------
Row 15:
db_id                                   department_management
query       SELECT head_id ,  name FROM head WHERE name LI...
question    Which head's name has the substring 'Ha'? List...
Name: 15, dtype: object
--------------------------------------------------------------------------------
Row 16:
db_id                            farm
query       SELECT count(*) FROM farm
question    How many farms are there?
Name: 16, dtype: object
--------------------------------------------------------------------------------
Row 17:
db_id                             farm
query        SELECT count(*) FROM farm
question    Count the number of farms.
Name: 17, dtype: object
--------------------------------------------------------------------------------
Row 18:
db_id                                                    farm
query       SELECT Total_Horses FROM farm ORDER BY Total_H...
question    List the total number of horses on farms in as...
Name: 18, dtype: object
--------------------------------------------------------------------------------
Row 19:
db_id                                                    farm
query       SELECT Total_Horses FROM farm ORDER BY Total_H...
question    What is the total horses record for each farm,...
Name: 19, dtype: object
--------------------------------------------------------------------------------

#### Fetching data of specific db_id

In [9]:
spider_df[spider_df["db_id"]=="farm"]

,db_id,query,question
16,farm,SELECT count(*) FROM farm,How many farms are there?
17,farm,SELECT count(*) FROM farm,Count the number of farms.
18,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,List the total number of horses on farms in as...
19,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,"What is the total horses record for each farm,..."
20,farm,SELECT Hosts FROM farm_competition WHERE Theme...,What are the hosts of competitions whose theme...
21,farm,SELECT Hosts FROM farm_competition WHERE Theme...,Return the hosts of competitions for which the...
22,farm,SELECT Theme FROM farm_competition ORDER BY YE...,What are the themes of farm competitions sorte...
23,farm,SELECT Theme FROM farm_competition ORDER BY YE...,"Return the themes of farm competitions, sorted..."
24,farm,SELECT avg(Working_Horses) FROM farm WHERE Tot...,What is the average number of working horses o...
25,farm,SELECT avg(Working_Horses) FROM farm WHERE Tot...,Give the average number of working horses on f...
26,farm,"SELECT max(Cows) , min(Cows) FROM farm",What are the maximum and minimum number of cow...
27,farm,"SELECT max(Cows) , min(Cows) FROM farm",Return the maximum and minimum number of cows ...
28,farm,SELECT count(DISTINCT Status) FROM city,How many different statuses do cities have?
29,farm,SELECT count(DISTINCT Status) FROM city,Count the number of different statuses.
30,farm,SELECT Official_Name FROM city ORDER BY Popula...,List official names of cities in descending or...
31,farm,SELECT Official_Name FROM city ORDER BY Popula...,"What are the official names of cities, ordered..."
32,farm,"SELECT Official_Name , Status FROM city ORDER...",List the official name and status of the city ...
33,farm,"SELECT Official_Name , Status FROM city ORDER...",What is the official name and status of the ci...
34,farm,"SELECT T2.Year , T1.Official_Name FROM city A...",Show the years and the official names of the h...
35,farm,"SELECT T2.Year , T1.Official_Name FROM city A...",Give the years and official names of the citie...
36,farm,SELECT T1.Official_Name FROM city AS T1 JOIN f...,Show the official names of the cities that hav...
37,farm,SELECT T1.Official_Name FROM city AS T1 JOIN f...,What are the official names of cities that hav...
38,farm,SELECT T1.Status FROM city AS T1 JOIN farm_com...,Show the status of the city that has hosted th...
39,farm,SELECT T1.Status FROM city AS T1 JOIN farm_com...,What is the status of the city that has hosted...
40,farm,SELECT T2.Theme FROM city AS T1 JOIN farm_comp...,Please show the themes of competitions with ho...
41,farm,SELECT T2.Theme FROM city AS T1 JOIN farm_comp...,What are the themes of competitions that have ...
42,farm,"SELECT Status , avg(Population) FROM city GRO...",Please show the different statuses of cities a...
43,farm,"SELECT Status , avg(Population) FROM city GRO...",What are the statuses and average populations ...
44,farm,SELECT Status FROM city GROUP BY Status ORDER ...,"Please show the different statuses, ordered by..."
45,farm,SELECT Status FROM city GROUP BY Status ORDER ...,"Return the different statuses of cities, ascen..."
46,farm,SELECT Status FROM city GROUP BY Status ORDER ...,List the most common type of Status across cit...
47,farm,SELECT Status FROM city GROUP BY Status ORDER ...,What is the most common status across all cities?
48,farm,SELECT Official_Name FROM city WHERE City_ID N...,List the official names of cities that have no...
49,farm,SELECT Official_Name FROM city WHERE City_ID N...,What are the official names of cities that hav...
50,farm,SELECT Status FROM city WHERE Population > 1...,Show the status shared by cities with populati...
51,farm,SELECT Status FROM city WHERE Population > 1...,Which statuses correspond to both cities that ...
52,farm,SELECT Official_Name FROM city WHERE Populatio...,Find the official names of cities with populat...
53,farm,SELECT Official_Name FROM city WHERE Populatio...,What are the official names of cities that hav...
54,farm,SELECT Census_Ranking FROM city WHERE Status !...,Show the census ranking of cities whose status...
55,farm,SELECT Census_Ranking FROM city WHERE Status !...,What are the census rankings of cities that do...

In [4]:
# List of db_id values to match
l = ["farm","film_rank","election","wrestler","wedding","swimming","climbing","device","loan_1","movie_1",
    "railway","coffee_shop","game_1","insurance_policies","product_catalog"]

# Filtering rows where db_id is in the list l
filtered_considered_df = spider_df[spider_df['db_id'].isin(l)]

# Counting occurrences of each element in l
count_per_element = filtered_considered_df['db_id'].value_counts()

# Ensuring all elements from l are in the count
count_per_element = count_per_element.reindex(l, fill_value=0)

print("Filtered DataFrame:")
print(filtered_considered_df.shape)
print("\n---------------\nCount of each element:")
print(count_per_element)

Filtered DataFrame:
(719, 3)

---------------
Count of each element:
db_id
farm                  40
film_rank             48
election              68
wrestler              40
wedding               20
swimming              30
climbing              40
device                40
loan_1                80
movie_1               98
railway               21
coffee_shop           18
game_1                86
insurance_policies    48
product_catalog       42
Name: count, dtype: int64

In [7]:
filtered_considered_df

# Assuming useful_df is already defined
# Filter rows where 'query' contains the word "join" or "JOIN"
filtered_considered_join_df = filtered_considered_df[filtered_considered_df['query'].str.contains(r'\bjoin\b', case=False, na=False)]

# Display the new DataFrame
filtered_considered_join_df

,db_id,query,question
34,farm,"SELECT T2.Year , T1.Official_Name FROM city A...",Show the years and the official names of the h...
35,farm,"SELECT T2.Year , T1.Official_Name FROM city A...",Give the years and official names of the citie...
36,farm,SELECT T1.Official_Name FROM city AS T1 JOIN f...,Show the official names of the cities that hav...
37,farm,SELECT T1.Official_Name FROM city AS T1 JOIN f...,What are the official names of cities that hav...
38,farm,SELECT T1.Status FROM city AS T1 JOIN farm_com...,Show the status of the city that has hosted th...
...,...,...,...
6048,game_1,SELECT Gname FROM Plays_games AS T1 JOIN Video...,What are the names of all games played by Lind...
6049,game_1,"SELECT T2.lname , T2.fname FROM SportsInfo AS...",Find the last and first name of students who a...
6050,game_1,"SELECT T2.lname , T2.fname FROM SportsInfo AS...",What is the first and last name of all student...
6053,game_1,"SELECT lname , sex FROM Student WHERE StuID I...",Find the last name and gender of the students ...
6054,game_1,"SELECT lname , sex FROM Student WHERE StuID I...",what is the last name and gender of all studen...

In [69]:
check = "farm"
spider_df[spider_df["db_id"]==check].shape

(40, 3)

In [70]:
for index, row in spider_df[spider_df["db_id"]==check].iterrows():
    print(f"Row {index}:")
    print(row)
    print("##########")
    print(row["query"])
    print(row["question"])
    print("-" * 80)  # Separator for readability

Row 16:
db_id                            farm
query       SELECT count(*) FROM farm
question    How many farms are there?
Name: 16, dtype: object
##########
SELECT count(*) FROM farm
How many farms are there?
--------------------------------------------------------------------------------
Row 17:
db_id                             farm
query        SELECT count(*) FROM farm
question    Count the number of farms.
Name: 17, dtype: object
##########
SELECT count(*) FROM farm
Count the number of farms.
--------------------------------------------------------------------------------
Row 18:
db_id                                                    farm
query       SELECT Total_Horses FROM farm ORDER BY Total_H...
question    List the total number of horses on farms in as...
Name: 18, dtype: object
##########
SELECT Total_Horses FROM farm ORDER BY Total_Horses ASC
List the total number of horses on farms in ascending order.
--------------------------------------------------------------------------------
Row 19:
db_id                                                    farm
query       SELECT Total_Horses FROM farm ORDER BY Total_H...
question    What is the total horses record for each farm,...
Name: 19, dtype: object
##########
SELECT Total_Horses FROM farm ORDER BY Total_Horses ASC
What is the total horses record for each farm, sorted ascending?
--------------------------------------------------------------------------------
Row 20:
db_id                                                    farm
query       SELECT Hosts FROM farm_competition WHERE Theme...
question    What are the hosts of competitions whose theme...
Name: 20, dtype: object
##########
SELECT Hosts FROM farm_competition WHERE Theme !=  'Aliens'
What are the hosts of competitions whose theme is not "Aliens"?
--------------------------------------------------------------------------------
Row 21:
db_id                                                    farm
query       SELECT Hosts FROM farm_competition WHERE Theme...
question    Return the hosts of competitions for which the...
Name: 21, dtype: object
##########
SELECT Hosts FROM farm_competition WHERE Theme !=  'Aliens'
Return the hosts of competitions for which the theme is not Aliens?
--------------------------------------------------------------------------------
Row 22:
db_id                                                    farm
query       SELECT Theme FROM farm_competition ORDER BY YE...
question    What are the themes of farm competitions sorte...
Name: 22, dtype: object
##########
SELECT Theme FROM farm_competition ORDER BY YEAR ASC
What are the themes of farm competitions sorted by year in ascending order?
--------------------------------------------------------------------------------
Row 23:
db_id                                                    farm
query       SELECT Theme FROM farm_competition ORDER BY YE...
question    Return the themes of farm competitions, sorted...
Name: 23, dtype: object
##########
SELECT Theme FROM farm_competition ORDER BY YEAR ASC
Return the themes of farm competitions, sorted by year ascending.
--------------------------------------------------------------------------------
Row 24:
db_id                                                    farm
query       SELECT avg(Working_Horses) FROM farm WHERE Tot...
question    What is the average number of working horses o...
Name: 24, dtype: object
##########
SELECT avg(Working_Horses) FROM farm WHERE Total_Horses  >  5000
What is the average number of working horses of farms with more than 5000 total number of horses?
--------------------------------------------------------------------------------
Row 25:
db_id                                                    farm
query       SELECT avg(Working_Horses) FROM farm WHERE Tot...
question    Give the average number of working horses on f...
Name: 25, dtype: object
##########
SELECT avg(Working_Horses) FROM farm WHERE Total_Horses  >  5000
Give the average number of working horses on farms with more than 5000 total horses.
--------------------------------------------------------------------------------
Row 26:
db_id                                                    farm
query                 SELECT max(Cows) ,  min(Cows) FROM farm
question    What are the maximum and minimum number of cow...
Name: 26, dtype: object
##########
SELECT max(Cows) ,  min(Cows) FROM farm
What are the maximum and minimum number of cows across all farms.
--------------------------------------------------------------------------------
Row 27:
db_id                                                    farm
query                 SELECT max(Cows) ,  min(Cows) FROM farm
question    Return the maximum and minimum number of cows ...
Name: 27, dtype: object
##########
SELECT max(Cows) ,  min(Cows) FROM farm
Return the maximum and minimum number of cows across all farms.
--------------------------------------------------------------------------------
Row 28:
db_id                                              farm
query           SELECT count(DISTINCT Status) FROM city
question    How many different statuses do cities have?
Name: 28, dtype: object
##########
SELECT count(DISTINCT Status) FROM city
How many different statuses do cities have?
--------------------------------------------------------------------------------
Row 29:
db_id                                          farm
query       SELECT count(DISTINCT Status) FROM city
question    Count the number of different statuses.
Name: 29, dtype: object
##########
SELECT count(DISTINCT Status) FROM city
Count the number of different statuses.
--------------------------------------------------------------------------------
Row 30:
db_id                                                    farm
query       SELECT Official_Name FROM city ORDER BY Popula...
question    List official names of cities in descending or...
Name: 30, dtype: object
##########
SELECT Official_Name FROM city ORDER BY Population DESC
List official names of cities in descending order of population.
--------------------------------------------------------------------------------
Row 31:
db_id                                                    farm
query       SELECT Official_Name FROM city ORDER BY Popula...
question    What are the official names of cities, ordered...
Name: 31, dtype: object
##########
SELECT Official_Name FROM city ORDER BY Population DESC
What are the official names of cities, ordered descending by population?
--------------------------------------------------------------------------------
Row 32:
db_id                                                    farm
query       SELECT Official_Name ,  Status FROM city ORDER...
question    List the official name and status of the city ...
Name: 32, dtype: object
##########
SELECT Official_Name ,  Status FROM city ORDER BY Population DESC LIMIT 1
List the official name and status of the city with the largest population.
--------------------------------------------------------------------------------
Row 33:
db_id                                                    farm
query       SELECT Official_Name ,  Status FROM city ORDER...
question    What is the official name and status of the ci...
Name: 33, dtype: object
##########
SELECT Official_Name ,  Status FROM city ORDER BY Population DESC LIMIT 1
What is the official name and status of the city with the most residents?
--------------------------------------------------------------------------------
Row 34:
db_id                                                    farm
query       SELECT T2.Year ,  T1.Official_Name FROM city A...
question    Show the years and the official names of the h...
Name: 34, dtype: object
##########
SELECT T2.Year ,  T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID
Show the years and the official names of the host cities of competitions.
--------------------------------------------------------------------------------
Row 35:
db_id                                                    farm
query       SELECT T2.Year ,  T1.Official_Name FROM city A...
question    Give the years and official names of the citie...
Name: 35, dtype: object
##########
SELECT T2.Year ,  T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID
Give the years and official names of the cities of each competition.
--------------------------------------------------------------------------------
Row 36:
db_id                                                    farm
query       SELECT T1.Official_Name FROM city AS T1 JOIN f...
question    Show the official names of the cities that hav...
Name: 36, dtype: object
##########
SELECT T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID HAVING COUNT(*)  >  1
Show the official names of the cities that have hosted more than one competition.
--------------------------------------------------------------------------------
Row 37:
db_id                                                    farm
query       SELECT T1.Official_Name FROM city AS T1 JOIN f...
question    What are the official names of cities that hav...
Name: 37, dtype: object
##########
SELECT T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID HAVING COUNT(*)  >  1
What are the official names of cities that have hosted more than one competition?
--------------------------------------------------------------------------------
Row 38:
db_id                                                    farm
query       SELECT T1.Status FROM city AS T1 JOIN farm_com...
question    Show the status of the city that has hosted th...
Name: 38, dtype: object
##########
SELECT T1.Status FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID ORDER BY COUNT(*) DESC LIMIT 1
Show the status of the city that has hosted the greatest number of competitions.
--------------------------------------------------------------------------------
Row 39:
db_id                                                    farm
query       SELECT T1.Status FROM city AS T1 JOIN farm_com...
question    What is the status of the city that has hosted...
Name: 39, dtype: object
##########
SELECT T1.Status FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID ORDER BY COUNT(*) DESC LIMIT 1
What is the status of the city that has hosted the most competitions?
--------------------------------------------------------------------------------
Row 40:
db_id                                                    farm
query       SELECT T2.Theme FROM city AS T1 JOIN farm_comp...
question    Please show the themes of competitions with ho...
Name: 40, dtype: object
##########
SELECT T2.Theme FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID WHERE T1.Population  >  1000
Please show the themes of competitions with host cities having populations larger than 1000.
--------------------------------------------------------------------------------
Row 41:
db_id                                                    farm
query       SELECT T2.Theme FROM city AS T1 JOIN farm_comp...
question    What are the themes of competitions that have ...
Name: 41, dtype: object
##########
SELECT T2.Theme FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID WHERE T1.Population  >  1000
What are the themes of competitions that have corresponding host cities with more than 1000 residents?
--------------------------------------------------------------------------------
Row 42:
db_id                                                    farm
query       SELECT Status ,  avg(Population) FROM city GRO...
question    Please show the different statuses of cities a...
Name: 42, dtype: object
##########
SELECT Status ,  avg(Population) FROM city GROUP BY Status
Please show the different statuses of cities and the average population of cities with each status.
--------------------------------------------------------------------------------
Row 43:
db_id                                                    farm
query       SELECT Status ,  avg(Population) FROM city GRO...
question    What are the statuses and average populations ...
Name: 43, dtype: object
##########
SELECT Status ,  avg(Population) FROM city GROUP BY Status
What are the statuses and average populations of each city?
--------------------------------------------------------------------------------
Row 44:
db_id                                                    farm
query       SELECT Status FROM city GROUP BY Status ORDER ...
question    Please show the different statuses, ordered by...
Name: 44, dtype: object
##########
SELECT Status FROM city GROUP BY Status ORDER BY COUNT(*) ASC
Please show the different statuses, ordered by the number of cities that have each.
--------------------------------------------------------------------------------
Row 45:
db_id                                                    farm
query       SELECT Status FROM city GROUP BY Status ORDER ...
question    Return the different statuses of cities, ascen...
Name: 45, dtype: object
##########
SELECT Status FROM city GROUP BY Status ORDER BY COUNT(*) ASC
Return the different statuses of cities, ascending by frequency.
--------------------------------------------------------------------------------
Row 46:
db_id                                                    farm
query       SELECT Status FROM city GROUP BY Status ORDER ...
question    List the most common type of Status across cit...
Name: 46, dtype: object
##########
SELECT Status FROM city GROUP BY Status ORDER BY COUNT(*) DESC LIMIT 1
List the most common type of Status across cities.
--------------------------------------------------------------------------------
Row 47:
db_id                                                    farm
query       SELECT Status FROM city GROUP BY Status ORDER ...
question    What is the most common status across all cities?
Name: 47, dtype: object
##########
SELECT Status FROM city GROUP BY Status ORDER BY COUNT(*) DESC LIMIT 1
What is the most common status across all cities?
--------------------------------------------------------------------------------
Row 48:
db_id                                                    farm
query       SELECT Official_Name FROM city WHERE City_ID N...
question    List the official names of cities that have no...
Name: 48, dtype: object
##########
SELECT Official_Name FROM city WHERE City_ID NOT IN (SELECT Host_city_ID FROM farm_competition)
List the official names of cities that have not held any competition.
--------------------------------------------------------------------------------
Row 49:
db_id                                                    farm
query       SELECT Official_Name FROM city WHERE City_ID N...
question    What are the official names of cities that hav...
Name: 49, dtype: object
##########
SELECT Official_Name FROM city WHERE City_ID NOT IN (SELECT Host_city_ID FROM farm_competition)
What are the official names of cities that have not hosted a farm competition?
--------------------------------------------------------------------------------
Row 50:
db_id                                                    farm
query       SELECT Status FROM city WHERE Population  >  1...
question    Show the status shared by cities with populati...
Name: 50, dtype: object
##########
SELECT Status FROM city WHERE Population  >  1500 INTERSECT SELECT Status FROM city WHERE Population  <  500
Show the status shared by cities with population bigger than 1500 and smaller than 500.
--------------------------------------------------------------------------------
Row 51:
db_id                                                    farm
query       SELECT Status FROM city WHERE Population  >  1...
question    Which statuses correspond to both cities that ...
Name: 51, dtype: object
##########
SELECT Status FROM city WHERE Population  >  1500 INTERSECT SELECT Status FROM city WHERE Population  <  500
Which statuses correspond to both cities that have a population over 1500 and cities that have a population lower than 500?
--------------------------------------------------------------------------------
Row 52:
db_id                                                    farm
query       SELECT Official_Name FROM city WHERE Populatio...
question    Find the official names of cities with populat...
Name: 52, dtype: object
##########
SELECT Official_Name FROM city WHERE Population  >  1500 OR Population  <  500
Find the official names of cities with population bigger than 1500 or smaller than 500.
--------------------------------------------------------------------------------
Row 53:
db_id                                                    farm
query       SELECT Official_Name FROM city WHERE Populatio...
question    What are the official names of cities that hav...
Name: 53, dtype: object
##########
SELECT Official_Name FROM city WHERE Population  >  1500 OR Population  <  500
What are the official names of cities that have population over 1500 or less than 500?
--------------------------------------------------------------------------------
Row 54:
db_id                                                    farm
query       SELECT Census_Ranking FROM city WHERE Status !...
question    Show the census ranking of cities whose status...
Name: 54, dtype: object
##########
SELECT Census_Ranking FROM city WHERE Status !=  "Village"
Show the census ranking of cities whose status are not "Village".
--------------------------------------------------------------------------------
Row 55:
db_id                                                    farm
query       SELECT Census_Ranking FROM city WHERE Status !...
question    What are the census rankings of cities that do...
Name: 55, dtype: object
##########
SELECT Census_Ranking FROM city WHERE Status !=  "Village"
What are the census rankings of cities that do not have the status "Village"?
--------------------------------------------------------------------------------

In [72]:
question_list = []
query_list = []
for index, row in spider_df[spider_df["db_id"]==check].iterrows():
    question_list.append(row["question"])
    query_list.append(row["query"])

In [74]:
query_list

['SELECT count(*) FROM farm',
 'SELECT count(*) FROM farm',
 'SELECT Total_Horses FROM farm ORDER BY Total_Horses ASC',
 'SELECT Total_Horses FROM farm ORDER BY Total_Horses ASC',
 "SELECT Hosts FROM farm_competition WHERE Theme !=  'Aliens'",
 "SELECT Hosts FROM farm_competition WHERE Theme !=  'Aliens'",
 'SELECT Theme FROM farm_competition ORDER BY YEAR ASC',
 'SELECT Theme FROM farm_competition ORDER BY YEAR ASC',
 'SELECT avg(Working_Horses) FROM farm WHERE Total_Horses  >  5000',
 'SELECT avg(Working_Horses) FROM farm WHERE Total_Horses  >  5000',
 'SELECT max(Cows) ,  min(Cows) FROM farm',
 'SELECT max(Cows) ,  min(Cows) FROM farm',
 'SELECT count(DISTINCT Status) FROM city',
 'SELECT count(DISTINCT Status) FROM city',
 'SELECT Official_Name FROM city ORDER BY Population DESC',
 'SELECT Official_Name FROM city ORDER BY Population DESC',
 'SELECT Official_Name ,  Status FROM city ORDER BY Population DESC LIMIT 1',
 'SELECT Official_Name ,  Status FROM city ORDER BY Population DESC LIMIT 1',
 'SELECT T2.Year ,  T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID',
 'SELECT T2.Year ,  T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID',
 'SELECT T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID HAVING COUNT(*)  >  1',
 'SELECT T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID HAVING COUNT(*)  >  1',
 'SELECT T1.Status FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID ORDER BY COUNT(*) DESC LIMIT 1',
 'SELECT T1.Status FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID ORDER BY COUNT(*) DESC LIMIT 1',
 'SELECT T2.Theme FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID WHERE T1.Population  >  1000',
 'SELECT T2.Theme FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID WHERE T1.Population  >  1000',
 'SELECT Status ,  avg(Population) FROM city GROUP BY Status',
 'SELECT Status ,  avg(Population) FROM city GROUP BY Status',
 'SELECT Status FROM city GROUP BY Status ORDER BY COUNT(*) ASC',
 'SELECT Status FROM city GROUP BY Status ORDER BY COUNT(*) ASC',
 'SELECT Status FROM city GROUP BY Status ORDER BY COUNT(*) DESC LIMIT 1',
 'SELECT Status FROM city GROUP BY Status ORDER BY COUNT(*) DESC LIMIT 1',
 'SELECT Official_Name FROM city WHERE City_ID NOT IN (SELECT Host_city_ID FROM farm_competition)',
 'SELECT Official_Name FROM city WHERE City_ID NOT IN (SELECT Host_city_ID FROM farm_competition)',
 'SELECT Status FROM city WHERE Population  >  1500 INTERSECT SELECT Status FROM city WHERE Population  <  500',
 'SELECT Status FROM city WHERE Population  >  1500 INTERSECT SELECT Status FROM city WHERE Population  <  500',
 'SELECT Official_Name FROM city WHERE Population  >  1500 OR Population  <  500',
 'SELECT Official_Name FROM city WHERE Population  >  1500 OR Population  <  500',
 'SELECT Census_Ranking FROM city WHERE Status !=  "Village"',
 'SELECT Census_Ranking FROM city WHERE Status !=  "Village"']

In [73]:
question_list

['How many farms are there?',
 'Count the number of farms.',
 'List the total number of horses on farms in ascending order.',
 'What is the total horses record for each farm, sorted ascending?',
 'What are the hosts of competitions whose theme is not "Aliens"?',
 'Return the hosts of competitions for which the theme is not Aliens?',
 'What are the themes of farm competitions sorted by year in ascending order?',
 'Return the themes of farm competitions, sorted by year ascending.',
 'What is the average number of working horses of farms with more than 5000 total number of horses?',
 'Give the average number of working horses on farms with more than 5000 total horses.',
 'What are the maximum and minimum number of cows across all farms.',
 'Return the maximum and minimum number of cows across all farms.',
 'How many different statuses do cities have?',
 'Count the number of different statuses.',
 'List official names of cities in descending order of population.',
 'What are the official names of cities, ordered descending by population?',
 'List the official name and status of the city with the largest population.',
 'What is the official name and status of the city with the most residents?',
 'Show the years and the official names of the host cities of competitions.',
 'Give the years and official names of the cities of each competition.',
 'Show the official names of the cities that have hosted more than one competition.',
 'What are the official names of cities that have hosted more than one competition?',
 'Show the status of the city that has hosted the greatest number of competitions.',
 'What is the status of the city that has hosted the most competitions?',
 'Please show the themes of competitions with host cities having populations larger than 1000.',
 'What are the themes of competitions that have corresponding host cities with more than 1000 residents?',
 'Please show the different statuses of cities and the average population of cities with each status.',
 'What are the statuses and average populations of each city?',
 'Please show the different statuses, ordered by the number of cities that have each.',
 'Return the different statuses of cities, ascending by frequency.',
 'List the most common type of Status across cities.',
 'What is the most common status across all cities?',
 'List the official names of cities that have not held any competition.',
 'What are the official names of cities that have not hosted a farm competition?',
 'Show the status shared by cities with population bigger than 1500 and smaller than 500.',
 'Which statuses correspond to both cities that have a population over 1500 and cities that have a population lower than 500?',
 'Find the official names of cities with population bigger than 1500 or smaller than 500.',
 'What are the official names of cities that have population over 1500 or less than 500?',
 'Show the census ranking of cities whose status are not "Village".',
 'What are the census rankings of cities that do not have the status "Village"?']

In [19]:
spider_df[spider_df["db_id"]=="book_2"].shape

(21, 3)

In [10]:
spider_df[spider_df["db_id"]=="body_builder"]

,db_id,query,question
1150,body_builder,SELECT count(*) FROM body_builder,How many body builders are there?
1151,body_builder,SELECT Total FROM body_builder ORDER BY Total ASC,List the total scores of body builders in asce...
1152,body_builder,"SELECT Snatch , Clean_Jerk FROM body_builder ...",List the snatch score and clean jerk score of ...
1153,body_builder,SELECT avg(Snatch) FROM body_builder,What is the average snatch score of body build...
1154,body_builder,SELECT Clean_Jerk FROM body_builder ORDER BY T...,What are the clean and jerk score of the body ...
1155,body_builder,SELECT Birth_Date FROM People ORDER BY Height ASC,What are the birthdays of people in ascending ...
1156,body_builder,SELECT T2.Name FROM body_builder AS T1 JOIN pe...,What are the names of body builders?
1157,body_builder,SELECT T2.Name FROM body_builder AS T1 JOIN pe...,What are the names of body builders whose tota...
1158,body_builder,SELECT T2.Name FROM body_builder AS T1 JOIN pe...,What is the name of the body builder with the ...
1159,body_builder,"SELECT T2.Birth_Date , T2.Birth_Place FROM bo...",What are the birth date and birth place of the...
1160,body_builder,SELECT T2.Height FROM body_builder AS T1 JOIN ...,What are the heights of body builders with tot...
1161,body_builder,SELECT avg(T1.Total) FROM body_builder AS T1 J...,What is the average total score of body builde...
1162,body_builder,SELECT T2.Name FROM body_builder AS T1 JOIN pe...,What are the names of body builders in descend...
1163,body_builder,"SELECT Birth_Place , COUNT(*) FROM people GRO...",List each birth place along with the number of...
1164,body_builder,SELECT Birth_Place FROM people GROUP BY Birth_...,What is the most common birth place of people?
1165,body_builder,SELECT Birth_Place FROM people GROUP BY Birth_...,What are the birth places that are shared by a...
1166,body_builder,"SELECT Height , Weight FROM people ORDER BY H...",List the height and weight of people in descen...
1167,body_builder,SELECT * FROM body_builder,Show all information about each body builder.
1168,body_builder,"SELECT Name , birth_place FROM people EXCEPT ...",List the names and origins of people who are n...
1169,body_builder,SELECT count(DISTINCT Birth_Place) FROM people,How many distinct birth places are there?
1170,body_builder,SELECT count(*) FROM people WHERE people_id NO...,How many persons are not body builders?
1171,body_builder,SELECT T2.weight FROM body_builder AS T1 JOIN ...,List the weight of the body builders who have ...
1172,body_builder,SELECT T1.total FROM body_builder AS T1 JOIN p...,What are the total scores of the body builders...
1173,body_builder,SELECT min(snatch) FROM body_builder,What is the minimum snatch score?

#### Fetching queries which have JOIN operations

In [12]:
import pandas as pd

# Assuming useful_df is already defined
# Filter rows where 'query' contains the word "join" or "JOIN"
join_df = spider_df[spider_df['query'].str.contains(r'\bjoin\b', case=False, na=False)]

# Display the new DataFrame
print(join_df)

                      db_id  \
6     department_management
9     department_management
12    department_management
13    department_management
14    department_management
...                     ...
6995        culture_company
6996        culture_company
6997        culture_company
6998        culture_company
6999        culture_company

                                                  query  \
6     SELECT DISTINCT T1.creation FROM department AS...
9     SELECT T1.name ,  T1.num_employees FROM depart...
12    SELECT DISTINCT T1.age FROM management AS T2 J...
13    SELECT T3.born_state FROM department AS T1 JOI...
14    SELECT T1.department_id ,  T1.name ,  count(*)...
...                                                 ...
6995  SELECT T1.company_name FROM culture_company AS...
6996  SELECT T1.title ,  T3.book_title FROM movie AS...
6997  SELECT T1.title ,  T3.book_title FROM movie AS...
6998  SELECT T2.company_name FROM movie AS T1 JOIN c...
6999  SELECT T2.company_name FROM movie AS T1 JOIN c...

                                               question
6     What are the distinct creation years of the de...
9     Show the name and number of employees for the ...
12    What are the distinct ages of the heads who ar...
13    List the states where both the secretary of 'T...
14    Which department has more than 1 head at a tim...
...                                                 ...
6995  What are all the company names that have a boo...
6996  Show the movie titles and book titles for all ...
6997  What are the titles of movies and books corres...
6998  Show all company names with a movie directed i...
6999  What are all company names that have a corresp...

[2771 rows x 3 columns]

In [14]:
join_df.shape

(2771, 3)

In [15]:
join_df.head()

,db_id,query,question
6,department_management,SELECT DISTINCT T1.creation FROM department AS...,What are the distinct creation years of the de...
9,department_management,"SELECT T1.name , T1.num_employees FROM depart...",Show the name and number of employees for the ...
12,department_management,SELECT DISTINCT T1.age FROM management AS T2 J...,What are the distinct ages of the heads who ar...
13,department_management,SELECT T3.born_state FROM department AS T1 JOI...,List the states where both the secretary of 'T...
14,department_management,"SELECT T1.department_id , T1.name , count(*)...",Which department has more than 1 head at a tim...

In [16]:
# Iterate through the first 10 rows of useful_df
for index, row in join_df.head(20).iterrows():
    print(f"Row {index}:")
    print(row)
    print("##########")
    print(row["query"])
    print("-" * 80)  # Separator for readability

Row 6:
db_id                                   department_management
query       SELECT DISTINCT T1.creation FROM department AS...
question    What are the distinct creation years of the de...
Name: 6, dtype: object
##########
SELECT DISTINCT T1.creation FROM department AS T1 JOIN management AS T2 ON T1.department_id  =  T2.department_id JOIN head AS T3 ON T2.head_id  =  T3.head_id WHERE T3.born_state  =  'Alabama'
--------------------------------------------------------------------------------
Row 9:
db_id                                   department_management
query       SELECT T1.name ,  T1.num_employees FROM depart...
question    Show the name and number of employees for the ...
Name: 9, dtype: object
##########
SELECT T1.name ,  T1.num_employees FROM department AS T1 JOIN management AS T2 ON T1.department_id  =  T2.department_id WHERE T2.temporary_acting  =  'Yes'
--------------------------------------------------------------------------------
Row 12:
db_id                                   department_management
query       SELECT DISTINCT T1.age FROM management AS T2 J...
question    What are the distinct ages of the heads who ar...
Name: 12, dtype: object
##########
SELECT DISTINCT T1.age FROM management AS T2 JOIN head AS T1 ON T1.head_id  =  T2.head_id WHERE T2.temporary_acting  =  'Yes'
--------------------------------------------------------------------------------
Row 13:
db_id                                   department_management
query       SELECT T3.born_state FROM department AS T1 JOI...
question    List the states where both the secretary of 'T...
Name: 13, dtype: object
##########
SELECT T3.born_state FROM department AS T1 JOIN management AS T2 ON T1.department_id  =  T2.department_id JOIN head AS T3 ON T2.head_id  =  T3.head_id WHERE T1.name  =  'Treasury' INTERSECT SELECT T3.born_state FROM department AS T1 JOIN management AS T2 ON T1.department_id  =  T2.department_id JOIN head AS T3 ON T2.head_id  =  T3.head_id WHERE T1.name  =  'Homeland Security'
--------------------------------------------------------------------------------
Row 14:
db_id                                   department_management
query       SELECT T1.department_id ,  T1.name ,  count(*)...
question    Which department has more than 1 head at a tim...
Name: 14, dtype: object
##########
SELECT T1.department_id ,  T1.name ,  count(*) FROM management AS T2 JOIN department AS T1 ON T1.department_id  =  T2.department_id GROUP BY T1.department_id HAVING count(*)  >  1
--------------------------------------------------------------------------------
Row 34:
db_id                                                    farm
query       SELECT T2.Year ,  T1.Official_Name FROM city A...
question    Show the years and the official names of the h...
Name: 34, dtype: object
##########
SELECT T2.Year ,  T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID
--------------------------------------------------------------------------------
Row 35:
db_id                                                    farm
query       SELECT T2.Year ,  T1.Official_Name FROM city A...
question    Give the years and official names of the citie...
Name: 35, dtype: object
##########
SELECT T2.Year ,  T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID
--------------------------------------------------------------------------------
Row 36:
db_id                                                    farm
query       SELECT T1.Official_Name FROM city AS T1 JOIN f...
question    Show the official names of the cities that hav...
Name: 36, dtype: object
##########
SELECT T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID HAVING COUNT(*)  >  1
--------------------------------------------------------------------------------
Row 37:
db_id                                                    farm
query       SELECT T1.Official_Name FROM city AS T1 JOIN f...
question    What are the official names of cities that hav...
Name: 37, dtype: object
##########
SELECT T1.Official_Name FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID HAVING COUNT(*)  >  1
--------------------------------------------------------------------------------
Row 38:
db_id                                                    farm
query       SELECT T1.Status FROM city AS T1 JOIN farm_com...
question    Show the status of the city that has hosted th...
Name: 38, dtype: object
##########
SELECT T1.Status FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID ORDER BY COUNT(*) DESC LIMIT 1
--------------------------------------------------------------------------------
Row 39:
db_id                                                    farm
query       SELECT T1.Status FROM city AS T1 JOIN farm_com...
question    What is the status of the city that has hosted...
Name: 39, dtype: object
##########
SELECT T1.Status FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID GROUP BY T2.Host_city_ID ORDER BY COUNT(*) DESC LIMIT 1
--------------------------------------------------------------------------------
Row 40:
db_id                                                    farm
query       SELECT T2.Theme FROM city AS T1 JOIN farm_comp...
question    Please show the themes of competitions with ho...
Name: 40, dtype: object
##########
SELECT T2.Theme FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID WHERE T1.Population  >  1000
--------------------------------------------------------------------------------
Row 41:
db_id                                                    farm
query       SELECT T2.Theme FROM city AS T1 JOIN farm_comp...
question    What are the themes of competitions that have ...
Name: 41, dtype: object
##########
SELECT T2.Theme FROM city AS T1 JOIN farm_competition AS T2 ON T1.City_ID  =  T2.Host_city_ID WHERE T1.Population  >  1000
--------------------------------------------------------------------------------
Row 56:
db_id                                      student_assessment
query       SELECT T1.course_name FROM courses AS T1 JOIN ...
question    which course has most number of registered stu...
Name: 56, dtype: object
##########
SELECT T1.course_name FROM courses AS T1 JOIN student_course_registrations AS T2 ON T1.course_id = T2.course_Id GROUP BY T1.course_id ORDER BY count(*) DESC LIMIT 1
--------------------------------------------------------------------------------
Row 57:
db_id                                      student_assessment
query       SELECT T1.course_name FROM courses AS T1 JOIN ...
question    What is the name of the course with the most r...
Name: 57, dtype: object
##########
SELECT T1.course_name FROM courses AS T1 JOIN student_course_registrations AS T2 ON T1.course_id = T2.course_Id GROUP BY T1.course_id ORDER BY count(*) DESC LIMIT 1
--------------------------------------------------------------------------------
Row 60:
db_id                                      student_assessment
query       SELECT T2.first_name ,  T2.last_name FROM cand...
question    what are the first name and last name of all c...
Name: 60, dtype: object
##########
SELECT T2.first_name ,  T2.last_name FROM candidates AS T1 JOIN people AS T2 ON T1.candidate_id = T2.person_id
--------------------------------------------------------------------------------
Row 61:
db_id                                      student_assessment
query       SELECT T2.first_name ,  T2.last_name FROM cand...
question    What are the first and last names of all the c...
Name: 61, dtype: object
##########
SELECT T2.first_name ,  T2.last_name FROM candidates AS T1 JOIN people AS T2 ON T1.candidate_id = T2.person_id
--------------------------------------------------------------------------------
Row 66:
db_id                                      student_assessment
query       SELECT T1.student_id ,  T2.course_name FROM st...
question    What are the ids of all students for courses a...
Name: 66, dtype: object
##########
SELECT T1.student_id ,  T2.course_name FROM student_course_registrations AS T1 JOIN courses AS T2 ON T1.course_id = T2.course_id
--------------------------------------------------------------------------------
Row 67:
db_id                                      student_assessment
query       SELECT T2.student_details FROM student_course_...
question    What is detail of the student who most recentl...
Name: 67, dtype: object
##########
SELECT T2.student_details FROM student_course_registrations AS T1 JOIN students AS T2 ON T1.student_id = T2.student_id ORDER BY T1.registration_date DESC LIMIT 1
--------------------------------------------------------------------------------
Row 68:
db_id                                      student_assessment
query       SELECT T2.student_details FROM student_course_...
question    What details do we have on the students who re...
Name: 68, dtype: object
##########
SELECT T2.student_details FROM student_course_registrations AS T1 JOIN students AS T2 ON T1.student_id = T2.student_id ORDER BY T1.registration_date DESC LIMIT 1
--------------------------------------------------------------------------------