In [26]:
import pandas as pd
import re
from collections import Counter

# Define a list of SQL operations we want to track
operations = ['SELECT', 'FROM', 'JOIN', 'WHERE', 'GROUP BY', 'ORDER BY', 'HAVING', 'LIMIT', 'INSERT', 'UPDATE', 'DELETE']

def query_len(query):
    return len(query)

def count_sql_operations(query):
    # Convert the query to uppercase to handle case insensitivity
    query = query.upper()

    # Initialize a counter to track operation counts
    operation_counts = Counter()

    # Loop through each operation type and count its occurrences
    for operation in operations:
        # Find all occurrences of each operation
        matches = re.findall(r'\b' + re.escape(operation) + r'\b', query)
        operation_counts[operation] = len(matches)

    return operation_counts

In [27]:
########################################################################
######### CHANGE INPUT FOLDER HERE #####################################
########################################################################
file_path = r"C:\Research-Paper\PAPER-WORK-2024\Outputs\Spider-Data-7.xlsx"
# Read the excel file
df = pd.read_excel(file_path, engine='openpyxl')
df.head()

,db_id,spider_query,question,text2sql_query
0,farm,SELECT count(*) FROM farm,How many farms are there?,"SELECT COUNT(DISTINCT f.Farm_ID) FROM ""farm"" f;"
1,farm,SELECT count(*) FROM farm,Count the number of farms.,"SELECT COUNT(DISTINCT f.""Farm_ID"") FROM ""farm"" f;"
2,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,List the total number of horses on farms in as...,"SELECT f.""Farm_ID"", f.""Year"", f.""Total_Horses""..."
3,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,"What is the total horses record for each farm,...","SELECT f.Farm_ID, f.Total_Horses FROM farm f O..."
4,farm,SELECT Hosts FROM farm_competition WHERE Theme...,What are the hosts of competitions whose theme...,SELECT DISTINCT fc.Hosts FROM farm_competition...

In [28]:
for index, row in df.iterrows():

    print("Number of row: ",index)
    
    target_query = row['spider_query']
    predicted_query = row['text2sql_query']

    # get query length
    target_len = query_len(target_query)

    # Store the len for query 1 in the DataFrame
    df.at[index, 'spider_query_length'] = str(target_len)
    print("Length of target_query:", target_len)

    # get query length
    predicted_len = query_len(predicted_query)

    # Store the len for query 2 in the DataFrame
    df.at[index, 'text2sql_query_length'] = str(predicted_len)
    print("Length of predicted_query:", predicted_len)
    
    # Compare the length
    if predicted_len == target_len:
        df.at[index, 'hallucination'] = False
    else:

        predicted_operations_counts = count_sql_operations(predicted_query)
        target_operations_counts = count_sql_operations(target_query)
        # print(predicted_operations_counts,predicted_query,target_operations_counts,target_query)
        
    # Matching counts
    matching_counts = sum(1 for key in predicted_operations_counts if predicted_operations_counts[key] == target_operations_counts[key])
    
    # Calculate the total number of clauses (operations)
    total_clauses = len(predicted_operations_counts)
    
    # Calculate the similarity score as the percentage of matching counts
    similarity_score = matching_counts / total_clauses
    
    # Print the results
    print(f"Matching Clause Counts: {matching_counts}")
    print(f"Total Clauses: {total_clauses}")
    print(f"Similarity Score: {similarity_score:.2f}")
    
    # Optionally, you can also print the differences:
    difference = predicted_operations_counts - target_operations_counts
    for ops in operations:
        try:
            ops_value = dict(difference)[ops]
        except:
            ops_value = 0
            
        df.at[index, ops+'__difference'] = ops_value
        
    if (len(dict(difference).values()) > 0) and (max(dict(difference).values()) > 5) :
        df.at[index, 'hallucination'] = True
    else:
        df.at[index, 'hallucination'] = False
    print("#"*50)

Number of row:  0
Length of target_query: 25
Length of predicted_query: 47
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  1
Length of target_query: 25
Length of predicted_query: 49
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  2
Length of target_query: 55
Length of predicted_query: 91
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  3
Length of target_query: 55
Length of predicted_query: 73
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  4
Length of target_query: 59
Length of predicted_query: 76
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  5
Length of target_query: 59
Length of predicted_query: 67
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  6
Length of target_query: 52
Length of predicted_query: 71
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  7
Length of target_query: 52
Length of predicted_query: 79
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  8
Length of target_query: 64
Length of predicted_query: 95
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  9
Length of target_query: 64
Length of predicted_query: 95
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  10
Length of target_query: 39
Length of predicted_query: 68
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  11
Length of target_query: 39
Length of predicted_query: 68
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  12
Length of target_query: 39
Length of predicted_query: 46
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  13
Length of target_query: 39
Length of predicted_query: 52
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  14
Length of target_query: 55
Length of predicted_query: 76
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  15
Length of target_query: 55
Length of predicted_query: 76
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  16
Length of target_query: 73
Length of predicted_query: 80
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  17
Length of target_query: 73
Length of predicted_query: 80
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  18
Length of target_query: 112
Length of predicted_query: 151
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  19
Length of target_query: 112
Length of predicted_query: 132
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  20
Length of target_query: 148
Length of predicted_query: 237
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  21
Length of target_query: 148
Length of predicted_query: 234
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  22
Length of target_query: 150
Length of predicted_query: 253
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  23
Length of target_query: 150
Length of predicted_query: 355
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  24
Length of target_query: 122
Length of predicted_query: 139
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  25
Length of target_query: 122
Length of predicted_query: 148
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  26
Length of target_query: 58
Length of predicted_query: 118
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  27
Length of target_query: 58
Length of predicted_query: 118
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  28
Length of target_query: 61
Length of predicted_query: 94
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  29
Length of target_query: 61
Length of predicted_query: 107
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  30
Length of target_query: 70
Length of predicted_query: 102
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  31
Length of target_query: 70
Length of predicted_query: 102
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  32
Length of target_query: 95
Length of predicted_query: 155
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  33
Length of target_query: 95
Length of predicted_query: 106
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  34
Length of target_query: 108
Length of predicted_query: 108
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  35
Length of target_query: 108
Length of predicted_query: 137
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  36
Length of target_query: 78
Length of predicted_query: 119
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  37
Length of target_query: 78
Length of predicted_query: 119
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  38
Length of target_query: 58
Length of predicted_query: 102
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  39
Length of target_query: 58
Length of predicted_query: 100
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  40
Length of target_query: 57
Length of predicted_query: 98
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  41
Length of target_query: 57
Length of predicted_query: 98
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  42
Length of target_query: 104
Length of predicted_query: 207
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  43
Length of target_query: 104
Length of predicted_query: 212
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  44
Length of target_query: 86
Length of predicted_query: 94
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  45
Length of target_query: 86
Length of predicted_query: 94
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  46
Length of target_query: 116
Length of predicted_query: 171
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  47
Length of target_query: 116
Length of predicted_query: 171
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  48
Length of target_query: 88
Length of predicted_query: 89
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  49
Length of target_query: 88
Length of predicted_query: 98
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  50
Length of target_query: 96
Length of predicted_query: 231
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  51
Length of target_query: 96
Length of predicted_query: 231
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  52
Length of target_query: 165
Length of predicted_query: 199
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  53
Length of target_query: 165
Length of predicted_query: 199
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  54
Length of target_query: 307
Length of predicted_query: 365
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  55
Length of target_query: 307
Length of predicted_query: 266
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  56
Length of target_query: 86
Length of predicted_query: 169
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  57
Length of target_query: 86
Length of predicted_query: 107
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  58
Length of target_query: 177
Length of predicted_query: 206
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  59
Length of target_query: 177
Length of predicted_query: 185
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  60
Length of target_query: 71
Length of predicted_query: 110
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  61
Length of target_query: 71
Length of predicted_query: 84
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  62
Length of target_query: 76
Length of predicted_query: 108
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  63
Length of target_query: 76
Length of predicted_query: 97
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  64
Length of target_query: 77
Length of predicted_query: 70
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  65
Length of target_query: 77
Length of predicted_query: 100
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  66
Length of target_query: 84
Length of predicted_query: 124
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  67
Length of target_query: 84
Length of predicted_query: 94
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  68
Length of target_query: 191
Length of predicted_query: 90
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  69
Length of target_query: 191
Length of predicted_query: 90
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  70
Length of target_query: 81
Length of predicted_query: 113
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  71
Length of target_query: 81
Length of predicted_query: 99
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  72
Length of target_query: 196
Length of predicted_query: 190
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  73
Length of target_query: 196
Length of predicted_query: 190
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  74
Length of target_query: 90
Length of predicted_query: 141
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  75
Length of target_query: 90
Length of predicted_query: 99
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  76
Length of target_query: 99
Length of predicted_query: 131
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  77
Length of target_query: 99
Length of predicted_query: 163
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  78
Length of target_query: 37
Length of predicted_query: 34
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  79
Length of target_query: 37
Length of predicted_query: 43
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  80
Length of target_query: 73
Length of predicted_query: 118
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  81
Length of target_query: 73
Length of predicted_query: 123
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  82
Length of target_query: 61
Length of predicted_query: 64
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  83
Length of target_query: 55
Length of predicted_query: 132
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  84
Length of target_query: 78
Length of predicted_query: 126
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  85
Length of target_query: 84
Length of predicted_query: 121
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  86
Length of target_query: 79
Length of predicted_query: 86
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  87
Length of target_query: 81
Length of predicted_query: 170
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  88
Length of target_query: 97
Length of predicted_query: 108
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  89
Length of target_query: 138
Length of predicted_query: 186
Matching Clause Counts: 5
Total Clauses: 11
Similarity Score: 0.45
##################################################
Number of row:  90
Length of target_query: 55
Length of predicted_query: 77
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  91
Length of target_query: 94
Length of predicted_query: 95
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  92
Length of target_query: 43
Length of predicted_query: 74
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  93
Length of target_query: 48
Length of predicted_query: 104
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  94
Length of target_query: 81
Length of predicted_query: 128
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  95
Length of target_query: 94
Length of predicted_query: 117
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  96
Length of target_query: 120
Length of predicted_query: 119
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  97
Length of target_query: 90
Length of predicted_query: 137
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  98
Length of target_query: 74
Length of predicted_query: 117
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  99
Length of target_query: 65
Length of predicted_query: 104
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  100
Length of target_query: 28
Length of predicted_query: 29
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  101
Length of target_query: 28
Length of predicted_query: 29
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  102

Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  224
Length of target_query: 65
Length of predicted_query: 104
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  225
Length of target_query: 65
Length of predicted_query: 104
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  226
Length of target_query: 107
Length of predicted_query: 92
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  227
Length of target_query: 107
Length of predicted_query: 91
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  228
Length of target_query: 136
Length of predicted_query: 133
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  229
Length of target_query: 136
Length of predicted_query: 152
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  230
Length of target_query: 68
Length of predicted_query: 68
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  231
Length of target_query: 68
Length of predicted_query: 68
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  232
Length of target_query: 135
Length of predicted_query: 62
Matching Clause Counts: 5
Total Clauses: 11
Similarity Score: 0.45
##################################################
Number of row:  233
Length of target_query: 135
Length of predicted_query: 146
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  234
Length of target_query: 106
Length of predicted_query: 118
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  235
Length of target_query: 106
Length of predicted_query: 233
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  236
Length of target_query: 222
Length of predicted_query: 166
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  237
Length of target_query: 222
Length of predicted_query: 291
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  238
Length of target_query: 193
Length of predicted_query: 200
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  239
Length of target_query: 193
Length of predicted_query: 231
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  240
Length of target_query: 112
Length of predicted_query: 135
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  241
Length of target_query: 112
Length of predicted_query: 106
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  242
Length of target_query: 160
Length of predicted_query: 135
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  243
Length of target_query: 160
Length of predicted_query: 140
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  244
Length of target_query: 159
Length of predicted_query: 145
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  245
Length of target_query: 159
Length of predicted_query: 164
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  246
Length of target_query: 174
Length of predicted_query: 180
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  247
Length of target_query: 174
Length of predicted_query: 233
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  248
Length of target_query: 55
Length of predicted_query: 103
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  249
Length of target_query: 55
Length of predicted_query: 141
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  250
Length of target_query: 186
Length of predicted_query: 143
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  251
Length of target_query: 186
Length of predicted_query: 147
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  252
Length of target_query: 155
Length of predicted_query: 127
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  253
Length of target_query: 155
Length of predicted_query: 129
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  254
Length of target_query: 118
Length of predicted_query: 187
Matching Clause Counts: 5
Total Clauses: 11
Similarity Score: 0.45
##################################################
Number of row:  255
Length of target_query: 118
Length of predicted_query: 179
Matching Clause Counts: 5
Total Clauses: 11
Similarity Score: 0.45
##################################################
Number of row:  256
Length of target_query: 66
Length of predicted_query: 84
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  257
Length of target_query: 66
Length of predicted_query: 84
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  258
Length of target_query: 91
Length of predicted_query: 107
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  259
Length of target_query: 91
Length of predicted_query: 158
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  260
Length of target_query: 107
Length of predicted_query: 160
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  261
Length of target_query: 107
Length of predicted_query: 167
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  262
Length of target_query: 140
Length of predicted_query: 146
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  263
Length of target_query: 140
Length of predicted_query: 161
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  264
Length of target_query: 135
Length of predicted_query: 254
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  265
Length of target_query: 135
Length of predicted_query: 228
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  266
Length of target_query: 113
Length of predicted_query: 195
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  267
Length of target_query: 113
Length of predicted_query: 211
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  268
Length of target_query: 158
Length of predicted_query: 191
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  269
Length of target_query: 158
Length of predicted_query: 159
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  270
Length of target_query: 126
Length of predicted_query: 175
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  271
Length of target_query: 126
Length of predicted_query: 180
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  272
Length of target_query: 136
Length of predicted_query: 128
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  273
Length of target_query: 136
Length of predicted_query: 149
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  274
Length of target_query: 128
Length of predicted_query: 152
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  275
Length of target_query: 128
Length of predicted_query: 154
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  276
Length of target_query: 102
Length of predicted_query: 150
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  277
Length of target_query: 102
Length of predicted_query: 117
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  278
Length of target_query: 94
Length of predicted_query: 85
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  279
Length of target_query: 94
Length of predicted_query: 79
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  280
Length of target_query: 177
Length of predicted_query: 194
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  281
Length of target_query: 177
Length of predicted_query: 236
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  282
Length of target_query: 138
Length of predicted_query: 141
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  283
Length of target_query: 138
Length of predicted_query: 143
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  284
Length of target_query: 72
Length of predicted_query: 128
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  285
Length of target_query: 72
Length of predicted_query: 127
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  286
Length of target_query: 70
Length of predicted_query: 71
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  287
Length of target_query: 70
Length of predicted_query: 71
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  288
Length of target_query: 39
Length of predicted_query: 77
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  289
Length of target_query: 39
Length of predicted_query: 126
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  290
Length of target_query: 177
Length of predicted_query: 94
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  291
Length of target_query: 177
Length of predicted_query: 94
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  292
Length of target_query: 76
Length of predicted_query: 72
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  293
Length of target_query: 76
Length of predicted_query: 72
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  294
Length of target_query: 199
Length of predicted_query: 103
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  295
Length of target_query: 199
Length of predicted_query: 116
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  296
Length of target_query: 195
Length of predicted_query: 120
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  297
Length of target_query: 195
Length of predicted_query: 120
Matching Clause Counts: 6
Total Clauses: 11
Similarity Score: 0.55
##################################################
Number of row:  298
Length of target_query: 27
Length of predicted_query: 32
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  299
Length of target_query: 27
Length of predicted_query: 32
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  300
Length of target_query: 44
Length of predicted_query: 85
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  301
Length of target_query: 44
Length of predicted_query: 85
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  302
Length of target_query: 34
Length of predicted_query: 63
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  303
Length of target_query: 34
Length of predicted_query: 63
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  304
Length of target_query: 53
Length of predicted_query: 96
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  305
Length of target_query: 53
Length of predicted_query: 96
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  306
Length of target_query: 38
Length of predicted_query: 76
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  307
Length of target_query: 38
Length of predicted_query: 76
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  308
Length of target_query: 58
Length of predicted_query: 65
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  309
Length of target_query: 58
Length of predicted_query: 65
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  310
Length of target_query: 50
Length of predicted_query: 57
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  311
Length of target_query: 50
Length of predicted_query: 61
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  312
Length of target_query: 42
Length of predicted_query: 80
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  313
Length of target_query: 42
Length of predicted_query: 80
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  314
Length of target_query: 42
Length of predicted_query: 51
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  315
Length of target_query: 42
Length of predicted_query: 49
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  316
Length of target_query: 81
Length of predicted_query: 106
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  317
Length of target_query: 81
Length of predicted_query: 106
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  318
Length of target_query: 66
Length of predicted_query: 100
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  319
Length of target_query: 66
Length of predicted_query: 100
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  320
Length of target_query: 22
Length of predicted_query: 160
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  321
Length of target_query: 22
Length of predicted_query: 59
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  322
Length of target_query: 106
Length of predicted_query: 126
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  323
Length of target_query: 106
Length of predicted_query: 129
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  324
Length of target_query: 119
Length of predicted_query: 155
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91

Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  449
Length of target_query: 368
Length of predicted_query: 320
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  450
Length of target_query: 110
Length of predicted_query: 117
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  451
Length of target_query: 110
Length of predicted_query: 117
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  452
Length of target_query: 88
Length of predicted_query: 111
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  453
Length of target_query: 88
Length of predicted_query: 111
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  454
Length of target_query: 87
Length of predicted_query: 110
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  455
Length of target_query: 87
Length of predicted_query: 110
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  456
Length of target_query: 124
Length of predicted_query: 155
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  457
Length of target_query: 124
Length of predicted_query: 137
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  458
Length of target_query: 103
Length of predicted_query: 116
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  459
Length of target_query: 103
Length of predicted_query: 106
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  460
Length of target_query: 123
Length of predicted_query: 137
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  461
Length of target_query: 123
Length of predicted_query: 137
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  462
Length of target_query: 176
Length of predicted_query: 199
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  463
Length of target_query: 176
Length of predicted_query: 178
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  464
Length of target_query: 167
Length of predicted_query: 141
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  465
Length of target_query: 167
Length of predicted_query: 140
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  466
Length of target_query: 71
Length of predicted_query: 67
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  467
Length of target_query: 71
Length of predicted_query: 67
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  468
Length of target_query: 43
Length of predicted_query: 72
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  469
Length of target_query: 43
Length of predicted_query: 72
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  470
Length of target_query: 177
Length of predicted_query: 263
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  471
Length of target_query: 177
Length of predicted_query: 263
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  472
Length of target_query: 61
Length of predicted_query: 104
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  473
Length of target_query: 61
Length of predicted_query: 102
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  474
Length of target_query: 100
Length of predicted_query: 143
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  475
Length of target_query: 100
Length of predicted_query: 123
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  476
Length of target_query: 99
Length of predicted_query: 133
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  477
Length of target_query: 99
Length of predicted_query: 142
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  478
Length of target_query: 40
Length of predicted_query: 72
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  479
Length of target_query: 40
Length of predicted_query: 72
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  480
Length of target_query: 47
Length of predicted_query: 91
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  481
Length of target_query: 47
Length of predicted_query: 91
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  482
Length of target_query: 103
Length of predicted_query: 180
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  483
Length of target_query: 103
Length of predicted_query: 180
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  484
Length of target_query: 32
Length of predicted_query: 28
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  485
Length of target_query: 32
Length of predicted_query: 49
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  486
Length of target_query: 107
Length of predicted_query: 112
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  487
Length of target_query: 107
Length of predicted_query: 112
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  488
Length of target_query: 159
Length of predicted_query: 120
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  489
Length of target_query: 159
Length of predicted_query: 120
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  490
Length of target_query: 180
Length of predicted_query: 163
Matching Clause Counts: 5
Total Clauses: 11
Similarity Score: 0.45
##################################################
Number of row:  491
Length of target_query: 180
Length of predicted_query: 209
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  492
Length of target_query: 38
Length of predicted_query: 69
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  493
Length of target_query: 38
Length of predicted_query: 72
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  494
Length of target_query: 25
Length of predicted_query: 26
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  495
Length of target_query: 25
Length of predicted_query: 26
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  496
Length of target_query: 34
Length of predicted_query: 70
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  497
Length of target_query: 34
Length of predicted_query: 70
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  498
Length of target_query: 37
Length of predicted_query: 59
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  499
Length of target_query: 37
Length of predicted_query: 65
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  500
Length of target_query: 64
Length of predicted_query: 142
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  501
Length of target_query: 64
Length of predicted_query: 109
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  502
Length of target_query: 59
Length of predicted_query: 99
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  503
Length of target_query: 59
Length of predicted_query: 99
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  504
Length of target_query: 59
Length of predicted_query: 100
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  505
Length of target_query: 59
Length of predicted_query: 92
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  506
Length of target_query: 55
Length of predicted_query: 58
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  507
Length of target_query: 55
Length of predicted_query: 58
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  508
Length of target_query: 47
Length of predicted_query: 54
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  509
Length of target_query: 47
Length of predicted_query: 61
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  510
Length of target_query: 54
Length of predicted_query: 78
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  511
Length of target_query: 54
Length of predicted_query: 78
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  512
Length of target_query: 105
Length of predicted_query: 138
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  513
Length of target_query: 105
Length of predicted_query: 96
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  514
Length of target_query: 129
Length of predicted_query: 120
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  515
Length of target_query: 129
Length of predicted_query: 151
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  516
Length of target_query: 145
Length of predicted_query: 154
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  517
Length of target_query: 145
Length of predicted_query: 154
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  518
Length of target_query: 113
Length of predicted_query: 144
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  519
Length of target_query: 113
Length of predicted_query: 144
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  520
Length of target_query: 150
Length of predicted_query: 153
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  521
Length of target_query: 150
Length of predicted_query: 153
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  522
Length of target_query: 51
Length of predicted_query: 123
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  523
Length of target_query: 51
Length of predicted_query: 124
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  524
Length of target_query: 70
Length of predicted_query: 122
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  525
Length of target_query: 70
Length of predicted_query: 111
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  526
Length of target_query: 62
Length of predicted_query: 113
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  527
Length of target_query: 62
Length of predicted_query: 136
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  528
Length of target_query: 88
Length of predicted_query: 113
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  529
Length of target_query: 88
Length of predicted_query: 113
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  530
Length of target_query: 126
Length of predicted_query: 91
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  531
Length of target_query: 126
Length of predicted_query: 145
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  532
Length of target_query: 64
Length of predicted_query: 72
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  533
Length of target_query: 64
Length of predicted_query: 72
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  534
Length of target_query: 87
Length of predicted_query: 109
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  535
Length of target_query: 87
Length of predicted_query: 108
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  536
Length of target_query: 80
Length of predicted_query: 166
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  537
Length of target_query: 80
Length of predicted_query: 166
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  538
Length of target_query: 131
Length of predicted_query: 217
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  539
Length of target_query: 131
Length of predicted_query: 149
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  540
Length of target_query: 183
Length of predicted_query: 4135
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  541
Length of target_query: 183
Length of predicted_query: 117
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  542
Length of target_query: 27
Length of predicted_query: 32
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  543
Length of target_query: 27
Length of predicted_query: 32
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  544
Length of target_query: 47
Length of predicted_query: 56
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  545
Length of target_query: 47
Length of predicted_query: 72
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  546
Length of target_query: 63
Length of predicted_query: 99
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  547
Length of target_query: 63
Length of predicted_query: 101
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  548
Length of target_query: 49
Length of predicted_query: 69
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  549
Length of target_query: 49
Length of predicted_query: 69
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00

##################################################
Number of row:  697
Length of target_query: 45
Length of predicted_query: 50
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  698
Length of target_query: 45
Length of predicted_query: 52
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  699
Length of target_query: 62
Length of predicted_query: 97
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  700
Length of target_query: 62
Length of predicted_query: 117
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  701
Length of target_query: 68
Length of predicted_query: 87
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  702
Length of target_query: 68
Length of predicted_query: 87
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  703
Length of target_query: 67
Length of predicted_query: 144
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  704
Length of target_query: 67
Length of predicted_query: 130
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  705
Length of target_query: 65
Length of predicted_query: 142
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  706
Length of target_query: 65
Length of predicted_query: 78
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  707
Length of target_query: 144
Length of predicted_query: 184
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  708
Length of target_query: 144
Length of predicted_query: 170
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  709
Length of target_query: 139
Length of predicted_query: 136
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  710
Length of target_query: 139
Length of predicted_query: 108
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################
Number of row:  711
Length of target_query: 181
Length of predicted_query: 150
Matching Clause Counts: 7
Total Clauses: 11
Similarity Score: 0.64
##################################################
Number of row:  712
Length of target_query: 181
Length of predicted_query: 144
Matching Clause Counts: 11
Total Clauses: 11
Similarity Score: 1.00
##################################################
Number of row:  713
Length of target_query: 158
Length of predicted_query: 189
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  714
Length of target_query: 158
Length of predicted_query: 167
Matching Clause Counts: 10
Total Clauses: 11
Similarity Score: 0.91
##################################################
Number of row:  715
Length of target_query: 179
Length of predicted_query: 189
Matching Clause Counts: 5
Total Clauses: 11
Similarity Score: 0.45
##################################################
Number of row:  716
Length of target_query: 179
Length of predicted_query: 189
Matching Clause Counts: 5
Total Clauses: 11
Similarity Score: 0.45
##################################################
Number of row:  717
Length of target_query: 313
Length of predicted_query: 240
Matching Clause Counts: 9
Total Clauses: 11
Similarity Score: 0.82
##################################################
Number of row:  718
Length of target_query: 313
Length of predicted_query: 265
Matching Clause Counts: 8
Total Clauses: 11
Similarity Score: 0.73
##################################################

In [29]:
df.head()

,db_id,spider_query,question,text2sql_query,spider_query_length,text2sql_query_length,SELECT__difference,FROM__difference,JOIN__difference,WHERE__difference,GROUP BY__difference,ORDER BY__difference,HAVING__difference,LIMIT__difference,INSERT__difference,UPDATE__difference,DELETE__difference,hallucination
0,farm,SELECT count(*) FROM farm,How many farms are there?,"SELECT COUNT(DISTINCT f.Farm_ID) FROM ""farm"" f;",25,47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
1,farm,SELECT count(*) FROM farm,Count the number of farms.,"SELECT COUNT(DISTINCT f.""Farm_ID"") FROM ""farm"" f;",25,49,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
2,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,List the total number of horses on farms in as...,"SELECT f.""Farm_ID"", f.""Year"", f.""Total_Horses""...",55,91,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
3,farm,SELECT Total_Horses FROM farm ORDER BY Total_H...,"What is the total horses record for each farm,...","SELECT f.Farm_ID, f.Total_Horses FROM farm f O...",55,73,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4,farm,SELECT Hosts FROM farm_competition WHERE Theme...,What are the hosts of competitions whose theme...,SELECT DISTINCT fc.Hosts FROM farm_competition...,59,76,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False

In [30]:
#############################################################################
######### CHANGE OUTPUT FOLDER FILE HERE ####################################
#############################################################################
output_file_path = r"C:\Research-Paper\PAPER-WORK-2024\Outputs\Spider-Data-7-Hallucination-Check.xlsx"
df.to_excel(output_file_path, index=False)
print(f"DataFrame saved successfully to {output_file_path}")

DataFrame saved successfully to C:\Research-Paper\PAPER-WORK-2024\Outputs\Spider-Data-7-Hallucination-Check.xlsx